/* =========================================================
   오늘의 모의고사 — 문제 뱅크 + 날짜 시드 자동 생성기
   -----------------------------------------------------------
   설계 원칙:
   - 여기 있는 각 항목의 matchTitle은 script.js의 quizDB에 있는
     title과 정확히 일치해야 함 → 그래야 sourceUrl이 자동으로 맞게 연결됨.
   - 오늘 날짜를 시드로 써서, 같은 날에는 전 세계 누구나 같은 문제를 보고,
     자정이 지나면 자동으로 다른 조합으로 바뀜.
   - 교육 콘텐츠(설명/선택지)는 한글+로마자+영어를 항상 함께 표시.
     UI 버튼/피드백 문구는 사이트 전체 컨벤션에 맞춰 영어로 표시(test.html에서 처리).
   ========================================================= */

window.dailyQuizBank = window.dailyQuizBank || [
  // ---- 공구/도구 ----
  { kr: "커터칼", rom: "keoteokal", en: "Cutter Knife",
    tip: "종이나 박스를 자를 때 쓰는 날카로운 칼입니다.",
    tipRom: "Jongi-na bakseu-reul jareul ttae sseuneun nalkaroun kal-imnida.",
    tipEn: "A sharp knife used to cut paper or boxes.", matchTitle: "Cutter Knife" },
  { kr: "가위", rom: "gawi", en: "Scissors",
    tip: "손으로 종이나 천을 자를 때 쓰는 도구입니다.",
    tipRom: "Son-euro jongi-na cheon-eul jareul ttae sseuneun dogu-imnida.",
    tipEn: "A tool used by hand to cut paper or cloth.", matchTitle: "Scissors" },
  { kr: "망치", rom: "mangchi", en: "Hammer",
    tip: "못을 박거나 물건을 두드릴 때 쓰는 도구입니다.",
    tipRom: "Mos-eul bakgeona mulgeon-eul dudeuril ttae sseuneun dogu-imnida.",
    tipEn: "A tool used to drive nails or strike objects.", matchTitle: "Hammer" },
  { kr: "드라이버", rom: "deuraibeo", en: "Screwdriver",
    tip: "나사를 돌려서 조이거나 풀 때 쓰는 도구입니다.",
    tipRom: "Nasa-reul dollyeoseo joigeona pul ttae sseuneun dogu-imnida.",
    tipEn: "A tool used to turn screws to tighten or loosen them.", matchTitle: "Screwdriver" },
  { kr: "스패너", rom: "seupaeneo", en: "Spanner / Wrench",
    tip: "볼트나 너트를 돌려서 조이는 공구입니다.",
    tipRom: "Bolteu-na neoteu-reul dollyeoseo joineun gonggu-imnida.",
    tipEn: "A tool used to turn and tighten bolts or nuts.", matchTitle: "Spanner / Wrench" },
  { kr: "펜치", rom: "penchi", en: "Pliers",
    tip: "물건을 집거나 철사를 구부릴 때 쓰는 도구입니다.",
    tipRom: "Mulgeon-eul jipgeona cheolsa-reul guburil ttae sseuneun dogu-imnida.",
    tipEn: "A tool used to grip objects or bend wire.", matchTitle: "Pliers" },
  { kr: "니퍼", rom: "nipeo", en: "Nippers",
    tip: "철사나 전선을 자를 때 쓰는 작은 도구입니다.",
    tipRom: "Cheolsa-na jeonseon-eul jareul ttae sseuneun jageun dogu-imnida.",
    tipEn: "A small tool used to cut wire or cables.", matchTitle: "Nippers" },
  { kr: "줄자", rom: "julja", en: "Tape Measure",
    tip: "물건의 길이를 잴 때 쓰는 도구입니다.",
    tipRom: "Mulgeon-ui giri-reul jael ttae sseuneun dogu-imnida.",
    tipEn: "A tool used to measure the length of an object.", matchTitle: "Tape Measure" },

  // ---- 안전 장비 ----
  { kr: "안전모", rom: "anjeonmo", en: "Safety Helmet",
    tip: "머리를 다치지 않게 보호하기 위해 쓰는 모자입니다.",
    tipRom: "Meori-reul dachiji anke bohohagi wihae sseuneun moja-imnida.",
    tipEn: "A hat worn to protect the head from injury.", matchTitle: "Safety Helmet" },
  { kr: "안전화", rom: "anjeonhwa", en: "Safety Shoes",
    tip: "발을 보호하기 위해 신는 튼튼한 신발입니다.",
    tipRom: "Bal-eul bohohagi wihae sinneun teunteunhan sinbal-imnida.",
    tipEn: "Sturdy shoes worn to protect the feet.", matchTitle: "Safety Shoes" },
  { kr: "안전장갑", rom: "anjeonjanggap", en: "Safety Gloves",
    tip: "손을 다치지 않게 보호하기 위해 끼는 장갑입니다.",
    tipRom: "Son-eul dachiji anke bohohagi wihae kkineun janggap-imnida.",
    tipEn: "Gloves worn to protect the hands from injury.", matchTitle: "Safety Gloves" },
  { kr: "보안경", rom: "boangyeong", en: "Safety Goggles",
    tip: "눈을 보호하기 위해 쓰는 안경입니다.",
    tipRom: "Nun-eul bohohagi wihae sseuneun angyeong-imnida.",
    tipEn: "Glasses worn to protect the eyes.", matchTitle: "Safety Goggles" },
  { kr: "방진마스크", rom: "bangjinmaseukeu", en: "Dust Mask",
    tip: "먼지를 막기 위해 코와 입에 쓰는 마스크입니다.",
    tipRom: "Meonji-reul makgi wihae ko-wa ib-e sseuneun maseukeu-imnida.",
    tipEn: "A mask worn over the nose and mouth to block dust.", matchTitle: "Dust Mask" },
  { kr: "귀마개", rom: "gwimagae", en: "Earplug",
    tip: "시끄러운 소리로부터 귀를 보호하기 위해 끼는 물건입니다.",
    tipRom: "Sikkeureoun sori-robuteo gwi-reul bohohagi wihae kkineun mulgeon-imnida.",
    tipEn: "A small item worn to protect the ears from loud noise.", matchTitle: "Earplug" },
  { kr: "안전대", rom: "anjeondae", en: "Safety Harness",
    tip: "높은 곳에서 일할 때 떨어지지 않도록 몸에 착용하는 장비입니다.",
    tipRom: "Nopeun gos-eseo ilhal ttae tteoreojiji ando-rok mom-e chagyonghaneun jangbi-imnida.",
    tipEn: "Equipment worn on the body to prevent falling while working at heights.", matchTitle: "Safety Harness" },
  { kr: "소화기", rom: "sohwagi", en: "Fire Extinguisher",
    tip: "불이 났을 때 불을 끄는 데 쓰는 도구입니다.",
    tipRom: "Bul-i nass-eul ttae bul-eul kkeuneun de sseuneun dogu-imnida.",
    tipEn: "A tool used to put out a fire.", matchTitle: "Fire Extinguisher" },
  { kr: "구급함", rom: "gugeupham", en: "First Aid Kit",
    tip: "다쳤을 때 응급 처치에 필요한 물건이 들어 있는 상자입니다.",
    tipRom: "Dachyeoss-eul ttae eunggeup cheochi-e pilyohan mulgeon-i deur-eo issneun sangja-imnida.",
    tipEn: "A box containing items needed for emergency treatment when injured.", matchTitle: "First Aid Kit" },
  { kr: "방독마스크", rom: "bangdokmaseukeu", en: "Gas Mask",
    tip: "유해 가스로부터 호흡기를 보호하기 위해 쓰는 마스크입니다.",
    tipRom: "Yuhae gaseu-robuteo hoheubgi-reul bohohagi wihae sseuneun maseukeu-imnida.",
    tipEn: "A mask worn to protect the respiratory system from harmful gas.", matchTitle: "Gas Mask" },

  // ---- 근로/노무 용어 ----
  { kr: "병가", rom: "byeongga", en: "Sick Leave",
    tip: "몸이 아파서 회사를 쉬는 것입니다.",
    tipRom: "Mom-i apaseo hoesa-reul swineun geos-imnida.",
    tipEn: "Taking time off work because you are sick.", matchTitle: "Sick Leave" },
  { kr: "휴가", rom: "hyuga", en: "Vacation",
    tip: "일하지 않고 쉬는 날입니다.",
    tipRom: "Ilhaji anko swineun nal-imnida.",
    tipEn: "A day off from work.", matchTitle: "Vacation" },
  { kr: "지각", rom: "jigak", en: "Lateness",
    tip: "정해진 시간보다 늦게 도착하는 것입니다.",
    tipRom: "Jeonghaejin sigan-boda neutge dochakhaneun geos-imnida.",
    tipEn: "Arriving later than the scheduled time.", matchTitle: "Lateness" },
  { kr: "조퇴", rom: "jotoe", en: "Leaving Early",
    tip: "정해진 시간보다 일찍 회사에서 나가는 것입니다.",
    tipRom: "Jeonghaejin sigan-boda iljjik hoesa-eseo naganeun geos-imnida.",
    tipEn: "Leaving work earlier than the scheduled time.", matchTitle: "Leaving Early" },
  { kr: "결근", rom: "gyeolgeun", en: "Absence",
    tip: "출근해야 하는 날에 회사에 나오지 않는 것입니다.",
    tipRom: "Chulgeunhaeya haneun nal-e hoesa-e naoji anneun geos-imnida.",
    tipEn: "Not coming to work on a day you are scheduled to work.", matchTitle: "Absence" },
  { kr: "야근", rom: "yageun", en: "Night Overtime",
    tip: "밤늦게까지 일을 더 하는 것입니다.",
    tipRom: "Bam-neutge-kkaji il-eul deo haneun geos-imnida.",
    tipEn: "Working extra hours late into the night.", matchTitle: "Night Overtime" },
  { kr: "퇴근", rom: "toegeun", en: "Leave Work",
    tip: "일을 마치고 회사에서 집으로 가는 것입니다.",
    tipRom: "Il-eul machigo hoesa-eseo jib-euro ganeun geos-imnida.",
    tipEn: "Finishing work and going home from the company.", matchTitle: "Leave Work" },
  { kr: "출근", rom: "chulgeun", en: "Go to Work",
    tip: "일하러 회사에 가는 것입니다.",
    tipRom: "Ilhareo hoesa-e ganeun geos-imnida.",
    tipEn: "Going to the company to work.", matchTitle: "Go to Work" },
  { kr: "급여명세서", rom: "geupyeo-myeongseoseo", en: "Payslip",
    tip: "월급이 얼마이고 어떻게 계산됐는지 적혀 있는 문서입니다.",
    tipRom: "Wolgeub-i eolma-igo eotteoke gyesandwaess-neunji jeokhyeo issneun munseo-imnida.",
    tipEn: "A document showing how much your salary is and how it was calculated.", matchTitle: "Payslip" },
  { kr: "시급", rom: "sigeup", en: "Hourly Wage",
    tip: "한 시간 일할 때 받는 돈입니다.",
    tipRom: "Han sigan ilhal ttae bad-neun don-imnida.",
    tipEn: "The money you earn for one hour of work.", matchTitle: "Hourly Wage" },
  { kr: "월급", rom: "wolgeup", en: "Monthly Salary",
    tip: "한 달 동안 일하고 받는 돈입니다.",
    tipRom: "Han dal dong-an ilhago bad-neun don-imnida.",
    tipEn: "The money you earn for a month of work.", matchTitle: "Monthly Salary" },
  { kr: "최저임금", rom: "choejeoimgeum", en: "Minimum Wage",
    tip: "법으로 정해진, 반드시 지급해야 하는 가장 적은 임금입니다.",
    tipRom: "Beob-euro jeonghaejin, bandeusi jigeuphaeya haneun gajang jeog-eun imgeum-imnida.",
    tipEn: "The lowest wage set by law that must be paid.", matchTitle: "Minimum Wage" },
  { kr: "퇴직금", rom: "toejikgeum", en: "Severance Pay",
    tip: "회사를 그만둘 때 받는 돈입니다.",
    tipRom: "Hoesa-reul geumandul ttae bad-neun don-imnida.",
    tipEn: "The money you receive when you leave a company.", matchTitle: "Severance Pay" },
  { kr: "사직", rom: "sajik", en: "Resignation",
    tip: "스스로 회사를 그만두는 것입니다.",
    tipRom: "Seuseuro hoesa-reul geumanduneun geos-imnida.",
    tipEn: "Quitting a job by your own choice.", matchTitle: "Resignation" },

  // ---- 음식 ----
  { kr: "비빔밥", rom: "bibimbap", en: "Bibimbap",
    tip: "밥에 여러 나물과 고추장을 넣고 비벼 먹는 한국 음식입니다.",
    tipRom: "Bab-e yeoreo namul-gwa gochujang-eul neoko bibyeo meokneun hanguk eumsik-imnida.",
    tipEn: "A Korean dish made by mixing rice with vegetables and chili paste.", matchTitle: "Bibimbap" },
  { kr: "불고기", rom: "bulgogi", en: "Bulgogi",
    tip: "얇게 썬 고기를 양념에 재워서 구운 한국 음식입니다.",
    tipRom: "Yalgge sseon gogi-reul yangnyeom-e jaewoseo guun hanguk eumsik-imnida.",
    tipEn: "A Korean dish of thinly sliced meat marinated and grilled.", matchTitle: "Bulgogi" },
  { kr: "김치", rom: "gimchi", en: "Kimchi",
    tip: "배추나 무를 양념에 절여서 만든 한국의 대표 반찬입니다.",
    tipRom: "Baechu-na mu-reul yangnyeom-e jeolyeoseo mandeun hanguk-ui daepyo banchan-imnida.",
    tipEn: "Korea's representative side dish made by fermenting cabbage or radish in seasoning.", matchTitle: "Kimchi" },
  { kr: "삼겹살", rom: "samgyeopsal", en: "Samgyeopsal",
    tip: "돼지고기의 한 부위로, 구워 먹는 인기 있는 한국 음식입니다.",
    tipRom: "Dwaejigogi-ui han buwi-ro, guwo meokneun ingi issneun hanguk eumsik-imnida.",
    tipEn: "A popular Korean food made from a pork cut that is grilled.", matchTitle: "Samgyeopsal" },
  { kr: "떡볶이", rom: "tteokbokki", en: "Tteokbokki",
    tip: "떡을 매운 양념에 볶아 만든 한국의 분식입니다.",
    tipRom: "Tteog-eul maeun yangnyeom-e bokk-a mandeun hanguk-ui bunsig-imnida.",
    tipEn: "A Korean street food made by stir-frying rice cakes in spicy sauce.", matchTitle: "Tteokbokki" },
  { kr: "라면", rom: "ramyeon", en: "Ramen",
    tip: "뜨거운 물에 끓여 먹는 인스턴트 국수입니다.",
    tipRom: "Tteugeoun mul-e kkeulyeo meokneun inseuteonteu guksu-imnida.",
    tipEn: "Instant noodles cooked in hot water.", matchTitle: "Ramen" },
  { kr: "김밥", rom: "gimbap", en: "Gimbap",
    tip: "밥과 여러 재료를 김으로 말아서 만든 한국 음식입니다.",
    tipRom: "Bab-gwa yeoreo jaeryo-reul gim-euro mar-aseo mandeun hanguk eumsik-imnida.",
    tipEn: "A Korean food made by rolling rice and various ingredients in dried seaweed.", matchTitle: "Gimbap" },

  // ---- 일상 어휘 ----
  { kr: "고양이", rom: "goyangi", en: "Cat",
    tip: "야옹 하고 우는, 사람들이 많이 키우는 동물입니다.",
    tipRom: "Yaong hago uneun, saramdeul-i mani kiuneun dongmul-imnida.",
    tipEn: "An animal that meows and is commonly kept as a pet.", matchTitle: "Cat" },
  { kr: "강아지", rom: "gangaji", en: "Dog",
    tip: "멍멍 하고 짖는, 사람들이 많이 키우는 동물입니다.",
    tipRom: "Meongmeong hago jitneun, saramdeul-i mani kiuneun dongmul-imnida.",
    tipEn: "An animal that barks and is commonly kept as a pet.", matchTitle: "Dog" },
  { kr: "버스", rom: "beoseu", en: "Bus",
    tip: "여러 사람이 함께 타는 큰 대중교통 수단입니다.",
    tipRom: "Yeoreo saram-i hamkke taneun keun daejunggyotong sudan-imnida.",
    tipEn: "A large public transportation vehicle many people ride together.", matchTitle: "Bus" },
  { kr: "택시", rom: "taeksi", en: "Taxi",
    tip: "돈을 내고 원하는 곳까지 갈 수 있는 자동차입니다.",
    tipRom: "Don-eul naego wonhaneun gos-kkaji gal su issneun jadongcha-imnida.",
    tipEn: "A car you can pay to ride to your destination.", matchTitle: "Taxi" },
  { kr: "기차", rom: "gicha", en: "Train",
    tip: "철로 위를 달리는 대중교통 수단입니다.",
    tipRom: "Cheollo wi-reul dallineun daejunggyotong sudan-imnida.",
    tipEn: "A public transportation vehicle that runs on rails.", matchTitle: "Train" },

  // ---- 서류/신분 ----
  { kr: "외국인등록증", rom: "oegugindeungrokjeung", en: "Alien Registration Card",
    tip: "한국에 사는 외국인이 신분을 증명하기 위해 갖고 있어야 하는 카드입니다.",
    tipRom: "Hanguk-e saneun oegugin-i sinbun-eul jeungmyeonghagi wihae gajgo iss-eoya haneun kadeu-imnida.",
    tipEn: "A card foreign residents in Korea must have to prove their identity.", matchTitle: "Alien Registration Card" },
  { kr: "여권", rom: "yeogwon", en: "Passport",
    tip: "다른 나라를 여행하거나 입국할 때 필요한 신분증명서입니다.",
    tipRom: "Dareun nara-reul yeohaenghageona ipgukhal ttae pilyohan sinbunjeungmyeongseo-imnida.",
    tipEn: "An identity document needed to travel to or enter another country.", matchTitle: "Passport" },
  { kr: "비자", rom: "bija", en: "Visa",
    tip: "외국인이 한국에 들어와서 머무를 수 있도록 허가하는 증명입니다.",
    tipRom: "Oegugin-i hanguk-e deur-eowaseo meomureul su issdorok heogahaneun jeungmyeong-imnida.",
    tipEn: "Permission that allows a foreigner to enter and stay in Korea.", matchTitle: "Visa" },

  // ---- 일상 어휘 추가 배치 (40개) ----
  { kr: "학원", rom: "hagwon", en: "Academy",
    tip: "한국어나 다른 과목을 배우러 다니는 사립 교육 기관입니다.",
    tipRom: "Hangugeo-na dareun gwamog-eul baeuleo daninneun sarip gyoyug gigwan-imnida.",
    tipEn: "A private institute where people go to learn subjects like Korean.", matchTitle: "Academy" },
  { kr: "비행기", rom: "bihaenggi", en: "Airplane",
    tip: "하늘을 날아서 먼 곳으로 이동하는 큰 교통수단입니다.",
    tipRom: "Haneul-eul nal-aseo meon gos-euro idonghaneun keun gyotongsudan-imnida.",
    tipEn: "A large vehicle that flies through the sky to travel far distances.", matchTitle: "Airplane" },
  { kr: "공항", rom: "gonghang", en: "Airport",
    tip: "비행기를 타고 내리는 곳입니다.",
    tipRom: "Bihaenggi-reul tago naerineun gos-imnida.",
    tipEn: "The place where airplanes take off and land.", matchTitle: "Airport" },
  { kr: "아파트", rom: "apateu", en: "Apartment",
    tip: "여러 층으로 이루어진, 많은 사람이 함께 사는 건물입니다.",
    tipRom: "Yeoreo cheung-euro irueojin, manh-eun saram-i hamkke saneun geonmul-imnida.",
    tipEn: "A multi-story building where many people live.", matchTitle: "Apartment" },
  { kr: "사과", rom: "sagwa", en: "Apple",
    tip: "빨갛거나 초록색인, 달콤한 과일입니다.",
    tipRom: "Ppalgakeona chorogsaeg-in, dalkomhan gwail-imnida.",
    tipEn: "A sweet fruit that is red or green.", matchTitle: "Apple" },
  { kr: "가을", rom: "gaeul", en: "Autumn",
    tip: "여름과 겨울 사이, 나뭇잎이 물드는 계절입니다.",
    tipRom: "Yeoreum-gwa gyeoul sai, namunnip-i muldeuneun gyejeol-imnida.",
    tipEn: "The season between summer and winter when leaves change color.", matchTitle: "Autumn" },
  { kr: "아기", rom: "agi", en: "Baby",
    tip: "태어난 지 얼마 안 된 어린 사람입니다.",
    tipRom: "Taeeonan ji eolma an doen eorin saram-imnida.",
    tipEn: "A very young child who was recently born.", matchTitle: "Baby" },
  { kr: "침대", rom: "chimdae", en: "Bed",
    tip: "잠을 자기 위해 눕는 가구입니다.",
    tipRom: "Jam-eul jagi wihae nupneun gagu-imnida.",
    tipEn: "Furniture you lie down on to sleep.", matchTitle: "Bed" },
  { kr: "새", rom: "sae", en: "Bird",
    tip: "날개로 하늘을 나는 동물입니다.",
    tipRom: "Nalgae-ro haneul-eul naneun dongmul-imnida.",
    tipEn: "An animal that flies through the sky with wings.", matchTitle: "Bird" },
  { kr: "책", rom: "chaek", en: "Book",
    tip: "글이 인쇄되어 있는, 읽는 물건입니다.",
    tipRom: "Geul-i inswaedoeeo issneun, ilgneun mulgeon-imnida.",
    tipEn: "An item with printed text that you read.", matchTitle: "Book" },
  { kr: "빵", rom: "ppang", en: "Bread",
    tip: "밀가루를 구워서 만든 음식입니다.",
    tipRom: "Milgaru-reul guwoseo mandeun eumsik-imnida.",
    tipEn: "A food made by baking flour.", matchTitle: "Bread" },
  { kr: "건물", rom: "geonmul", en: "Buildings",
    tip: "사람이 살거나 일하는 큰 구조물입니다.",
    tipRom: "Saram-i salgeona ilhaneun keun gujomul-imnida.",
    tipEn: "A large structure where people live or work.", matchTitle: "Buildings" },
  { kr: "현금", rom: "hyeongeum", en: "Cash",
    tip: "카드가 아닌, 직접 주고받는 돈입니다.",
    tipRom: "Kadeu-ga anin, jikjeop jugobadneun don-imnida.",
    tipEn: "Physical money, not paid by card.", matchTitle: "Cash" },
  { kr: "의자", rom: "uija", en: "Chair",
    tip: "앉을 때 쓰는 가구입니다.",
    tipRom: "Anj-eul ttae sseuneun gagu-imnida.",
    tipEn: "Furniture used for sitting.", matchTitle: "Chair" },
  { kr: "도시", rom: "dosi", en: "City",
    tip: "사람과 건물이 많은 큰 지역입니다.",
    tipRom: "Saram-gwa geonmul-i manh-eun keun jiyeog-imnida.",
    tipEn: "A large area with many people and buildings.", matchTitle: "City" },
  { kr: "옷", rom: "ot", en: "Clothes",
    tip: "몸에 입는 물건입니다.",
    tipRom: "Mom-e ipneun mulgeon-imnida.",
    tipEn: "Items worn on the body.", matchTitle: "Clothes" },
  { kr: "통근", rom: "tonggeun", en: "Commute",
    tip: "집에서 회사까지 왔다 갔다 하는 것입니다.",
    tipRom: "Jib-eseo hoesa-kkaji wass-da gass-da haneun geos-imnida.",
    tipEn: "Traveling back and forth between home and work.", matchTitle: "Commute" },
  { kr: "회사", rom: "hoesa", en: "Company",
    tip: "사람들이 일하는 조직입니다.",
    tipRom: "Saramdeul-i ilhaneun jojig-imnida.",
    tipEn: "An organization where people work.", matchTitle: "Company" },
  { kr: "요리", rom: "yori", en: "Cooking",
    tip: "음식을 만드는 활동입니다.",
    tipRom: "Eumsig-eul mandeuneun hwaldong-imnida.",
    tipEn: "The activity of preparing food.", matchTitle: "Cooking" },
  { kr: "아빠", rom: "appa", en: "Dad",
    tip: "남자 부모를 부르는 말입니다.",
    tipRom: "Namja bumo-reul bureuneun mal-imnida.",
    tipEn: "A word used to call one's father.", matchTitle: "Dad" },
  { kr: "책상", rom: "chaeksang", en: "Desk",
    tip: "공부하거나 일할 때 쓰는 가구입니다.",
    tipRom: "Gongbuhageona ilhal ttae sseuneun gagu-imnida.",
    tipEn: "Furniture used for studying or working.", matchTitle: "Desk" },
  { kr: "문", rom: "mun", en: "Door",
    tip: "방이나 건물에 드나들 때 여는 것입니다.",
    tipRom: "Bang-ina geonmul-e deunadeul ttae yeoneun geos-imnida.",
    tipEn: "What you open to enter or exit a room or building.", matchTitle: "Door" },
  { kr: "감정", rom: "gamjeong", en: "Emotions",
    tip: "기쁨, 슬픔처럼 마음속에서 느끼는 것입니다.",
    tipRom: "Gippeum, seulpeumcheoreom maeumsog-eseo neukkineun geos-imnida.",
    tipEn: "Feelings you experience inside, like joy or sadness.", matchTitle: "Emotions" },
  { kr: "저녁", rom: "jeonyeok", en: "Evening",
    tip: "오후 늦게부터 밤이 되기 전까지의 시간입니다.",
    tipRom: "Ohu neutgebuteo bam-i doegi jeon-kkaji-ui sigan-imnida.",
    tipEn: "The time from late afternoon until night.", matchTitle: "Evening" },
  { kr: "시험", rom: "siheom", en: "Exam",
    tip: "배운 것을 확인하기 위한 테스트입니다.",
    tipRom: "Baeun geos-eul hwaginhagi wihan teseuteu-imnida.",
    tipEn: "A test to check what you have learned.", matchTitle: "Exam" },
  { kr: "가족", rom: "gajok", en: "Family",
    tip: "부모, 형제처럼 함께 사는 사람들입니다.",
    tipRom: "Bumo, hyeongjecheoreom hamkke saneun saramdeul-imnida.",
    tipEn: "People who live together, like parents and siblings.", matchTitle: "Family" },
  { kr: "물고기", rom: "mulgogi", en: "Fish",
    tip: "물속에서 사는 동물입니다.",
    tipRom: "Mulsog-eseo saneun dongmul-imnida.",
    tipEn: "An animal that lives in water.", matchTitle: "Fish" },
  { kr: "꽃", rom: "kkot", en: "Flower",
    tip: "예쁜 색과 향기를 가진 식물의 일부입니다.",
    tipRom: "Yeppeun saeg-gwa hyanggi-reul gajin sigmul-ui ilbu-imnida.",
    tipEn: "A colorful, fragrant part of a plant.", matchTitle: "Flower" },
  { kr: "친구", rom: "chingu", en: "Friend",
    tip: "가깝게 지내는 사람입니다.",
    tipRom: "Gakkabge jinaeneun saram-imnida.",
    tipEn: "A person you are close with.", matchTitle: "Friend" },
  { kr: "과일", rom: "gwail", en: "Fruit",
    tip: "나무나 식물에서 나는 달콤한 먹거리입니다.",
    tipRom: "Namu-na sigmul-eseo naneun dalkomhan meokgeori-imnida.",
    tipEn: "A sweet food that grows on trees or plants.", matchTitle: "Fruit" },
  { kr: "선물", rom: "seonmul", en: "Gift",
    tip: "다른 사람에게 주는 물건입니다.",
    tipRom: "Dareun saram-ege juneun mulgeon-imnida.",
    tipEn: "An item given to another person.", matchTitle: "Gift" },
  { kr: "행복", rom: "haengbok", en: "Happiness",
    tip: "기분이 아주 좋은 상태입니다.",
    tipRom: "Gibun-i aju joh-eun sangtae-imnida.",
    tipEn: "A state of feeling very good.", matchTitle: "Happiness" },
  { kr: "건강", rom: "geongang", en: "Health",
    tip: "몸이 아프지 않고 튼튼한 상태입니다.",
    tipRom: "Mom-i apeuji anko teunteunhan sangtae-imnida.",
    tipEn: "The state of being physically well and strong.", matchTitle: "Health" },
  { kr: "취미", rom: "chwimi", en: "Hobbies",
    tip: "즐거움을 위해 하는 활동입니다.",
    tipRom: "Jeulgeoum-eul wihae haneun hwaldong-imnida.",
    tipEn: "Activities done for enjoyment.", matchTitle: "Hobbies" },
  { kr: "숙제", rom: "sukje", en: "Homework",
    tip: "집에서 하는 학교 과제입니다.",
    tipRom: "Jib-eseo haneun hakgyo gwaje-imnida.",
    tipEn: "School assignments done at home.", matchTitle: "Homework" },
  { kr: "직업", rom: "jigeop", en: "Jobs",
    tip: "돈을 벌기 위해 하는 일입니다.",
    tipRom: "Don-eul beolgi wihae haneun il-imnida.",
    tipEn: "Work done to earn money.", matchTitle: "Jobs" },
  { kr: "부엌", rom: "bueok", en: "Kitchen",
    tip: "요리를 하는 방입니다.",
    tipRom: "Yori-reul haneun bang-imnida.",
    tipEn: "The room where cooking is done.", matchTitle: "Kitchen" },
  { kr: "사자", rom: "saja", en: "Lion",
    tip: "갈기가 있는 크고 힘센 동물입니다.",
    tipRom: "Galgi-ga issneun keugo himsen dongmul-imnida.",
    tipEn: "A large, powerful animal with a mane.", matchTitle: "Lion" },
  { kr: "사랑", rom: "sarang", en: "Love",
    tip: "누군가를 아주 소중하게 여기는 마음입니다.",
    tipRom: "Nugungaleul aju sojunghage yeogineun maeum-imnida.",
    tipEn: "A feeling of deeply caring for someone.", matchTitle: "Love" },
  { kr: "시장", rom: "sijang", en: "Market",
    tip: "물건을 사고파는 곳입니다.",
    tipRom: "Mulgeon-eul sagopaneun gos-imnida.",
    tipEn: "A place where things are bought and sold.", matchTitle: "Market" },
  { kr: "교통", rom: "gyotong", en: "Transport",
    tip: "사람이나 물건을 옮기는 수단입니다.",
    tipRom: "Saram-ina mulgeon-eul olmgineun sudan-imnida.",
    tipEn: "The means used to move people or goods.", matchTitle: "Transport" },

  // ---- 근로/산업안전 용어 추가 배치 (40개) ----
  { kr: "특근", rom: "teukgeun", en: "Special Shift Work",
    tip: "정해진 근무일이 아닌 날에 특별히 일하는 것입니다.",
    tipRom: "Jeonghaejin geunmuil-i anin nal-e teukbyeolhi ilhaneun geos-imnida.",
    tipEn: "Working on a day that is not a regular scheduled workday.", matchTitle: "Special Shift Work" },
  { kr: "잔업", rom: "janeop", en: "Remaining Work",
    tip: "정해진 근무 시간 안에 끝내지 못한, 남은 일입니다.",
    tipRom: "Jeonghaejin geunmu sigan an-e kkeutnaeji moshan, nam-eun il-imnida.",
    tipEn: "Work left unfinished within regular working hours.", matchTitle: "Remaining Work" },
  { kr: "반장", rom: "banjang", en: "Foreman",
    tip: "작업 현장에서 근로자들을 이끄는 사람입니다.",
    tipRom: "Jageop hyeonjang-eseo geunrojadeul-eul ikkeuneun saram-imnida.",
    tipEn: "The person who leads workers at a job site.", matchTitle: "Foreman" },
  { kr: "사업주", rom: "saeopju", en: "Employer",
    tip: "회사를 소유하고 근로자를 고용하는 사람입니다.",
    tipRom: "Hoesa-reul soyuhago geunroja-reul goyonghaneun saram-imnida.",
    tipEn: "The person who owns the company and employs workers.", matchTitle: "Employer" },
  { kr: "근무지", rom: "geunmuji", en: "Workplace",
    tip: "일을 하는 장소입니다.",
    tipRom: "Il-eul haneun jangso-imnida.",
    tipEn: "The place where work is done.", matchTitle: "Workplace" },
  { kr: "근로 계약서", rom: "geunro-gyeyakseo", en: "Labor Contract",
    tip: "회사와 근로 조건을 정해서 쓰는 문서입니다.",
    tipRom: "Hoesa-wa geunro jogeon-eul jeonghaeseo sseuneun munseo-imnida.",
    tipEn: "A document that sets the terms of employment between worker and company.", matchTitle: "Labor Contract" },
  { kr: "수당", rom: "sudang", en: "Allowance",
    tip: "월급 외에 추가로 받는 돈입니다.",
    tipRom: "Wolgeup oe-e chuga-ro badneun don-imnida.",
    tipEn: "Extra money received in addition to the base salary.", matchTitle: "Allowance" },
  { kr: "근로자", rom: "geunroja", en: "Worker",
    tip: "회사에서 일하는 사람입니다.",
    tipRom: "Hoesa-eseo ilhaneun saram-imnida.",
    tipEn: "A person who works at a company.", matchTitle: "Worker" },
  { kr: "팀장", rom: "timjang", en: "Team Leader",
    tip: "팀을 이끄는 사람입니다.",
    tipRom: "Tim-eul ikkeuneun saram-imnida.",
    tipEn: "The person who leads a team.", matchTitle: "Team Leader" },
  { kr: "사장", rom: "sajang", en: "President",
    tip: "회사를 대표하는 가장 높은 사람입니다.",
    tipRom: "Hoesa-reul daepyohaneun gajang nop-eun saram-imnida.",
    tipEn: "The highest-ranking person representing a company.", matchTitle: "President" },
  { kr: "동료", rom: "dongryo", en: "Co-worker",
    tip: "같은 회사에서 함께 일하는 사람입니다.",
    tipRom: "Gat-eun hoesa-eseo hamkke ilhaneun saram-imnida.",
    tipEn: "A person you work together with at the same company.", matchTitle: "Co-worker" },
  { kr: "교대 근무", rom: "gyodae-geunmu", en: "Shift Work",
    tip: "정해진 시간마다 사람이 바뀌면서 일하는 방식입니다.",
    tipRom: "Jeonghaejin siganmada saram-i bakkwimyeonseo ilhaneun bangsig-imnida.",
    tipEn: "A work system where workers alternate at set times.", matchTitle: "Shift Work" },
  { kr: "기본급", rom: "gibongeup", en: "Base Pay",
    tip: "수당을 더하기 전, 기본으로 받는 급여입니다.",
    tipRom: "Sudang-eul deohagi jeon, gibon-euro badneun geubyeo-imnida.",
    tipEn: "The basic salary before any allowances are added.", matchTitle: "Base Pay" },
  { kr: "상여금", rom: "sangyeogeum", en: "Bonus",
    tip: "정해진 월급 외에 추가로 주는 돈입니다.",
    tipRom: "Jeonghaejin wolgeup oe-e chuga-ro juneun don-imnida.",
    tipEn: "Extra money given in addition to the regular salary.", matchTitle: "Bonus" },
  { kr: "공제", rom: "gongje", en: "Deduction",
    tip: "월급에서 빼는 금액입니다.",
    tipRom: "Wolgeup-eseo ppaeneun geumaeg-imnida.",
    tipEn: "An amount subtracted from a salary.", matchTitle: "Deduction" },
  { kr: "세금", rom: "segeum", en: "Tax",
    tip: "국가에 내야 하는 돈입니다.",
    tipRom: "Gukga-e naeya haneun don-imnida.",
    tipEn: "Money that must be paid to the government.", matchTitle: "Tax" },
  { kr: "실수령액", rom: "silsuryeongaek", en: "Net Pay",
    tip: "세금과 공제를 뺀 후 실제로 받는 돈입니다.",
    tipRom: "Segeum-gwa gongje-reul ppaen hu siljero badneun don-imnida.",
    tipEn: "The actual amount received after tax and deductions.", matchTitle: "Net Pay" },
  { kr: "해고", rom: "haego", en: "Dismissal / Firing",
    tip: "회사가 근로자를 그만두게 하는 것입니다.",
    tipRom: "Hoesa-ga geunroja-reul geumanduge haneun geos-imnida.",
    tipEn: "When a company forces a worker to stop working.", matchTitle: "Dismissal / Firing" },
  { kr: "재계약", rom: "jaegyeyak", en: "Re-contract / Renewal",
    tip: "계약 기간이 끝난 후 다시 계약하는 것입니다.",
    tipRom: "Gyeyak gigan-i kkeutnan hu dasi gyeyakhaneun geos-imnida.",
    tipEn: "Signing a new contract after the previous one ends.", matchTitle: "Re-contract / Renewal" },
  { kr: "수습 기간", rom: "suseup-gigan", en: "Probationary Period",
    tip: "정식 채용 전에 능력을 확인하는 기간입니다.",
    tipRom: "Jeongsig chaeyong jeon-e neungryeog-eul hwaginhaneun gigan-imnida.",
    tipEn: "A trial period to check ability before official hiring.", matchTitle: "Probationary Period" },
  { kr: "취업 규칙", rom: "chwieop-gyuchik", en: "Employment Rules",
    tip: "회사에서 정한 근무 규정입니다.",
    tipRom: "Hoesa-eseo jeonghan geunmu gyujeong-imnida.",
    tipEn: "Work rules set by the company.", matchTitle: "Employment Rules" },
  { kr: "근로 시간", rom: "geunro-sigan", en: "Working Hours",
    tip: "일을 하기로 정해진 시간입니다.",
    tipRom: "Il-eul hagiro jeonghaejin sigan-imnida.",
    tipEn: "The scheduled hours for working.", matchTitle: "Working Hours" },
  { kr: "연차 휴가", rom: "yeoncha-hyuga", en: "Annual Leave",
    tip: "1년에 며칠씩 주어지는 유급 휴가입니다.",
    tipRom: "Il-nyeon-e myeochilssig jueojineun yugeup hyuga-imnida.",
    tipEn: "Paid days off given each year.", matchTitle: "Annual Leave" },
  { kr: "체류 기간", rom: "cheryu-gigan", en: "Period of Stay",
    tip: "외국인이 한국에 머무를 수 있는 허가된 기간입니다.",
    tipRom: "Oegugin-i hanguk-e meomureul su issneun heogadoen gigan-imnida.",
    tipEn: "The authorized length of time a foreigner may stay in Korea.", matchTitle: "Period of Stay" },
  { kr: "체류 연장", rom: "cheryu-yeonjang", en: "Extension of Stay",
    tip: "체류 기간을 늘리는 것입니다.",
    tipRom: "Cheryu gigan-eul neullineun geos-imnida.",
    tipEn: "Extending the authorized period of stay.", matchTitle: "Extension of Stay" },
  { kr: "고용노동부", rom: "goyong-nodongbu", en: "Ministry of Employment and Labor",
    tip: "근로자의 권리를 관리하는 한국 정부 부처입니다.",
    tipRom: "Geunroja-ui gwolli-reul gwanrihaneun hanguk jeongbu bucheo-imnida.",
    tipEn: "The Korean government ministry that manages workers' rights.", matchTitle: "Ministry of Employment and Labor" },
  { kr: "산업재해", rom: "saneop-jaehae", en: "Industrial Accident",
    tip: "일을 하다가 다치거나 발생하는 사고입니다.",
    tipRom: "Il-eul hadaga dachigeona balsaenghaneun sago-imnida.",
    tipEn: "An accident that occurs while working.", matchTitle: "Industrial Accident" },
  { kr: "산재보험", rom: "sanjae-boheom", en: "Industrial Accident Insurance",
    tip: "산업재해를 당했을 때 보상해 주는 보험입니다.",
    tipRom: "Saneop jaehae-reul danghaess-eul ttae bosanghae juneun boheom-imnida.",
    tipEn: "Insurance that compensates workers for industrial accidents.", matchTitle: "Industrial Accident Insurance" },
  { kr: "국민건강보험", rom: "gukmin-geongang-boheom", en: "National Health Insurance",
    tip: "병원비를 지원해 주는 한국의 건강보험 제도입니다.",
    tipRom: "Byeong-wonbi-reul jiwonhae juneun hanguk-ui geongang boheom jedo-imnida.",
    tipEn: "Korea's health insurance system that helps cover medical costs.", matchTitle: "National Health Insurance" },
  { kr: "신청서", rom: "sincheongseo", en: "Application Form",
    tip: "무언가를 신청할 때 작성하는 서류입니다.",
    tipRom: "Mueonga-reul sincheonghal ttae jakseonghaneun seoryu-imnida.",
    tipEn: "A document filled out to apply for something.", matchTitle: "Application Form" },
  { kr: "도장", rom: "dojang", en: "Stamp / Seal",
    tip: "이름을 새겨서 서류에 찍는 도구입니다.",
    tipRom: "Ireum-eul saegyeoseo seoryu-e jjigneun dogu-imnida.",
    tipEn: "A tool engraved with a name, stamped on documents.", matchTitle: "Stamp / Seal" },
  { kr: "서명", rom: "seomyeong", en: "Signature",
    tip: "본인임을 확인하기 위해 손으로 쓰는 이름입니다.",
    tipRom: "Boninim-eul hwaginhagi wihae son-euro sseuneun ireum-imnida.",
    tipEn: "A handwritten name used to confirm identity.", matchTitle: "Signature" },
  { kr: "신분증", rom: "sinbunjeung", en: "ID Card",
    tip: "자신의 신분을 증명하는 카드입니다.",
    tipRom: "Jasin-ui sinbun-eul jeungmyeonghaneun kadeu-imnida.",
    tipEn: "A card that proves one's identity.", matchTitle: "ID Card" },
  { kr: "환율", rom: "hwanyul", en: "Exchange Rate",
    tip: "한 나라 돈을 다른 나라 돈으로 바꾸는 비율입니다.",
    tipRom: "Han nara don-eul dareun nara don-euro bakkuneun biyul-imnida.",
    tipEn: "The rate for converting one country's currency to another's.", matchTitle: "Exchange Rate" },
  { kr: "송금", rom: "songgeum", en: "Money Transfer",
    tip: "돈을 다른 계좌로 보내는 것입니다.",
    tipRom: "Don-eul dareun gyejwa-ro bonaeneun geos-imnida.",
    tipEn: "Sending money to another account.", matchTitle: "Money Transfer" },
  { kr: "통장", rom: "tongjang", en: "Bank Account",
    tip: "은행 거래 내역이 기록되는 것입니다.",
    tipRom: "Eunhaeng georae naeyeog-i girokdoeneun geos-imnida.",
    tipEn: "A record book or account for bank transactions.", matchTitle: "Bank Account" },
  { kr: "서류", rom: "seoryu", en: "Documents",
    tip: "글로 적힌 공식적인 종이입니다.",
    tipRom: "Geullo jeoghin gongsigjeog-in jong-i-imnida.",
    tipEn: "Official written papers.", matchTitle: "Documents" },
  { kr: "기숙사", rom: "gisuksa", en: "Dormitory",
    tip: "회사나 학교에서 제공하는 숙소입니다.",
    tipRom: "Hoesa-na hakgyo-eseo jegonghaneun sugso-imnida.",
    tipEn: "Housing provided by a company or school.", matchTitle: "Dormitory" },
  { kr: "작업", rom: "jageop", en: "Work",
    tip: "몸이나 도구를 써서 하는 일입니다.",
    tipRom: "Mom-ina dogu-reul sseoseo haneun il-imnida.",
    tipEn: "Tasks done using the body or tools.", matchTitle: "Work" },
  { kr: "공정", rom: "gongjeong", en: "Process",
    tip: "제품을 만드는 순서나 단계입니다.",
    tipRom: "Jepum-eul mandeuneun sunseo-na dangye-imnida.",
    tipEn: "The steps or stages of making a product.", matchTitle: "Process" }
];

/* =========================================================
   날짜 시드 기반 의사난수 (같은 날짜 → 항상 같은 결과)
   ========================================================= */
function getTodayDateStr(){
  return new Date().toISOString().slice(0, 10); // "2026-09-14"
}

function seedFromString(str){
  let hash = 0;
  for (let i = 0; i < str.length; i++){
    hash = (hash * 31 + str.charCodeAt(i)) >>> 0;
  }
  return hash;
}

// mulberry32: 가볍고 충분히 균등한 시드 기반 PRNG
function mulberry32(seed){
  return function(){
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function seededShuffle(arr, rand){
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--){
    const j = Math.floor(rand() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/* =========================================================
   오늘의 모의고사 큐 생성 (문제 하나씩 순서대로 풀도록)
   -----------------------------------------------------------
   count: 오늘 몇 문제를 낼지 (기본 10개)
   sourceUrl은 script.js의 window.quizDB에서 matchTitle로 자동 매칭.

   반환되는 각 문제 객체:
   {
     question, questionRom, questionEn   → 설명(tip) 한글/로마자/영어
     options: [{kr, rom, en}, ...]        → 선택지 4개, 각각 한글/로마자/영어
     answer                               → 정답 인덱스
     sourceUrl, sourceTitle               → 개별 페이지 연결용
   }
   ========================================================= */
function buildDailyQuizQueue(count){
  count = count || 10;
  const dateStr = getTodayDateStr();
  const rand = mulberry32(seedFromString(dateStr));
  const bank = window.dailyQuizBank || [];
  if (bank.length === 0) return [];

  const picked = seededShuffle(bank, rand).slice(0, Math.min(count, bank.length));

  return picked.map(item => {
    const distractorPool = bank.filter(b => b.en !== item.en);
    const distractorItems = seededShuffle(distractorPool, rand).slice(0, 3);
    const optionItems = seededShuffle([item, ...distractorItems], rand);
    const options = optionItems.map(o => ({ kr: o.kr, rom: o.rom, en: o.en }));
    const answerIndex = optionItems.findIndex(o => o.en === item.en);
    const sourceEntry = (window.quizDB || []).find(q => q.title === item.matchTitle);

    return {
      question: item.tip,
      questionRom: item.tipRom,
      questionEn: item.tipEn,
      options: options,
      answer: answerIndex,
      sourceUrl: sourceEntry ? sourceEntry.url : null,
      sourceTitle: item.matchTitle
    };
  });
}

window.buildDailyQuizQueue = buildDailyQuizQueue;
window.getTodayDateStr = getTodayDateStr;
