/* =========================================================
   EPS-TOPIK 정식 모의고사 데이터
   -----------------------------------------------------------
   실제 EPS-TOPIK 형식 기준(2026년):
   - 총 40문항, 50분, 쉬는 시간 없음
   - 듣기 20문항(25분) + 읽기 20문항(25분)
   - 전부 4지선다, 각 2.5점 (합계 100점)
   - 합격선은 업종마다 다름 (제조업 60점 / 그 외 45점 / 어업 특례 30점)
     → 이 앱은 참고용 연습이며, 실제 시험 채점 기준은 HRD Korea 공식 안내를 따라야 함

   세트 추가 방법: 아래 mockExamSets 배열에 같은 형식으로 객체를 추가하면 됨.
   free: true 인 세트만 무료로 열림. 나머지는 유료(paid) 플랜만 접근 가능.

   ✅ sourceUrl/sourceTitle:
   각 문항이 quizDB(script.js) 600개 레슨 페이지 중 어떤 페이지와 "주제"로 연결되는지
   나타내는 필드. 문제 문장과 레슨 페이지 문장이 토씨 하나까지 일치할 필요는 없음 —
   같은 주제를 더 공부하고 싶을 때 찾아갈 곳을 안내하는 용도. 시험 응시 중에는
   화면에 노출되지 않고, 결과 화면(정답/오답 40문항 리뷰)에서만
   "📚 Study [제목] →" 버튼을 만드는 데 쓰인다.
   나중에 quizDB에 새 페이지가 추가되면, 그 페이지를 주제로 새 문항/새 세트를
   똑같은 방식으로 계속 만들어나갈 수 있음.

   ✅ 2회차 수정 사항 (1회차 대비):
   - R05: 오답 중 하나("버스를 내려요")가 사실 자연스러운 표현이라
     복수 정답처럼 읽히던 문제 → 명확하게 하나만 맞는 조사 문제로 교체
   - sourceUrl 중복 제거: jakeop.html(R02/R09), geunmuji.html(R05/R19),
     apayo1.html(L08/R07)이 겹쳐 쓰이던 것을 40문항 전부 서로 다른 페이지로 재매핑
   ========================================================= */

window.mockExamSets = window.mockExamSets || [
  {
    id: "set_01",
    title: "EPS-TOPIK Mock Test #1",
    free: true,
    listening: [
      { id: "L01", audioText: "안녕하세요. 처음 뵙겠습니다.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 비싸요.", "네, 반갑습니다.", "네, 늦었어요.", "네, 맛있어요."], answer: 1,
        sourceUrl: "annyeonghaseyo1.html", sourceTitle: "Hello" },
      { id: "L02", audioText: "지금 몇 시예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["9시예요.", "3만원이에요.", "월요일이에요.", "회사예요."], answer: 0,
        sourceUrl: "jigeummyeotsiyeyo1.html", sourceTitle: "What Time Is It?" },
      { id: "L03", audioText: "오늘 날씨가 어때요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["일요일이에요.", "추워요.", "먹어요.", "친구예요."], answer: 1,
        sourceUrl: "weather.html", sourceTitle: "Weather" },
      { id: "L04", audioText: "이거 얼마예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["5층이에요.", "5시예요.", "5천원이에요.", "5개예요."], answer: 2,
        sourceUrl: "eolmayeyo1.html", sourceTitle: "How Much Is It" },
      { id: "L05", audioText: "화장실이 어디에 있어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["많이 있어요.", "친구가 있어요.", "저기 있어요.", "내일 있어요."], answer: 2,
        sourceUrl: "hwajangsil1.html", sourceTitle: "Where Is the Restroom?" },
      { id: "L06", audioText: "남자: 오늘 회사에 몇 시까지 가요? 여자: 8시까지 가요.", question: "여자는 몇 시까지 회사에 갑니까?",
        options: ["6시", "7시", "8시", "9시"], answer: 2,
        sourceUrl: "chulgeun.html", sourceTitle: "Go to Work" },
      { id: "L07", audioText: "남자: 안전모를 써 주세요. 여자: 네, 알겠습니다.", question: "남자가 여자에게 부탁한 것은 무엇입니까?",
        options: ["장갑 착용", "안전모 착용", "마스크 착용", "안전화 착용"], answer: 1,
        sourceUrl: "anjeonmo.html", sourceTitle: "Safety Helmet" },
      { id: "L08", audioText: "여자: 오늘 몸이 아파서 병원에 가야 해요. 남자: 그럼 오늘 회사를 쉬세요.", question: "여자는 오늘 무엇을 합니까?",
        options: ["병원에 간다", "학교에 간다", "여행을 간다", "회사에 간다"], answer: 0,
        sourceUrl: "apayo1.html", sourceTitle: "Im Sick" },
      { id: "L09", audioText: "남자: 이 서류에 사인해 주세요. 여자: 네, 여기 사인할게요.", question: "여자가 하는 행동은 무엇입니까?",
        options: ["서류를 읽는다", "서류를 버린다", "서류를 복사한다", "서류에 사인한다"], answer: 3,
        sourceUrl: "seomyeong.html", sourceTitle: "Signature" },
      { id: "L10", audioText: "남자: 다음 주에 휴가를 가고 싶어요. 여자: 언제부터 언제까지예요?", question: "여자가 남자에게 물어본 것은 무엇입니까?",
        options: ["휴가 비용", "휴가 장소", "휴가 이유", "휴가 기간"], answer: 3,
        sourceUrl: "hyuga.html", sourceTitle: "Vacation" },
      { id: "L11", audioText: "공장 안에서는 뛰지 마세요. 위험합니다.", question: "이 방송의 목적은 무엇입니까?",
        options: ["식사를 안내한다", "안전 주의를 준다", "퇴근을 알린다", "휴식을 알린다"], answer: 1,
        sourceUrl: "wiheom.html", sourceTitle: "Danger" },
      { id: "L12", audioText: "오늘 야근이 있습니다. 저녁 8시까지 근무합니다.", question: "오늘 근무는 몇 시까지입니까?",
        options: ["저녁 8시", "밤 10시", "낮 12시", "저녁 6시"], answer: 0,
        sourceUrl: "yageun.html", sourceTitle: "Night Overtime" },
      { id: "L13", audioText: "이번 달 월급은 25일에 나옵니다.", question: "월급은 언제 나옵니까?",
        options: ["1일", "25일", "30일", "15일"], answer: 1,
        sourceUrl: "wolgeup.html", sourceTitle: "Monthly Salary" },
      { id: "L14", audioText: "남자: 이 기계가 고장 났어요. 여자: 반장님께 말씀드릴게요.", question: "여자는 무엇을 할 것입니까?",
        options: ["기계를 고친다", "집에 간다", "반장에게 알린다", "기계를 버린다"], answer: 2,
        sourceUrl: "banjang.html", sourceTitle: "Foreman" },
      { id: "L15", audioText: "다음 버스는 10분 후에 도착합니다.", question: "버스는 언제 도착합니까?",
        options: ["10시간 후", "10분 후", "내일", "지금"], answer: 1,
        sourceUrl: "bus.html", sourceTitle: "Bus" },
      { id: "L16", audioText: "남자: 실례합니다. 은행이 어디예요? 여자: 이 길로 쭉 가세요. 왼쪽에 있어요.", question: "은행은 어느 쪽에 있습니까?",
        options: ["오른쪽", "왼쪽", "위쪽", "뒤쪽"], answer: 1,
        sourceUrl: "oenjjogeurodoseyo1.html", sourceTitle: "Turn Left" },
      { id: "L17", audioText: "물건을 받으면 바로 검사해 주세요.", question: "물건을 받은 후에 해야 할 일은 무엇입니까?",
        options: ["버린다", "포장한다", "검사한다", "판매한다"], answer: 2,
        sourceUrl: "geomsa.html", sourceTitle: "Inspection" },
      { id: "L18", audioText: "남자: 오늘 왜 늦었어요? 여자: 죄송합니다. 버스를 놓쳤어요.", question: "여자가 늦은 이유는 무엇입니까?",
        options: ["몸이 아팠다", "잠을 잤다", "버스를 놓쳤다", "길을 잃었다"], answer: 2,
        sourceUrl: "jigak.html", sourceTitle: "Lateness" },
      { id: "L19", audioText: "이 작업은 장갑을 끼고 하세요.", question: "이 작업을 할 때 착용해야 하는 것은 무엇입니까?",
        options: ["모자", "안경", "신발", "장갑"], answer: 3,
        sourceUrl: "anjeonjanggap.html", sourceTitle: "Safety Gloves" },
      { id: "L20", audioText: "남자: 내일부터 3일 동안 휴가입니다. 여자: 네, 잘 다녀오세요.", question: "남자는 며칠 동안 휴가입니까?",
        options: ["1일", "5일", "3일", "일주일"], answer: 2,
        sourceUrl: "yeonchahyuga.html", sourceTitle: "Annual Leave" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n손으로 종이나 천을 자를 때 쓰는 도구입니다.",
        options: ["안경", "볼펜", "가위", "가방"], answer: 2,
        sourceUrl: "gawi.html", sourceTitle: "Scissors" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n공사장에서 땅을 파는 데 쓰는 큰 기계입니다.",
        options: ["굴착기", "자전거", "트랙터", "지게차"], answer: 0,
        sourceUrl: "jakeop.html", sourceTitle: "Work" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 의자에 앉아서 종이책을 펴고 들여다보고 있습니다.",
        options: ["피아노를 치고 있습니다.", "친구를 만나고 있습니다.", "책을 읽고 있습니다.", "밥을 먹고 있습니다."], answer: 2,
        sourceUrl: "book.html", sourceTitle: "Book" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n노란 바탕에 번개 모양이 그려진 경고 표지판입니다.",
        options: ["불이 붙을 수 있으니까 조심하세요.", "떨어질 수 있으니까 조심하세요.", "바닥이 미끄러우니까 조심하세요.", "전기가 흐르니까 조심하세요."], answer: 3,
        sourceUrl: "gyeonggo.html", sourceTitle: "Warning" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.",
        options: ["공장이 일해요.", "공장에서 일해요.", "공장을 일해요.", "공장에게 일해요."], answer: 1,
        sourceUrl: "geunroja.html", sourceTitle: "Worker" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.",
        options: ["친구한테서 선물을 받었어요.", "퇴근할 때 문을 닫라요.", "심심하면 한국 노래를 듣어요.", "오늘 시내에서 많이 걸었어요."], answer: 3,
        sourceUrl: "city.html", sourceTitle: "City" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"튼튼치과 진료 시간: 오전 9시 ~ 오후 6시 (일요일 휴무)\"\n\n이 병원이 문을 여는 시간은 언제입니까?",
        options: ["오전 9시", "오전 6시", "오후 9시", "휴무일 없음"], answer: 0,
        sourceUrl: "byeongga.html", sourceTitle: "Sick Leave" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n복장",
        options: ["비빔밥", "작업복", "기차표", "컴퓨터"], answer: 1,
        sourceUrl: "bohogu.html", sourceTitle: "Protective Gear" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n작업장",
        options: ["근로자가 상담하는 곳입니다.", "근로자가 일하는 곳입니다.", "근로자가 운동하는 곳입니다.", "근로자가 거주하는 곳입니다."], answer: 1,
        sourceUrl: "geunmuji.html", sourceTitle: "Workplace" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"이번 주 급여는 통장으로 입금됩니다. 급여 명세서는 이메일로 발송됩니다.\"\n\n급여 명세서는 어떻게 받습니까?",
        options: ["이메일로 받습니다.", "문자로 받습니다.", "우편으로 받습니다.", "직접 받으러 갑니다."], answer: 0,
        sourceUrl: "geupyeo-myeongseoseo.html", sourceTitle: "Payslip" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n지급 방법: _____________",
        options: ["출근 시간", "통장 입금", "생일 선물", "가족 모임"], answer: 1,
        sourceUrl: "tongjang.html", sourceTitle: "Bank Account" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n한국어를 배우고 싶지만 학원에 갈 시간이 없습니다. 그래서 퇴근 후에 인터넷 강의를 ______ 한국어를 공부하고 있습니다.",
        options: ["듣자마자", "들으려고", "들으면서", "듣느라고"], answer: 2,
        sourceUrl: "gongbu1.html", sourceTitle: "Let's Study" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n오늘은 다른 날보다 길이 많이 막힙니다. ______ 가지 않으면 회사에 늦을 것 같습니다.",
        options: ["조심하게", "서둘러서", "서두르게", "조심해서"], answer: 1,
        sourceUrl: "ppalli1.html", sourceTitle: "Hurry Up" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n오늘은 날씨가 너무 덥습니다. 집에 오자마자 선풍기를 ______ 시원한 물을 마셨습니다.",
        options: ["틀면", "틀고", "틀려면", "틀려고"], answer: 1,
        sourceUrl: "water.html", sourceTitle: "Water" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n작업 중 손을 다쳤을 때는 상처가 가벼워도 바로 소독을 해야 합니다. 그리고 병원에 가서 진료를 받고 필요하면 주사를 ______",
        options: ["맞는 것이 좋습니다.", "놓는 것이 좋습니다.", "놓지 않도록 합니다.", "맞지 않도록 합니다."], answer: 0,
        sourceUrl: "eunggeupcheochi.html", sourceTitle: "First Aid" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n어두운 곳에서 작업할 때는 가시성이 높은 ______ 이것을 입으면 멀리서도 잘 보여서 사고를 막을 수 있습니다.",
        options: ["반사 조끼를 착용해야 합니다.", "보호 장갑을 구매해야 합니다.", "환기 장치를 작동해야 합니다.", "비상 계단을 이용해야 합니다."], answer: 0,
        sourceUrl: "anjeon_suchik.html", sourceTitle: "Safety Rules" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n손에 쥐고 철사를 끊거나 구부릴 때 쓰는 도구입니다. 전선이나 작은 부품을 잡을 때도 사용합니다.",
        options: ["망치", "펜치", "쇠톱", "토치"], answer: 1,
        sourceUrl: "penchi.html", sourceTitle: "Pliers" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n한국 사람들은 계절마다 즐겨 먹는 음식이 있습니다. 여름에는 차갑고 시원한 냉면, 콩국수, 팥빙수 등을 많이 먹습니다. 겨울에는 뜨거운 국이나 따뜻한 팥죽, 군고구마, 호떡 등을 자주 먹습니다.",
        options: ["음식 재료", "조리 방법", "조리 시기", "계절 음식"], answer: 3,
        sourceUrl: "food.html", sourceTitle: "Food" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"사내 휴게실 이용 안내: 출입문 비밀번호는 게시판에서 확인하세요. 회사 직원이면 누구나 이용할 수 있습니다. 이용 후에는 문을 꼭 닫고 나가야 합니다.\"",
        options: ["휴게실 출입문에는 비밀번호가 없습니다.", "이용 후에는 문을 열어 두고 나가야 합니다.", "다른 회사 직원도 이용할 수 있습니다.", "회사 직원은 누구나 휴게실을 이용할 수 있습니다."], answer: 3,
        sourceUrl: "chwieopgyuchik.html", sourceTitle: "Employment Rules" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"한국에서 일하는 외국인 근로자는 4대 사회보험 혜택을 받습니다. 이 중 산재보험은 사업주만 가입하면 되지만, 국민연금·건강보험·고용보험은 사업주와 근로자 모두 반드시 가입해야 합니다.\"",
        options: ["근로자는 원하는 보험만 선택해서 가입할 수 있습니다.", "산재보험은 사업주만 가입하면 됩니다.", "국민연금은 사업주만 가입하면 됩니다.", "산재보험은 근로자와 사업주가 모두 가입해야 합니다."], answer: 1,
        sourceUrl: "sanjaeboheom.html", sourceTitle: "Industrial Accident Insurance" }
    ]
  },
  {
    id: "set_02",
    title: "EPS-TOPIK Mock Test #2",
    free: true,
    listening: [
      { id: "L01", audioText: "이 음식 맛이 어때요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["맛있어요.", "조용해요.", "커요.", "빨라요."], answer: 0,
        sourceUrl: "masisseo1.html", sourceTitle: "It's Delicious" },
      { id: "L02", audioText: "생일이 언제예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["만원이에요.", "회사예요.", "다음 달이에요.", "형이에요."], answer: 2,
        sourceUrl: "saengilchukha1.html", sourceTitle: "Happy Birthday" },
      { id: "L03", audioText: "이름이 뭐예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["한국이에요.", "교실이에요.", "김민수예요.", "일곱 살이에요."], answer: 2,
        sourceUrl: "irum1.html", sourceTitle: "What's Your Name" },
      { id: "L04", audioText: "커피 드시겠어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 주세요.", "아니요, 가까워요.", "네, 비싸요.", "아니요, 늦었어요."], answer: 0,
        sourceUrl: "keopijuseyo1.html", sourceTitle: "Coffee Please" },
      { id: "L05", audioText: "여기서 멀어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 가까워요.", "네, 맛있어요.", "네, 커요.", "아니요, 늦었어요."], answer: 0,
        sourceUrl: "gakkawoyo1.html", sourceTitle: "Is It Close?" },
      { id: "L06", audioText: "남자: 이번 달 수당이 얼마예요? 여자: 20만원 정도예요.", question: "여자의 이번 달 수당은 얼마입니까?",
        options: ["20만원", "30만원", "5만원", "10만원"], answer: 0,
        sourceUrl: "sudang.html", sourceTitle: "Allowance" },
      { id: "L07", audioText: "남자: 기숙사에서 지내요? 여자: 네, 회사 기숙사에서 지내요.", question: "여자는 어디에서 지냅니까?",
        options: ["친구 집", "호텔", "회사 기숙사", "고향집"], answer: 2,
        sourceUrl: "gisuksa.html", sourceTitle: "Dormitory" },
      { id: "L08", audioText: "남자: 계약 기간이 언제까지예요? 여자: 내년 12월까지예요.", question: "여자의 계약 기간은 언제까지입니까?",
        options: ["다음 주까지", "이번 달까지", "올해 6월까지", "내년 12월까지"], answer: 3,
        sourceUrl: "gyeyak-gigan.html", sourceTitle: "Contract Period" },
      { id: "L09", audioText: "남자: 오늘 제품 몇 개 만들었어요? 여자: 오백 개 만들었어요.", question: "여자는 오늘 제품을 몇 개 만들었습니까?",
        options: ["오 개", "오십 개", "오천 개", "오백 개"], answer: 3,
        sourceUrl: "jepum.html", sourceTitle: "Product" },
      { id: "L10", audioText: "남자: 이 부품을 어디에 두면 돼요? 여자: 창고에 두세요.", question: "부품을 어디에 둬야 합니까?",
        options: ["식당", "창고", "사무실", "기숙사"], answer: 1,
        sourceUrl: "changgo.html", sourceTitle: "Warehouse" },
      { id: "L11", audioText: "이 기계는 고장 났으니 사용하지 마세요.", question: "이 방송의 목적은 무엇입니까?",
        options: ["회식 안내", "퇴근 시간 안내", "점심시간 안내", "기계 사용 금지 안내"], answer: 3,
        sourceUrl: "gojang.html", sourceTitle: "Breakdown" },
      { id: "L12", audioText: "오늘부터 새 사원증을 지급합니다.", question: "오늘부터 무엇을 지급합니까?",
        options: ["사원증", "안전화", "식권", "교통비"], answer: 0,
        sourceUrl: "sinbunjeung.html", sourceTitle: "ID Card" },
      { id: "L13", audioText: "남자: 다음 주에 회사를 그만둬요. 여자: 왜 그만두세요?", question: "남자는 다음 주에 무엇을 합니까?",
        options: ["휴가를 간다", "회사를 그만둔다", "출장을 간다", "이직 준비를 한다"], answer: 1,
        sourceUrl: "sajik.html", sourceTitle: "Resignation" },
      { id: "L14", audioText: "남자: 이번 달 세금이 얼마 나왔어요? 여자: 몇만 원 나왔어요.", question: "무엇에 대해 이야기하고 있습니까?",
        options: ["상여금", "월급", "세금", "수당"], answer: 2,
        sourceUrl: "segeum.html", sourceTitle: "Tax" },
      { id: "L15", audioText: "여권을 꼭 가지고 다니세요.", question: "무엇을 가지고 다니라고 했습니까?",
        options: ["우산", "휴대폰", "지갑", "여권"], answer: 3,
        sourceUrl: "yeogwon.html", sourceTitle: "Passport" },
      { id: "L16", audioText: "남자: 비자 연장 신청했어요? 여자: 네, 지난주에 했어요.", question: "여자는 언제 비자 연장을 신청했습니까?",
        options: ["오늘", "내일", "지난주", "다음 달"], answer: 2,
        sourceUrl: "cheryuyeonjang.html", sourceTitle: "Extension of Stay" },
      { id: "L17", audioText: "포장한 제품은 창고로 옮겨 주세요.", question: "포장한 제품은 어디로 옮겨야 합니까?",
        options: ["창고", "식당", "주차장", "사무실"], answer: 0,
        sourceUrl: "pojang.html", sourceTitle: "Packaging" },
      { id: "L18", audioText: "남자: 오늘 검사에서 불량품이 나왔어요. 여자: 몇 개나 나왔어요?", question: "무엇에 대해 이야기하고 있습니까?",
        options: ["완성품", "원자재", "견본품", "불량품"], answer: 3,
        sourceUrl: "bulryangpum.html", sourceTitle: "Defective Product" },
      { id: "L19", audioText: "이 자재는 조심히 다뤄 주세요. 깨지기 쉽습니다.", question: "이 자재를 어떻게 다뤄야 합니까?",
        options: ["버려야 한다", "조심히 다뤄야 한다", "빨리 옮겨야 한다", "밖에 둬야 한다"], answer: 1,
        sourceUrl: "wonjajae.html", sourceTitle: "Raw Materials" },
      { id: "L20", audioText: "남자: 다음 달에 최저임금이 오른대요. 여자: 그래요? 잘됐네요.", question: "다음 달에 무엇이 오릅니까?",
        options: ["최저임금", "기름값", "물가", "집세"], answer: 0,
        sourceUrl: "choejeoimgeum.html", sourceTitle: "Minimum Wage" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n물건을 나르거나 옮길 때 타는 큰 차입니다.",
        options: ["배", "자전거", "비행기", "트럭"], answer: 3,
        sourceUrl: "unban.html", sourceTitle: "Transport" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n음식을 넣어서 차갑게 보관하는 가전제품입니다.",
        options: ["세탁기", "냉장고", "청소기", "전자레인지"], answer: 1,
        sourceUrl: "electronics.html", sourceTitle: "Electronics" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 침대에 누워서 눈을 감고 자고 있습니다.",
        options: ["운전하고 있습니다.", "요리하고 있습니다.", "자고 있습니다.", "일하고 있습니다."], answer: 2,
        sourceUrl: "bed.html", sourceTitle: "Bed" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n빨간 바탕에 불꽃 모양이 그려진 표지판입니다.",
        options: ["미끄러우니 조심하세요.", "무거우니 조심하세요.", "전기가 흐르니 조심하세요.", "불이 날 수 있으니 조심하세요."], answer: 3,
        sourceUrl: "hwajae.html", sourceTitle: "Fire" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n저는 아침 8시에 회사___ 도착해요.",
        options: ["회사에 도착해요.", "회사가 도착해요.", "회사에서 도착해요.", "회사를 도착해요."], answer: 0,
        sourceUrl: "company.html", sourceTitle: "Company" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n출근하기 전에 얼굴을 ______.",
        options: ["씻으요.", "씻아요.", "씻었요.", "씻어요."], answer: 3,
        sourceUrl: "morning.html", sourceTitle: "Morning" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"기차 운행 시간: 오전 6시 ~ 오후 11시 (배차 간격 15분)\"\n\n기차는 몇 분마다 옵니까?",
        options: ["11분마다", "6분마다", "30분마다", "15분마다"], answer: 3,
        sourceUrl: "train.html", sourceTitle: "Train" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n주방",
        options: ["요리", "쇼핑", "잠", "운동"], answer: 0,
        sourceUrl: "kitchen.html", sourceTitle: "Kitchen" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n부품",
        options: ["근로자가 쉬는 곳입니다.", "회사 대표를 말합니다.", "기계나 제품을 만드는 데 쓰이는 작은 조각입니다.", "월급을 받는 날입니다."], answer: 2,
        sourceUrl: "bupum.html", sourceTitle: "Parts" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"이번 달 상여금은 급여와 함께 지급됩니다. 지급일은 25일입니다.\"\n\n상여금은 언제 지급됩니까?",
        options: ["1일", "25일", "30일", "15일"], answer: 1,
        sourceUrl: "sangyeogeum.html", sourceTitle: "Bonus" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n지급 방법: _____________",
        options: ["계좌 이체", "생일 선물", "가족 모임", "출근 시간"], answer: 0,
        sourceUrl: "gyejwabeonho.html", sourceTitle: "Account Number" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n기계 소리가 이상하면 ______ 반장님께 알려야 합니다.",
        options: ["즉시", "즉시하게", "즉시로", "즉시히"], answer: 0,
        sourceUrl: "ojakdong.html", sourceTitle: "Malfunction" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n물건이 도착하면 ______ 수량을 확인해야 합니다.",
        options: ["먼저가", "먼저", "먼저는", "먼저를"], answer: 1,
        sourceUrl: "suryang.html", sourceTitle: "Quantity" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n오늘은 잔업이 있어서 ______ 집에 갈 수 없습니다.",
        options: ["일찍", "일찍히", "일찍게", "일찍이는"], answer: 0,
        sourceUrl: "janeop.html", sourceTitle: "Remaining Work" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n몸이 안 좋으면 무리하지 말고 팀장님께 ______",
        options: ["말씀드리는 것이 좋습니다.", "말씀드릴 수 없습니다.", "말씀드리지 않는 것이 좋습니다.", "말씀드려야 안 됩니다."], answer: 0,
        sourceUrl: "timjang.html", sourceTitle: "Team Leader" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n밤에 어두운 길을 걸을 때는 ______ 이것을 착용하면 차량 운전자가 멀리서도 알아볼 수 있습니다.",
        options: ["보호 장갑을 구매해야 합니다.", "마스크를 착용해야 합니다.", "야광 조끼를 착용해야 합니다.", "장화를 신어야 합니다."], answer: 2,
        sourceUrl: "anjeon_gyoyuk.html", sourceTitle: "Safety Training" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n선을 정확하게 재거나 물건의 길이를 측정할 때 쓰는 도구입니다.",
        options: ["드라이버", "가위", "줄자", "망치"], answer: 2,
        sourceUrl: "julja.html", sourceTitle: "Tape Measure" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n한국의 대중교통은 버스, 지하철, 택시가 있습니다. 출퇴근 시간에는 사람이 많아서 복잡합니다. 교통카드를 사용하면 편리하게 이용할 수 있습니다.",
        options: ["한국의 명절", "계절별 옷차림", "대중교통 이용", "음식 문화"], answer: 2,
        sourceUrl: "transport.html", sourceTitle: "Transport" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"기숙사 이용 안내: 기숙사는 회사 근로자만 이용할 수 있습니다. 외부인 출입은 금지되어 있으며, 밤 12시 이후에는 조용히 해 주시기 바랍니다.\"",
        options: ["외부인도 자유롭게 출입할 수 있습니다.", "기숙사는 아무나 이용할 수 있습니다.", "기숙사는 회사 근로자만 이용할 수 있습니다.", "밤 12시 이후에는 시끄러워도 됩니다."], answer: 2,
        sourceUrl: "chulipgeumji.html", sourceTitle: "No Entry" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"근로계약서에는 근무 시간, 급여, 휴일 등이 명시되어 있습니다. 근로자와 사업주는 각각 한 부씩 보관해야 합니다.\"",
        options: ["근로자는 보관할 필요가 없습니다.", "근로계약서에는 급여만 적혀 있습니다.", "근로자와 사업주가 각각 한 부씩 보관해야 합니다.", "사업주만 보관하면 됩니다."], answer: 2,
        sourceUrl: "geunro-gyeyakseo.html", sourceTitle: "Labor Contract" }
    ]
  },
  {
    id: "set_03",
    title: "EPS-TOPIK Mock Test #3",
    free: true,
    listening: [
      { id: "L01", audioText: "미안해요, 늦었어요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["비싸요.", "괜찮아요.", "맛있어요.", "가까워요."], answer: 1,
        sourceUrl: "gwaenchanayo1.html", sourceTitle: "It's Okay" },
      { id: "L02", audioText: "많이 피곤해 보여요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 늦었어요.", "아니요, 추워요.", "네, 배고파요.", "네, 좀 피곤해요."], answer: 3,
        sourceUrl: "pigon1.html", sourceTitle: "Im Tired" },
      { id: "L03", audioText: "천천히 말해 주세요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 천천히 말할게요.", "아니요, 늦었어요.", "네, 빨리 갈게요.", "아니요, 비싸요."], answer: 0,
        sourceUrl: "cheoncheonhi1.html", sourceTitle: "Please Speak Slowly" },
      { id: "L04", audioText: "이해했어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 비싸요.", "네, 이해했어요.", "아니요, 배고파요.", "아니요, 늦었어요."], answer: 1,
        sourceUrl: "ihae1.html", sourceTitle: "I Understand" },
      { id: "L05", audioText: "도와주세요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 도와드릴게요.", "네, 비싸요.", "아니요, 맛있어요.", "아니요, 가까워요."], answer: 0,
        sourceUrl: "dowajuseyo1.html", sourceTitle: "Help Me" },
      { id: "L06", audioText: "남자: 다친 곳이 어디예요? 여자: 손가락을 다쳤어요.", question: "여자는 어디를 다쳤습니까?",
        options: ["머리", "손가락", "허리", "다리"], answer: 1,
        sourceUrl: "busang.html", sourceTitle: "Injury" },
      { id: "L07", audioText: "남자: 상처에 뭐 발랐어요? 여자: 연고를 발랐어요.", question: "여자는 상처에 무엇을 발랐습니까?",
        options: ["연고", "기름", "물", "소금"], answer: 0,
        sourceUrl: "yeongo.html", sourceTitle: "Ointment" },
      { id: "L08", audioText: "남자: 이 도구 이름이 뭐예요? 여자: 스패너예요.", question: "이 도구의 이름은 무엇입니까?",
        options: ["가위", "드라이버", "망치", "스패너"], answer: 3,
        sourceUrl: "seupaeneo_renchi.html", sourceTitle: "Spanner / Wrench" },
      { id: "L09", audioText: "안전 고글을 꼭 착용하세요.", question: "무엇을 착용해야 합니까?",
        options: ["안전 고글", "장갑", "모자", "마스크"], answer: 0,
        sourceUrl: "boangyeong.html", sourceTitle: "Safety Goggles" },
      { id: "L10", audioText: "귀마개는 소음이 심한 곳에서 착용하세요.", question: "귀마개는 언제 착용해야 합니까?",
        options: ["추울 때", "더울 때", "비가 올 때", "소음이 심할 때"], answer: 3,
        sourceUrl: "gwimagae.html", sourceTitle: "Earplug" },
      { id: "L11", audioText: "화재가 발생하면 즉시 비상구로 대피하세요.", question: "화재 발생 시 어떻게 해야 합니까?",
        options: ["창문을 연다", "비상구로 대피한다", "계속 일한다", "엘리베이터를 탄다"], answer: 1,
        sourceUrl: "bisanggu.html", sourceTitle: "Emergency Exit" },
      { id: "L12", audioText: "남자: 소화기는 어디에 있어요? 여자: 저기 벽에 걸려 있어요.", question: "소화기는 어디에 있습니까?",
        options: ["사무실에 있다", "벽에 걸려 있다", "창고에 있다", "바닥에 있다"], answer: 1,
        sourceUrl: "sohwagi.html", sourceTitle: "Fire Extinguisher" },
      { id: "L13", audioText: "이 구역은 흡연 구역입니다.", question: "이 구역은 무엇을 하는 곳입니까?",
        options: ["휴식", "흡연", "식사", "회의"], answer: 1,
        sourceUrl: "heupyeonguyeok.html", sourceTitle: "Smoking Area" },
      { id: "L14", audioText: "남자: 다음 정류장에서 내려 주세요. 여자: 네, 알겠습니다.", question: "남자는 여자에게 무엇을 부탁했습니까?",
        options: ["창문을 열기", "다음 정류장에서 내리기", "문을 닫기", "빨리 가기"], answer: 1,
        sourceUrl: "yeogiseosewojuseyo1.html", sourceTitle: "Stop Here" },
      { id: "L15", audioText: "이 길로 쭉 가다가 오른쪽으로 도세요.", question: "어느 방향으로 가야 합니까?",
        options: ["왼쪽", "위쪽", "오른쪽", "아래쪽"], answer: 2,
        sourceUrl: "oreunjjogeurodoseyo1.html", sourceTitle: "Turn Right" },
      { id: "L16", audioText: "남자: 길을 잃었어요. 여기가 어디예요? 여자: 여기는 시청 앞이에요.", question: "남자는 지금 어떤 상황입니까?",
        options: ["길을 잃었다", "돈이 없다", "시간이 없다", "배가 고프다"], answer: 0,
        sourceUrl: "gireulireosseoyo1.html", sourceTitle: "I'm Lost" },
      { id: "L17", audioText: "남자: 오늘 왜 일찍 왔어요? 여자: 차가 안 막혀서 일찍 왔어요.", question: "여자는 왜 일찍 왔습니까?",
        options: ["차가 안 막혀서", "버스를 놓쳐서", "길을 잃어서", "늦잠을 자서"], answer: 0,
        sourceUrl: "iljjikwasseoyo1.html", sourceTitle: "I'm Early" },
      { id: "L18", audioText: "질문 있으면 손을 들어 주세요.", question: "질문이 있으면 어떻게 해야 합니까?",
        options: ["자리에서 일어난다", "크게 말한다", "문을 두드린다", "손을 든다"], answer: 3,
        sourceUrl: "jilmunisseoyo1.html", sourceTitle: "I Have a Question" },
      { id: "L19", audioText: "남자: 이 서류 다 작성했어요? 여자: 네, 다 작성했어요.", question: "여자는 서류를 어떻게 했습니까?",
        options: ["아직 안 했다", "버렸다", "잃어버렸다", "다 작성했다"], answer: 3,
        sourceUrl: "sincheongseo.html", sourceTitle: "Application Form" },
      { id: "L20", audioText: "이 제품에는 시리얼 번호가 붙어 있습니다.", question: "이 제품에 무엇이 붙어 있습니까?",
        options: ["보증서", "시리얼 번호", "사용설명서", "가격표"], answer: 1,
        sourceUrl: "ilryeonbeonho.html", sourceTitle: "Serial Number" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n못을 박거나 물건을 두드릴 때 쓰는 도구입니다.",
        options: ["드라이버", "펜치", "망치", "가위"], answer: 2,
        sourceUrl: "mangchi.html", sourceTitle: "Hammer" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n나사를 돌려서 조이거나 풀 때 쓰는 도구입니다.",
        options: ["가위", "드라이버", "줄자", "망치"], answer: 1,
        sourceUrl: "deuraibeo.html", sourceTitle: "Screwdriver" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 서서 큰 소리로 전화 통화를 하고 있습니다.",
        options: ["잠을 자고 있습니다.", "전화를 하고 있습니다.", "요리를 하고 있습니다.", "운전을 하고 있습니다."], answer: 1,
        sourceUrl: "friend.html", sourceTitle: "Friend" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n초록 바탕에 걷는 사람 모양이 그려진 표지판입니다.",
        options: ["이 길은 위험합니다.", "이 길로 대피하세요.", "이 길은 출입 금지입니다.", "이 길은 공사 중입니다."], answer: 1,
        sourceUrl: "pinangu.html", sourceTitle: "Escape Exit" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n다친 손가락___ 붕대를 감았어요.",
        options: ["손가락을 붕대를 감았어요.", "손가락에서 붕대를 감았어요.", "손가락에 붕대를 감았어요.", "손가락이 붕대를 감았어요."], answer: 2,
        sourceUrl: "bungdae.html", sourceTitle: "Bandage" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n작업 전에 안전화를 ______.",
        options: ["신으요.", "신었요.", "신어요.", "신아요."], answer: 2,
        sourceUrl: "anjeonhwa.html", sourceTitle: "Safety Shoes" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"소방 훈련 안내: 이번 주 금요일 오후 2시에 실시합니다. 전 직원 참여 필수입니다.\"\n\n소방 훈련은 언제 실시합니까?",
        options: ["오늘 오전", "다음 주 월요일", "이번 주 금요일 오후 2시", "이번 달 말"], answer: 2,
        sourceUrl: "anjeon_jeomgeom.html", sourceTitle: "Safety Inspection" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n구급함",
        options: ["음식을 보관하는 상자입니다.", "서류를 보관하는 상자입니다.", "다쳤을 때 필요한 약과 도구가 들어 있는 상자입니다.", "월급을 계산하는 상자입니다."], answer: 2,
        sourceUrl: "gugeupham.html", sourceTitle: "First Aid Kit" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n소독약",
        options: ["상처를 깨끗하게 소독할 때 사용합니다.", "기계를 수리할 때 사용합니다.", "옷을 세탁할 때 사용합니다.", "바닥을 청소할 때 사용합니다."], answer: 0,
        sourceUrl: "sodongyak.html", sourceTitle: "Antiseptic" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"산업재해 신고 안내: 사고가 발생하면 즉시 반장님이나 관리자에게 알리세요.\"\n\n사고가 발생하면 누구에게 알려야 합니까?",
        options: ["가족", "경찰", "반장님이나 관리자", "친구"], answer: 2,
        sourceUrl: "singo.html", sourceTitle: "Report / Notification" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n비상 연락처: _____________",
        options: ["소방서 전화번호", "생일 날짜", "취미", "좋아하는 음식"], answer: 0,
        sourceUrl: "bisang_yeollakcheo.html", sourceTitle: "Emergency Contact" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n작업 중 어지러우면 ______ 쉬어야 합니다.",
        options: ["즉시", "즉시히", "즉시하게", "즉시로"], answer: 0,
        sourceUrl: "eojireumjeung.html", sourceTitle: "Dizziness" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n쓰러진 사람을 발견하면 ______ 심폐소생술을 실시해야 합니다.",
        options: ["바로는", "바로를", "바로가", "바로"], answer: 3,
        sourceUrl: "simpyesosaengsul.html", sourceTitle: "CPR" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n화재가 나면 엘리베이터를 타지 말고 ______ 대피해야 합니다.",
        options: ["계단으로", "계단도", "계단을", "계단이"], answer: 0,
        sourceUrl: "daepi.html", sourceTitle: "Evacuation" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n가스 냄새가 나면 창문을 열고 ______",
        options: ["환기시키지 않는 것이 좋습니다.", "환기시키는 것이 좋습니다.", "환기해야 안 됩니다.", "환기할 수 없습니다."], answer: 1,
        sourceUrl: "gaseunuchul.html", sourceTitle: "Gas Leak" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n전선이 벗겨진 곳은 만지지 말고 ______ 이것을 지키면 감전 사고를 막을 수 있습니다.",
        options: ["물을 뿌려야 합니다.", "맨손으로 만져야 합니다.", "절연 장갑을 착용해야 합니다.", "바로 잡아당겨야 합니다."], answer: 2,
        sourceUrl: "gamjeon.html", sourceTitle: "Electric Shock" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n전기가 통하지 않도록 막아 주는 것으로, 감전 사고를 예방하는 데 씁니다.",
        options: ["소화기", "펜치", "줄자", "절연체"], answer: 3,
        sourceUrl: "jeoryeon.html", sourceTitle: "Insulation" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n작업장에서는 항상 안전 수칙을 지켜야 합니다. 보호 장비를 착용하고, 위험한 구역에는 함부로 들어가지 않아야 합니다. 사고가 발생하면 즉시 신고해야 합니다.",
        options: ["제품 포장 방법", "휴가 신청 방법", "작업장 안전 수칙", "월급 계산 방법"], answer: 2,
        sourceUrl: "anjeon_pyojipan.html", sourceTitle: "Safety Sign" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"비상벨 사용 안내: 위급한 상황이 발생하면 비상벨을 누르세요. 비상벨을 누르면 관리자에게 즉시 연락이 갑니다.\"",
        options: ["비상벨을 누르면 관리자에게 연락이 갑니다.", "비상벨을 누르면 아무 일도 일어나지 않습니다.", "비상벨은 평소에도 눌러도 됩니다.", "비상벨은 사용할 수 없습니다."], answer: 0,
        sourceUrl: "bisangbel.html", sourceTitle: "Emergency Bell" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"위험물 취급 안내: 위험물은 지정된 장소에만 보관해야 합니다. 화기 근처에는 절대 두면 안 됩니다.\"",
        options: ["위험물은 아무 곳에나 보관해도 됩니다.", "위험물은 화기 근처에 둬도 됩니다.", "위험물은 지정된 장소에만 보관해야 합니다.", "위험물 취급에는 규정이 없습니다."], answer: 2,
        sourceUrl: "yuhaemuljil.html", sourceTitle: "Hazardous Material" }
    ]
  },
  {
    id: "set_04",
    title: "EPS-TOPIK Mock Test #4",
    free: true,
    listening: [
      { id: "L01", audioText: "오늘 기분이 어때요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["좋아요.", "멀어요.", "늦었어요.", "비싸요."], answer: 0,
        sourceUrl: "gibun1.html", sourceTitle: "I Feel Good" },
      { id: "L02", audioText: "지금 바빠요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 좀 바빠요.", "네, 맛있어요.", "아니요, 늦었어요.", "아니요, 커요."], answer: 0,
        sourceUrl: "bappa1.html", sourceTitle: "Im Busy" },
      { id: "L03", audioText: "오늘 시간 있어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 멀어요.", "네, 시간 있어요.", "아니요, 비싸요.", "아니요, 추워요."], answer: 1,
        sourceUrl: "sigan1.html", sourceTitle: "Im Free" },
      { id: "L04", audioText: "배 안 고파요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 늦었어요.", "네, 비싸요.", "아니요, 멀어요.", "네, 배고파요."], answer: 3,
        sourceUrl: "baegopa1.html", sourceTitle: "I'm Hungry" },
      { id: "L05", audioText: "졸려요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 커요.", "네, 비싸요.", "네, 졸려요.", "아니요, 가까워요."], answer: 2,
        sourceUrl: "jollyeo1.html", sourceTitle: "Im Sleepy" },
      { id: "L06", audioText: "남자: 오늘 공정이 몇 개 남았어요? 여자: 세 개 남았어요.", question: "공정이 몇 개 남았습니까?",
        options: ["다섯 개", "한 개", "세 개", "두 개"], answer: 2,
        sourceUrl: "gongjeong.html", sourceTitle: "Process" },
      { id: "L07", audioText: "남자: 조립은 다 끝났어요? 여자: 네, 방금 끝났어요.", question: "여자는 무엇을 끝냈습니까?",
        options: ["검사", "포장", "조립", "배송"], answer: 2,
        sourceUrl: "jorip.html", sourceTitle: "Assembly" },
      { id: "L08", audioText: "이 제품은 용접이 필요합니다.", question: "이 제품에 무엇이 필요합니까?",
        options: ["용접", "도색", "포장", "세척"], answer: 0,
        sourceUrl: "yongjeop.html", sourceTitle: "Welding" },
      { id: "L09", audioText: "남자: 완성품은 어디에 쌓아 두면 돼요? 여자: 저쪽 팔레트 위에 쌓아 주세요.", question: "완성품을 어디에 쌓아야 합니까?",
        options: ["출입구", "창문 옆", "바닥", "팔레트 위"], answer: 3,
        sourceUrl: "wanseongpum.html", sourceTitle: "Finished Product" },
      { id: "L10", audioText: "오늘 납기일은 내일까지입니다.", question: "납기일은 언제까지입니까?",
        options: ["내일까지", "다음 주까지", "오늘까지", "이번 달 말까지"], answer: 0,
        sourceUrl: "napgi.html", sourceTitle: "Delivery" },
      { id: "L11", audioText: "남자: 불량품은 따로 분류해 주세요. 여자: 네, 알겠습니다.", question: "불량품은 어떻게 해야 합니까?",
        options: ["버린다", "그냥 포장한다", "재사용한다", "따로 분류한다"], answer: 3,
        sourceUrl: "bunryu.html", sourceTitle: "Sorting / Classification" },
      { id: "L12", audioText: "이 부품은 정확한 치수로 측정해야 합니다.", question: "이 부품에 대해 무엇을 해야 합니까?",
        options: ["색깔 확인", "정확한 치수 측정", "무게 확인", "빠른 포장"], answer: 1,
        sourceUrl: "cheukjeong.html", sourceTitle: "Measurement" },
      { id: "L13", audioText: "남자: 기계 설정을 바꿨어요? 여자: 네, 방금 바꿨어요.", question: "여자는 무엇을 했습니까?",
        options: ["기계 설정을 바꿨다", "기계를 껐다", "기계를 옮겼다", "기계를 청소했다"], answer: 0,
        sourceUrl: "seoljeong.html", sourceTitle: "Setting / Configuration" },
      { id: "L14", audioText: "이 기계는 시운전 중입니다.", question: "이 기계는 지금 어떤 상태입니까?",
        options: ["꺼져 있다", "수리 중이다", "고장났다", "시운전 중이다"], answer: 3,
        sourceUrl: "siunjeon.html", sourceTitle: "Test Run" },
      { id: "L15", audioText: "폐기물은 정해진 곳에 버려 주세요.", question: "폐기물을 어디에 버려야 합니까?",
        options: ["창고", "사무실", "아무 곳", "정해진 곳"], answer: 3,
        sourceUrl: "pyegimul.html", sourceTitle: "Waste Material" },
      { id: "L16", audioText: "남자: 재고가 얼마나 남았어요? 여자: 백 개 정도 남았어요.", question: "재고가 얼마나 남았습니까?",
        options: ["십 개 정도", "오십 개 정도", "백 개 정도", "천 개 정도"], answer: 2,
        sourceUrl: "jaego.html", sourceTitle: "Inventory / Stock" },
      { id: "L17", audioText: "남자: 생산량이 목표에 도달했어요? 여자: 아직 못 했어요.", question: "생산량은 목표에 도달했습니까?",
        options: ["알 수 없다", "초과했다", "아직 못 했다", "이미 도달했다"], answer: 2,
        sourceUrl: "saengsallyang.html", sourceTitle: "Production Volume" },
      { id: "L18", audioText: "이 기계는 과부하로 자동 정지되었습니다.", question: "이 기계는 왜 정지되었습니까?",
        options: ["과부하 때문에", "사람이 꺼서", "고장이 나서", "전기가 없어서"], answer: 0,
        sourceUrl: "gwabuhwa.html", sourceTitle: "Overload" },
      { id: "L19", audioText: "남자: 품질 검사는 언제 해요? 여자: 생산 끝난 후에 바로 해요.", question: "품질 검사는 언제 합니까?",
        options: ["생산 시작 전", "퇴근 후에", "생산 끝난 후 바로", "점심시간에"], answer: 2,
        sourceUrl: "pumjilgwanri.html", sourceTitle: "Quality Control" },
      { id: "L20", audioText: "이 상자에는 바코드를 붙여 주세요.", question: "이 상자에 무엇을 붙여야 합니까?",
        options: ["이름표", "경고문", "바코드", "가격표"], answer: 2,
        sourceUrl: "bakodeu.html", sourceTitle: "Barcode" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n물건의 무게를 재는 도구입니다.",
        options: ["저울", "시계", "줄자", "온도계"], answer: 0,
        sourceUrl: "muge.html", sourceTitle: "Weight" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n물건을 눌러서 압축할 때 쓰는 기계입니다.",
        options: ["드라이버", "프레스기", "가위", "망치"], answer: 1,
        sourceUrl: "peureseu.html", sourceTitle: "Pressing" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 기계 앞에 서서 부품을 가공하고 있습니다.",
        options: ["전화를 하고 있습니다.", "부품을 가공하고 있습니다.", "잠을 자고 있습니다.", "밥을 먹고 있습니다."], answer: 1,
        sourceUrl: "gagong.html", sourceTitle: "Processing / Machining" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n노란 바탕에 상자가 떨어지는 그림이 그려진 표지판입니다.",
        options: ["불이 날 수 있으니 조심하세요.", "미끄러우니 조심하세요.", "전기가 흐르니 조심하세요.", "낙하물을 조심하세요."], answer: 3,
        sourceUrl: "pason.html", sourceTitle: "Damage / Breakage" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n완성된 상자___ 창고로 옮겼어요.",
        options: ["상자도 창고로 옮겼어요.", "상자가 창고로 옮겼어요.", "상자를 창고로 옮겼어요.", "상자에서 창고로 옮겼어요."], answer: 2,
        sourceUrl: "mukkeum.html", sourceTitle: "Bundle" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n기계를 사용하기 전에 설명서를 ______.",
        options: ["읽어요.", "읽었요.", "읽으요.", "읽아요."], answer: 0,
        sourceUrl: "gwalli.html", sourceTitle: "Management / Care" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"생산 목표 안내: 이번 주 목표 수량은 5,000개입니다. 매일 진행 상황을 게시판에 기록해 주세요.\"\n\n이번 주 목표 수량은 몇 개입니까?",
        options: ["5,000개", "5개", "50,000개", "500개"], answer: 0,
        sourceUrl: "mokpyoryang.html", sourceTitle: "Target Quantity" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n효율",
        options: ["휴가를 가는 것입니다.", "물건을 포장하는 것입니다.", "월급을 받는 것입니다.", "적은 시간과 힘으로 많은 일을 하는 것입니다."], answer: 3,
        sourceUrl: "neungnyul.html", sourceTitle: "Efficiency" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n표본",
        options: ["품질을 확인하기 위해 미리 만든 제품입니다.", "포장 재료를 말합니다.", "불량품을 말합니다.", "완성된 모든 제품입니다."], answer: 0,
        sourceUrl: "sample_sijepum.html", sourceTitle: "Sample / Prototype" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"품질 개선 회의 안내: 매주 월요일 오전 10시에 실시합니다. 관련 부서는 모두 참석해 주세요.\"\n\n품질 개선 회의는 언제 합니까?",
        options: ["매일 오후", "매달 첫째 주", "금요일마다", "매주 월요일 오전 10시"], answer: 3,
        sourceUrl: "gongjeonggaeseon.html", sourceTitle: "Improvement" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n규격 확인 방법: _____________",
        options: ["줄자로 측정", "출근 시간", "생일 선물", "가족 모임"], answer: 0,
        sourceUrl: "gyugyeok.html", sourceTitle: "Standard / Specification" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n부품이 부족하면 ______ 담당자에게 알려야 합니다.",
        options: ["즉시로", "즉시하게", "즉시", "즉시히"], answer: 2,
        sourceUrl: "suryangbujok.html", sourceTitle: "Shortage of Quantity" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n기계를 점검할 때는 ______ 전원을 꺼야 합니다.",
        options: ["먼저는", "먼저", "먼저를", "먼저가"], answer: 1,
        sourceUrl: "jeomgeom.html", sourceTitle: "Checking / Inspection" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n포장이 끝나면 ______ 배송 준비를 합니다.",
        options: ["바로는", "바로가", "바로", "바로를"], answer: 2,
        sourceUrl: "chulha.html", sourceTitle: "Shipping Out" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n불량품을 발견하면 반장님께 ______",
        options: ["보고하지 않는 것이 좋습니다.", "보고해야 안 됩니다.", "보고하는 것이 좋습니다.", "보고할 수 없습니다."], answer: 2,
        sourceUrl: "gyoche.html", sourceTitle: "Replacement" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n무거운 자재를 옮길 때는 ______ 이렇게 하면 허리 부상을 막을 수 있습니다.",
        options: ["허리를 펴고 다리 힘으로 들어야 합니다.", "한 손으로 빨리 들어야 합니다.", "허리를 굽히고 팔 힘으로 들어야 합니다.", "숨을 참고 들어야 합니다."], answer: 0,
        sourceUrl: "bunhae.html", sourceTitle: "Disassembly" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n물건에 붙여서 제품 정보를 표시하는 종이나 스티커입니다.",
        options: ["줄자", "망치", "가위", "라벨"], answer: 3,
        sourceUrl: "rabelling.html", sourceTitle: "Labeling" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n공장에서는 매일 생산량을 기록하고 목표와 비교합니다. 목표에 미달하면 원인을 분석하고 개선 방법을 찾습니다. 이러한 과정을 통해 효율을 높일 수 있습니다.",
        options: ["휴가 신청 절차", "생산 관리와 개선", "급여 계산 방법", "직원 채용 방법"], answer: 1,
        sourceUrl: "jakdong.html", sourceTitle: "Operation" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"재고 관리 안내: 매주 금요일 재고를 확인하고 기록합니다. 부족한 자재는 다음 주 월요일까지 주문해야 합니다.\"",
        options: ["매주 금요일 재고를 확인합니다.", "재고는 확인하지 않습니다.", "부족한 자재는 주문할 필요가 없습니다.", "재고 관리는 한 달에 한 번 합니다."], answer: 0,
        sourceUrl: "gadong.html", sourceTitle: "Operation / Running" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"폐기물 처리 안내: 재활용 가능한 폐기물은 따로 분리해서 배출합니다. 일반 폐기물과 섞지 않도록 주의해 주세요.\"",
        options: ["재활용 가능한 폐기물은 따로 분리해서 배출합니다.", "폐기물은 아무 데나 버려도 됩니다.", "재활용은 하지 않아도 됩니다.", "모든 폐기물은 같이 버려도 됩니다."], answer: 0,
        sourceUrl: "jaehwalyong.html", sourceTitle: "Recycling" }
    ]
  },
  {
    id: "set_05",
    title: "EPS-TOPIK Mock Test #5",
    free: true,
    listening: [
      { id: "L01", audioText: "이거 뭐예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["일요일이에요.", "회사예요.", "빵이에요.", "친구예요."], answer: 2,
        sourceUrl: "bread.html", sourceTitle: "Bread" },
      { id: "L02", audioText: "무슨 계절을 좋아해요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["연필을 좋아해요.", "봄을 좋아해요.", "우산을 좋아해요.", "책상을 좋아해요."], answer: 1,
        sourceUrl: "spring.html", sourceTitle: "Spring" },
      { id: "L03", audioText: "가족이 몇 명이에요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["가방이에요.", "네 명이에요.", "교실이에요.", "월요일이에요."], answer: 1,
        sourceUrl: "family.html", sourceTitle: "Family" },
      { id: "L04", audioText: "오늘 뭐 먹었어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["일곱 시예요.", "친구를 만났어요.", "서울에 갔어요.", "김치찌개를 먹었어요."], answer: 3,
        sourceUrl: "soup.html", sourceTitle: "Soup" },
      { id: "L05", audioText: "취미가 뭐예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["운동이에요.", "가까워요.", "비싸요.", "월요일이에요."], answer: 0,
        sourceUrl: "hobbies.html", sourceTitle: "Hobbies" },
      { id: "L06", audioText: "남자: 외국인등록증 가지고 왔어요? 여자: 네, 여기 있어요.", question: "여자는 무엇을 가지고 왔습니까?",
        options: ["외국인등록증", "여권", "통장", "비자"], answer: 0,
        sourceUrl: "oegugindeungrokjeung.html", sourceTitle: "Alien Registration Card" },
      { id: "L07", audioText: "남자: 비자는 언제까지예요? 여자: 내년 3월까지예요.", question: "여자의 비자는 언제까지입니까?",
        options: ["내년 3월까지", "올해 12월까지", "다음 주까지", "이번 달까지"], answer: 0,
        sourceUrl: "bija.html", sourceTitle: "Visa" },
      { id: "L08", audioText: "남자: 체류 기간이 얼마나 남았어요? 여자: 두 달 남았어요.", question: "여자의 체류 기간은 얼마나 남았습니까?",
        options: ["일 년", "두 달", "한 달", "일주일"], answer: 1,
        sourceUrl: "cheryugigan.html", sourceTitle: "Period of Stay" },
      { id: "L09", audioText: "재입국 허가를 미리 신청해야 합니다.", question: "무엇을 미리 신청해야 합니까?",
        options: ["재입국 허가", "비자 연장", "외국인등록증", "건강보험"], answer: 0,
        sourceUrl: "jaeipguk.html", sourceTitle: "Re-entry" },
      { id: "L10", audioText: "고용센터에서 취업 상담을 받을 수 있습니다.", question: "고용센터에서 무엇을 받을 수 있습니까?",
        options: ["취업 상담", "비자 발급", "여권 발급", "건강 검진"], answer: 0,
        sourceUrl: "goyongcenter.html", sourceTitle: "Employment Center" },
      { id: "L11", audioText: "남자: 건강보험료가 얼마예요? 여자: 매달 오만원 정도예요.", question: "건강보험료는 얼마입니까?",
        options: ["매달 오천원", "매달 이십만원", "매달 십만원", "매달 오만원 정도"], answer: 3,
        sourceUrl: "gukmingeongangboheom.html", sourceTitle: "National Health Insurance" },
      { id: "L12", audioText: "이 도장을 서류에 찍어 주세요.", question: "서류에 무엇을 찍어야 합니까?",
        options: ["도장", "사진", "이름", "날짜"], answer: 0,
        sourceUrl: "dojang.html", sourceTitle: "Stamp / Seal" },
      { id: "L13", audioText: "남자: 오늘 환율이 얼마예요? 여자: 천이백 원 정도예요.", question: "오늘 환율은 얼마입니까?",
        options: ["이천 원", "천 원", "오백 원", "천이백 원 정도"], answer: 3,
        sourceUrl: "hwanyul.html", sourceTitle: "Exchange Rate" },
      { id: "L14", audioText: "남자: 고향에 돈을 보냈어요? 여자: 네, 어제 송금했어요.", question: "여자는 언제 송금했습니까?",
        options: ["어제", "내일", "오늘", "지난달"], answer: 0,
        sourceUrl: "songgeum.html", sourceTitle: "Money Transfer" },
      { id: "L15", audioText: "송금 수수료를 확인해 주세요.", question: "무엇을 확인해야 합니까?",
        options: ["생년월일", "주소", "송금 수수료", "전화번호"], answer: 2,
        sourceUrl: "susuryo.html", sourceTitle: "Fee" },
      { id: "L16", audioText: "남자: 재직증명서 발급받았어요? 여자: 네, 오늘 받았어요.", question: "여자는 무엇을 발급받았습니까?",
        options: ["재직증명서", "졸업증명서", "건강진단서", "비자"], answer: 0,
        sourceUrl: "jeungmyeongseo.html", sourceTitle: "Certificate" },
      { id: "L17", audioText: "서류 접수는 오전에만 가능합니다.", question: "서류 접수는 언제 가능합니까?",
        options: ["오후에만", "종일", "저녁에만", "오전에만"], answer: 3,
        sourceUrl: "jeopsu.html", sourceTitle: "Reception / Filing" },
      { id: "L18", audioText: "남자: 신청이 승인됐어요? 여자: 네, 어제 승인됐어요.", question: "신청은 언제 승인됐습니까?",
        options: ["어제", "다음 주", "내일", "오늘"], answer: 0,
        sourceUrl: "seungin.html", sourceTitle: "Approval" },
      { id: "L19", audioText: "남자: 서류에 동의 서명을 했어요? 여자: 네, 다 했어요.", question: "여자는 무엇을 했습니까?",
        options: ["동의 서명", "서류 제출", "비용 납부", "사진 촬영"], answer: 0,
        sourceUrl: "dongui.html", sourceTitle: "Consent / Agreement" },
      { id: "L20", audioText: "신분 확인을 위해 신분증을 보여 주세요.", question: "무엇을 보여 줘야 합니까?",
        options: ["통장", "신분증", "여권 사진", "계약서"], answer: 1,
        sourceUrl: "sinwon_hwagin.html", sourceTitle: "Identity Verification" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n하늘을 날아서 먼 나라로 이동할 때 타는 것입니다.",
        options: ["버스", "비행기", "기차", "배"], answer: 1,
        sourceUrl: "airplane.html", sourceTitle: "Airplane" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n비행기를 타고 내리는 곳입니다.",
        options: ["버스터미널", "기차역", "공항", "항구"], answer: 2,
        sourceUrl: "airport.html", sourceTitle: "Airport" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 부엌에서 채소를 썰고 있습니다.",
        options: ["요리를 하고 있습니다.", "잠을 자고 있습니다.", "청소를 하고 있습니다.", "운동을 하고 있습니다."], answer: 0,
        sourceUrl: "cooking.html", sourceTitle: "Cooking" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n파란 바탕에 흰색 화살표가 아래를 가리키는 표지판입니다.",
        options: ["이쪽으로 올라가세요.", "여기서 기다리세요.", "이쪽으로 내려가세요.", "여기서 멈추세요."], answer: 2,
        sourceUrl: "places.html", sourceTitle: "Places" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n이 서류___ 고용센터에 제출하세요.",
        options: ["서류도 고용센터에 제출하세요.", "서류가 고용센터에 제출하세요.", "서류에서 고용센터에 제출하세요.", "서류를 고용센터에 제출하세요."], answer: 3,
        sourceUrl: "goyongnodongbu.html", sourceTitle: "Ministry of Employment and Labor" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n서류를 제출하기 전에 내용을 ______.",
        options: ["확인해서요.", "확인하요.", "확인했요.", "확인해요."], answer: 3,
        sourceUrl: "eoryu.html", sourceTitle: "Documents" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"고용센터 운영 시간: 평일 오전 9시 ~ 오후 6시 (주말 휴무)\"\n\n고용센터는 언제까지 운영합니까?",
        options: ["오후 9시", "오전 9시", "오후 6시", "오전 6시"], answer: 2,
        sourceUrl: "goyongboheom.html", sourceTitle: "Employment Insurance" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n국민연금",
        options: ["회사에서 주는 보너스입니다.", "나이가 들면 받는 연금 제도입니다.", "병원비 지원 제도입니다.", "매달 내는 세금입니다."], answer: 1,
        sourceUrl: "gukminyeongeum.html", sourceTitle: "National Pension" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n산업재해",
        options: ["월급이 늦게 나오는 것입니다.", "일을 하다가 다치거나 병에 걸리는 것입니다.", "휴가를 못 가는 것입니다.", "계약이 끝나는 것입니다."], answer: 1,
        sourceUrl: "saneupjaehae.html", sourceTitle: "Industrial Accident" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"서류 접수 안내: 신청서는 이메일 또는 방문으로 접수할 수 있습니다. 접수 마감일은 이번 달 30일입니다.\"\n\n접수 마감일은 언제입니까?",
        options: ["다음 달 1일", "다음 달 30일", "이번 달 30일", "이번 달 1일"], answer: 2,
        sourceUrl: "geojeol.html", sourceTitle: "Rejection" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n지급 방법: _____________",
        options: ["현금 지급", "생일 선물", "출근 시간", "가족 모임"], answer: 0,
        sourceUrl: "money.html", sourceTitle: "Money" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n공항에 도착하면 ______ 짐을 찾아야 합니다.",
        options: ["먼저", "먼저는", "먼저가", "먼저를"], answer: 0,
        sourceUrl: "travel.html", sourceTitle: "Travel" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n장을 볼 때는 ______ 영수증을 받아야 합니다.",
        options: ["꼭이", "꼭은", "꼭", "꼭도"], answer: 2,
        sourceUrl: "market.html", sourceTitle: "Market" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n이사할 집을 구할 때는 ______ 여러 곳을 비교해 봐야 합니다.",
        options: ["미리", "미리가", "미리는", "미리도"], answer: 0,
        sourceUrl: "house.html", sourceTitle: "House" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n몸이 아프면 참지 말고 병원에 ______",
        options: ["갈 수 없습니다.", "가야 안 됩니다.", "가지 않는 것이 좋습니다.", "가는 것이 좋습니다."], answer: 3,
        sourceUrl: "health.html", sourceTitle: "Health" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n고향 가족에게 안부를 전할 때는 ______ 이렇게 하면 마음이 편안해집니다.",
        options: ["걱정하지 않아도 됩니다.", "답장을 안 해도 됩니다.", "전화를 자주 하는 것이 좋습니다.", "연락을 끊는 것이 좋습니다."], answer: 2,
        sourceUrl: "parents.html", sourceTitle: "Parents" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n여러 가지 채소와 고기를 넣고 매운 양념으로 볶은 한국 음식입니다.",
        options: ["김밥", "불고기", "비빔밥", "떡볶이"], answer: 3,
        sourceUrl: "tteokbokki.html", sourceTitle: "Tteokbokki" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n한국은 봄, 여름, 가을, 겨울 네 계절이 뚜렷합니다. 봄에는 꽃이 피고, 여름에는 덥고 습합니다. 가을에는 단풍이 들고, 겨울에는 눈이 옵니다.",
        options: ["한국의 교통수단", "한국의 직장 문화", "한국의 음식 문화", "한국의 사계절"], answer: 3,
        sourceUrl: "autumn.html", sourceTitle: "Autumn" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"편의점 이용 안내: 24시간 운영하며, 간단한 식사와 생필품을 구매할 수 있습니다. 교통카드 충전도 가능합니다.\"",
        options: ["편의점에서는 식사를 살 수 없습니다.", "편의점은 오전에만 운영합니다.", "교통카드 충전은 불가능합니다.", "편의점은 24시간 운영합니다."], answer: 3,
        sourceUrl: "store.html", sourceTitle: "Store" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"대중교통 이용 안내: 교통카드를 사용하면 버스와 지하철을 환승할 때 할인을 받을 수 있습니다. 현금 결제 시에는 환승 할인이 적용되지 않습니다.\"",
        options: ["교통카드를 사용하면 환승 할인을 받을 수 있습니다.", "현금으로 내도 환승 할인을 받습니다.", "환승 할인은 항상 적용됩니다.", "교통카드는 지하철에서만 사용할 수 있습니다."], answer: 0,
        sourceUrl: "commute.html", sourceTitle: "Commute" }
    ]
  },
  {
    id: "set_06",
    title: "EPS-TOPIK Mock Test #6",
    free: true,
    listening: [
      { id: "L01", audioText: "몸이 어디가 아파요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["비싸요.", "회사예요.", "머리가 아파요.", "늦었어요."], answer: 2,
        sourceUrl: "meorigaapayo1.html", sourceTitle: "My Head Hurts" },
      { id: "L02", audioText: "열이 나요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 열이 나요.", "아니요, 배고파요.", "아니요, 늦었어요.", "네, 비싸요."], answer: 0,
        sourceUrl: "yeorinayo1.html", sourceTitle: "I Have a Fever" },
      { id: "L03", audioText: "무슨 일이에요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["늦었어요.", "가까워요.", "비싸요.", "사고가 났어요."], answer: 3,
        sourceUrl: "museunirieyo1.html", sourceTitle: "What Happened?" },
      { id: "L04", audioText: "도움이 필요해요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 비싸요.", "아니요, 맛있어요.", "아니요, 가까워요.", "네, 도움이 필요해요."], answer: 3,
        sourceUrl: "doumipilyohaeyo1.html", sourceTitle: "I Need Help" },
      { id: "L05", audioText: "이쪽으로 가면 돼요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 비싸요.", "네, 이쪽으로 가세요.", "아니요, 늦었어요.", "네, 맛있어요."], answer: 1,
        sourceUrl: "ttaraoseyo1.html", sourceTitle: "Follow Me" },
      { id: "L06", audioText: "남자: 작업 중 손을 베였어요. 여자: 빨리 응급실로 가세요.", question: "남자에게 무슨 일이 있었습니까?",
        options: ["넘어졌다", "감전됐다", "화상을 입었다", "손을 다쳤다"], answer: 3,
        sourceUrl: "yeolsang.html", sourceTitle: "Laceration / Cut" },
      { id: "L07", audioText: "남자: 뜨거운 물에 손을 데었어요. 여자: 찬물로 식히세요.", question: "여자는 남자에게 무엇을 하라고 했습니까?",
        options: ["병원에 가기", "약을 바르기", "찬물로 식히기", "붕대를 감기"], answer: 2,
        sourceUrl: "hwasang.html", sourceTitle: "Burn" },
      { id: "L08", audioText: "높은 곳에서 작업할 때는 안전벨트를 착용하세요.", question: "높은 곳에서 작업할 때 무엇을 착용해야 합니까?",
        options: ["모자", "마스크", "장갑", "안전벨트"], answer: 3,
        sourceUrl: "anjeondae.html", sourceTitle: "Safety Harness" },
      { id: "L09", audioText: "남자: 바닥이 미끄러워요. 조심하세요. 여자: 네, 알겠습니다.", question: "남자는 여자에게 무엇을 조심하라고 했습니까?",
        options: ["뜨거운 물건", "미끄러운 바닥", "날카로운 도구", "무거운 짐"], answer: 1,
        sourceUrl: "jeondo.html", sourceTitle: "Slip / Trip" },
      { id: "L10", audioText: "이 기계에 손이 끼이지 않도록 조심하세요.", question: "무엇을 조심해야 합니까?",
        options: ["기계 소리가 큰 것", "손이 기계에 끼이는 것", "기계가 뜨거운 것", "기계가 넘어지는 것"], answer: 1,
        sourceUrl: "hyeopchak.html", sourceTitle: "Jamming / Pinched" },
      { id: "L11", audioText: "가스 누출 경보음이 울리면 즉시 대피하세요.", question: "경보음이 울리면 어떻게 해야 합니까?",
        options: ["창문을 닫는다", "기계를 켠다", "즉시 대피한다", "계속 일한다"], answer: 2,
        sourceUrl: "gyeongbogi.html", sourceTitle: "Alarm" },
      { id: "L12", audioText: "이 마스크는 먼지가 많은 곳에서 착용하세요.", question: "이 마스크는 언제 착용해야 합니까?",
        options: ["비가 올 때", "더울 때", "먼지가 많을 때", "추울 때"], answer: 2,
        sourceUrl: "bangjinmaseukeu.html", sourceTitle: "Dust Mask" },
      { id: "L13", audioText: "남자: 여기 차단기가 내려갔어요. 여자: 제가 올릴게요.", question: "여자는 무엇을 하려고 합니까?",
        options: ["기계를 끄기", "전등을 켜기", "문을 열기", "차단기를 올리기"], answer: 3,
        sourceUrl: "chadangi.html", sourceTitle: "Circuit Breaker" },
      { id: "L14", audioText: "전선을 만지기 전에 접지 상태를 확인하세요.", question: "전선을 만지기 전에 무엇을 확인해야 합니까?",
        options: ["접지 상태", "전선 길이", "전선 색깔", "전선 무게"], answer: 0,
        sourceUrl: "jeopji.html", sourceTitle: "Grounding / Earthing" },
      { id: "L15", audioText: "이 구역은 물기가 있으니 사용하지 마세요.", question: "이 구역에서 무엇을 하지 말아야 합니까?",
        options: ["휴식", "전기 기구 사용", "이동", "대화"], answer: 1,
        sourceUrl: "mulgi_eomgeum.html", sourceTitle: "Keep Away from Water" },
      { id: "L16", audioText: "화재 시 소화전 위치를 미리 확인해 두세요.", question: "화재 시 무엇을 미리 확인해야 합니까?",
        options: ["경보음 크기", "소화기 무게", "비상구 색깔", "소화전 위치"], answer: 3,
        sourceUrl: "sohwajeon.html", sourceTitle: "Fire Hydrant" },
      { id: "L17", audioText: "이 구역은 차량 출입을 금지합니다.", question: "이 구역에서 금지하는 것은 무엇입니까?",
        options: ["휴식", "보행", "차량 출입", "대화"], answer: 2,
        sourceUrl: "tapseunggeumji.html", sourceTitle: "No Riding" },
      { id: "L18", audioText: "인화물질 근처에서는 불을 사용하지 마세요.", question: "인화물질 근처에서 하지 말아야 할 것은 무엇입니까?",
        options: ["휴식", "이동", "대화", "불 사용"], answer: 3,
        sourceUrl: "hwagi_eomgeum.html", sourceTitle: "No Flammable Materials" },
      { id: "L19", audioText: "작업장은 항상 깨끗하게 정리 정돈하세요.", question: "작업장을 어떻게 유지해야 합니까?",
        options: ["물건을 쌓아 두게", "최대한 어둡게", "좁게", "깨끗하게 정리 정돈"], answer: 3,
        sourceUrl: "jeongrijeongdon.html", sourceTitle: "Tidying Up" },
      { id: "L20", audioText: "환기가 잘 안 되는 곳에서는 마스크를 착용하세요.", question: "환기가 잘 안 되는 곳에서 무엇을 착용해야 합니까?",
        options: ["안전화", "마스크", "장갑", "모자"], answer: 1,
        sourceUrl: "hwangi.html", sourceTitle: "Ventilation" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n작은 철사나 전선을 자를 때 쓰는 도구입니다.",
        options: ["가위", "망치", "니퍼", "펜치"], answer: 2,
        sourceUrl: "nipeo.html", sourceTitle: "Nippers" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n바닥이나 벽이 수평인지 확인할 때 쓰는 도구입니다.",
        options: ["저울", "줄자", "수평계", "온도계"], answer: 2,
        sourceUrl: "supyeongdae.html", sourceTitle: "Spirit Level" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 바닥에 쓰러져서 움직이지 않습니다.",
        options: ["잠을 자고 있습니다.", "의식을 잃었습니다.", "일을 하고 있습니다.", "운동을 하고 있습니다."], answer: 1,
        sourceUrl: "honsu_gijeol.html", sourceTitle: "Fainting / Unconsciousness" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n빨간 바탕에 금지 표시가 그려진 표지판입니다.",
        options: ["이곳은 쉬는 곳입니다.", "이곳은 자유롭게 다닐 수 있습니다.", "이곳은 출입을 금지합니다.", "이곳은 식사하는 곳입니다."], answer: 2,
        sourceUrl: "geumji.html", sourceTitle: "Prohibition" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n다친 사람___ 병원에 데려갔어요.",
        options: ["다친 사람도 병원에 데려갔어요.", "다친 사람이 병원에 데려갔어요.", "다친 사람을 병원에 데려갔어요.", "다친 사람에서 병원에 데려갔어요."], answer: 2,
        sourceUrl: "sangcheo.html", sourceTitle: "Wound" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n다치면 바로 병원에 ______.",
        options: ["가여요.", "가요.", "갔요.", "가아요."], answer: 1,
        sourceUrl: "goljeol.html", sourceTitle: "Fracture" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"소화기 점검 안내: 매달 첫째 주 월요일에 점검합니다. 이상이 있으면 관리자에게 알려 주세요.\"\n\n소화기는 언제 점검합니까?",
        options: ["매주 금요일", "매일 아침", "매달 첫째 주 월요일", "분기별 1회"], answer: 2,
        sourceUrl: "jeongbi.html", sourceTitle: "Maintenance" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n소독",
        options: ["월급을 계산하는 것입니다.", "상처나 물건을 깨끗하게 하는 것입니다.", "휴가를 신청하는 것입니다.", "물건을 포장하는 것입니다."], answer: 1,
        sourceUrl: "sodok.html", sourceTitle: "Disinfection" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n누전",
        options: ["전기가 새어 나오는 것입니다.", "소리가 새는 것입니다.", "물이 새는 것입니다.", "가스가 새는 것입니다."], answer: 0,
        sourceUrl: "nujeon.html", sourceTitle: "Electricity Leakage" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"대피소 이용 안내: 비상시 3층 대피소로 이동하세요. 엘리베이터는 사용하지 마세요.\"\n\n비상시 어디로 이동해야 합니까?",
        options: ["지하 주차장", "옥상", "3층 대피소", "1층 로비"], answer: 2,
        sourceUrl: "daepiso.html", sourceTitle: "Shelter" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n사고 원인: _____________",
        options: ["합선", "생일 선물", "가족 모임", "출근 시간"], answer: 0,
        sourceUrl: "hapseon.html", sourceTitle: "Short Circuit" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n화학물질을 다룰 때는 ______ 환기를 시켜야 합니다.",
        options: ["반드시도", "반드시는", "반드시", "반드시가"], answer: 2,
        sourceUrl: "inhwasung.html", sourceTitle: "Flammability" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n부식성 물질은 ______ 다뤄야 합니다.",
        options: ["조심스럽게", "조심스러움", "조심스러운", "조심"], answer: 0,
        sourceUrl: "busiksung.html", sourceTitle: "Corrosiveness" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n작업장에서는 ______ 정리 정돈을 해야 합니다.",
        options: ["항상이", "항상도", "항상", "항상은"], answer: 2,
        sourceUrl: "cheongso.html", sourceTitle: "Cleaning" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n독성 물질을 마셨을 때는 즉시 ______",
        options: ["집에서 쉬어야 합니다.", "병원에 가야 합니다.", "그냥 두어야 합니다.", "물을 안 마셔야 합니다."], answer: 1,
        sourceUrl: "jungdok.html", sourceTitle: "Poisoning / Intoxication" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n폭발 위험이 있는 구역에서는 ______ 이렇게 하면 큰 사고를 막을 수 있습니다.",
        options: ["화기를 사용하면 안 됩니다.", "담배를 피워도 됩니다.", "불을 켜도 됩니다.", "라이터를 사용해도 됩니다."], answer: 0,
        sourceUrl: "pokbal.html", sourceTitle: "Explosion" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n숨을 쉬기 어려운 상태로, 산소가 부족할 때 나타납니다.",
        options: ["구토", "질식", "어지러움", "기절"], answer: 1,
        sourceUrl: "jilsik.html", sourceTitle: "Suffocation" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n작업 중 사고가 발생하면 당황하지 말고 먼저 안전한 곳으로 이동해야 합니다. 그 다음 관리자에게 알리고, 필요하면 119에 신고해야 합니다.",
        options: ["월급 계산 방법", "제품 포장 방법", "휴가 신청 절차", "사고 발생 시 대처 방법"], answer: 3,
        sourceUrl: "chungdol.html", sourceTitle: "Collision" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"화상 응급처치 안내: 화상을 입으면 먼저 찬물로 식히고, 물집을 터뜨리지 마세요. 심하면 병원에 가야 합니다.\"",
        options: ["물집은 바로 터뜨려야 합니다.", "화상을 입으면 뜨거운 물로 식혀야 합니다.", "화상은 병원에 갈 필요가 없습니다.", "화상을 입으면 찬물로 식혀야 합니다."], answer: 3,
        sourceUrl: "banchanggo.html", sourceTitle: "Adhesive Plaster" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"어지러움 증상 대처 안내: 어지러우면 즉시 앉거나 누워서 쉬어야 합니다. 증상이 계속되면 관리자에게 알려야 합니다.\"",
        options: ["어지러워도 계속 일해야 합니다.", "어지러우면 뛰어야 합니다.", "어지러움은 신경 쓰지 않아도 됩니다.", "어지러우면 즉시 앉거나 누워서 쉬어야 합니다."], answer: 3,
        sourceUrl: "guto.html", sourceTitle: "Vomiting" }
    ]
  },
  {
    id: "set_07",
    title: "EPS-TOPIK Mock Test #7",
    free: true,
    listening: [
      { id: "L01", audioText: "만나서 반가워요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["저도 반가워요.", "비싸요.", "가까워요.", "늦었어요."], answer: 0,
        sourceUrl: "bangawoyo1.html", sourceTitle: "Nice to Meet You" },
      { id: "L02", audioText: "한국어 공부해요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 한국어를 배우고 있어요.", "아니요, 늦었어요.", "네, 비싸요.", "아니요, 멀어요."], answer: 0,
        sourceUrl: "hangukeo1.html", sourceTitle: "I'm Learning Korean" },
      { id: "L03", audioText: "이거 어디에 있어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["맛있어요.", "비싸요.", "저기 있어요.", "늦었어요."], answer: 2,
        sourceUrl: "eodi1.html", sourceTitle: "Where Is It" },
      { id: "L04", audioText: "행복해요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 배고파요.", "아니요, 늦었어요.", "네, 행복해요.", "네, 비싸요."], answer: 2,
        sourceUrl: "haengbok1.html", sourceTitle: "Im Happy" },
      { id: "L05", audioText: "무섭지 않아요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["비싸요.", "맛있어요.", "가까워요.", "조금 무서워요."], answer: 3,
        sourceUrl: "museowo1.html", sourceTitle: "Im Scared" },
      { id: "L06", audioText: "남자: 이번에 재계약 하실 거예요? 여자: 네, 계속 일하고 싶어요.", question: "여자는 무엇을 하고 싶어합니까?",
        options: ["그만두기", "이직하기", "휴직하기", "재계약하고 계속 일하기"], answer: 3,
        sourceUrl: "jaegyeyak.html", sourceTitle: "Re-contract / Renewal" },
      { id: "L07", audioText: "남자: 수습 기간이 언제 끝나요? 여자: 다음 달에 끝나요.", question: "여자의 수습 기간은 언제 끝납니까?",
        options: ["내년", "다음 달", "다음 주", "이번 달"], answer: 1,
        sourceUrl: "suseupgigan.html", sourceTitle: "Probationary Period" },
      { id: "L08", audioText: "우리 회사 근로 시간은 오전 9시부터 오후 6시까지입니다.", question: "근로 시간은 몇 시부터 몇 시까지입니까?",
        options: ["오전 10시~오후 7시", "오전 8시~오후 5시", "오전 9시~오후 6시", "오전 7시~오후 4시"], answer: 2,
        sourceUrl: "geunrosigan.html", sourceTitle: "Working Hours" },
      { id: "L09", audioText: "남자: 이번 달 월차 썼어요? 여자: 네, 지난주에 썼어요.", question: "여자는 언제 월차를 썼습니까?",
        options: ["이번 주", "오늘", "지난주", "다음 주"], answer: 2,
        sourceUrl: "wolcha.html", sourceTitle: "Monthly Leave" },
      { id: "L10", audioText: "남자: 오늘 조퇴하고 싶어요. 여자: 무슨 일이에요?", question: "남자는 오늘 무엇을 하고 싶어합니까?",
        options: ["출장가기", "야근하기", "조퇴하기", "휴가가기"], answer: 2,
        sourceUrl: "jotoe.html", sourceTitle: "Leaving Early" },
      { id: "L11", audioText: "어제 결근한 이유가 뭐예요?", question: "무엇에 대해 묻고 있습니까?",
        options: ["조퇴 이유", "휴가 이유", "결근 이유", "지각 이유"], answer: 2,
        sourceUrl: "gyeolgeun.html", sourceTitle: "Absence" },
      { id: "L12", audioText: "이번 주는 특근이 있습니다.", question: "이번 주에 무엇이 있습니까?",
        options: ["특근", "휴가", "회식", "교육"], answer: 0,
        sourceUrl: "teukgeun.html", sourceTitle: "Special Shift Work" },
      { id: "L13", audioText: "남자: 몇 시에 퇴근해요? 여자: 6시에 퇴근해요.", question: "여자는 몇 시에 퇴근합니까?",
        options: ["7시", "5시", "8시", "6시"], answer: 3,
        sourceUrl: "toegeun.html", sourceTitle: "Leave Work" },
      { id: "L14", audioText: "기본급 외에 수당이 추가로 지급됩니다.", question: "기본급 외에 무엇이 추가로 지급됩니까?",
        options: ["보험료", "수당", "식비", "세금"], answer: 1,
        sourceUrl: "gibongeup.html", sourceTitle: "Base Pay" },
      { id: "L15", audioText: "이번 달 월급에서 세금이 공제되었습니다.", question: "이번 달 월급에서 무엇이 공제되었습니까?",
        options: ["수당", "상여금", "식비", "세금"], answer: 3,
        sourceUrl: "gongje.html", sourceTitle: "Deduction" },
      { id: "L16", audioText: "남자: 실수령액이 얼마예요? 여자: 이백오십만 원 정도예요.", question: "여자의 실수령액은 얼마입니까?",
        options: ["삼백만 원", "이백오십만 원 정도", "이백만 원", "백오십만 원"], answer: 1,
        sourceUrl: "silsuryeongae.html", sourceTitle: "Net Pay" },
      { id: "L17", audioText: "퇴직금은 근무 기간에 따라 계산됩니다.", question: "퇴직금은 무엇에 따라 계산됩니까?",
        options: ["근무 기간", "직급", "학력", "나이"], answer: 0,
        sourceUrl: "toejikgeum.html", sourceTitle: "Severance Pay" },
      { id: "L18", audioText: "남자: 그 사람 해고됐어요? 여자: 네, 지난주에 해고됐어요.", question: "그 사람은 언제 해고됐습니까?",
        options: ["다음 주", "이번 주", "지난주", "어제"], answer: 2,
        sourceUrl: "haego.html", sourceTitle: "Dismissal / Firing" },
      { id: "L19", audioText: "제 동료가 오늘 처음 출근했어요.", question: "동료는 오늘 무엇을 했습니까?",
        options: ["퇴사했다", "출장을 갔다", "휴가를 갔다", "처음 출근했다"], answer: 3,
        sourceUrl: "dongryo.html", sourceTitle: "Co-worker" },
      { id: "L20", audioText: "우리 부서는 2교대 근무를 합니다.", question: "우리 부서는 어떤 근무를 합니까?",
        options: ["야간 근무만", "주간 근무만", "3교대 근무", "2교대 근무"], answer: 3,
        sourceUrl: "gyodae-geunmu.html", sourceTitle: "Shift Work" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n회사에서 가장 높은 직급으로, 회사를 대표하는 사람입니다.",
        options: ["사장", "팀장", "반장", "동료"], answer: 0,
        sourceUrl: "sajang.html", sourceTitle: "President" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n나를 고용해서 월급을 주는 사람이나 회사입니다.",
        options: ["근로자", "고객", "사업주", "동료"], answer: 2,
        sourceUrl: "saeopju.html", sourceTitle: "Employer" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 책상에 앉아서 계산기를 두드리며 서류를 보고 있습니다.",
        options: ["요리를 하고 있습니다.", "운동을 하고 있습니다.", "잠을 자고 있습니다.", "계산을 하고 있습니다."], answer: 3,
        sourceUrl: "desk.html", sourceTitle: "Desk" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n파란 바탕에 시계 모양이 그려진 표지판입니다.",
        options: ["출입구 위치입니다.", "화장실 위치입니다.", "근무 시간을 확인하세요.", "식당 위치입니다."], answer: 2,
        sourceUrl: "time.html", sourceTitle: "Time" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n이번 달 월급___ 통장으로 들어왔어요.",
        options: ["월급에서 통장으로 들어왔어요.", "월급이 통장으로 들어왔어요.", "월급을 통장으로 들어왔어요.", "월급도 통장으로 들어왔어요."], answer: 1,
        sourceUrl: "cash.html", sourceTitle: "Cash" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n매달 월급날을 손꼽아 ______.",
        options: ["기다려요.", "기다리요.", "기다렸요.", "기다려서요."], answer: 0,
        sourceUrl: "today.html", sourceTitle: "Today" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"근로계약 갱신 안내: 계약 만료 한 달 전에 갱신 여부를 알려 드립니다. 계속 근무를 원하시면 서명해 주세요.\"\n\n계약 만료 언제 전에 갱신 여부를 알려줍니까?",
        options: ["일주일 전", "하루 전", "한 달 전", "3개월 전"], answer: 2,
        sourceUrl: "study.html", sourceTitle: "Study" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n수업",
        options: ["휴가를 가는 것입니다.", "계약을 맺는 것입니다.", "일정한 시간에 배우는 것입니다.", "월급을 받는 것입니다."], answer: 2,
        sourceUrl: "class.html", sourceTitle: "Class" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n학생",
        options: ["학교에서 공부하는 사람입니다.", "음식을 요리하는 사람입니다.", "회사에서 일하는 사람입니다.", "환자를 진료하는 사람입니다."], answer: 0,
        sourceUrl: "student.html", sourceTitle: "Student" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"시험 결과 안내: 시험 결과는 시험 다음 날 오후에 게시판에 공지됩니다. 궁금한 점은 담당자에게 문의하세요.\"\n\n시험 결과는 언제 공지됩니까?",
        options: ["시험 당일", "일주일 후", "한 달 후", "시험 다음 날 오후"], answer: 3,
        sourceUrl: "exam.html", sourceTitle: "Exam" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n근무 형태: _____________",
        options: ["2교대 근무", "출근 시간", "생일 선물", "가족 모임"], answer: 0,
        sourceUrl: "jobs.html", sourceTitle: "Jobs" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n동료가 힘들어 보이면 ______ 도와줘야 합니다.",
        options: ["먼저", "먼저는", "먼저가", "먼저를"], answer: 0,
        sourceUrl: "homework.html", sourceTitle: "Homework" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n새로운 일을 시작할 때는 ______ 배워야 합니다.",
        options: ["차근차근은", "차근차근이", "차근차근", "차근차근도"], answer: 2,
        sourceUrl: "joy.html", sourceTitle: "Joy" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n회사 규칙은 ______ 지켜야 합니다.",
        options: ["항상도", "항상이", "항상", "항상은"], answer: 2,
        sourceUrl: "school.html", sourceTitle: "School" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n일이 힘들면 참지 말고 동료에게 ______",
        options: ["이야기할 수 없습니다.", "이야기하지 않는 것이 좋습니다.", "이야기해야 안 됩니다.", "이야기하는 것이 좋습니다."], answer: 3,
        sourceUrl: "sadness.html", sourceTitle: "Sadness" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n새 직장에 적응하기 어려우면 ______ 이렇게 하면 도움이 됩니다.",
        options: ["아무것도 안 하는 것이 좋습니다.", "혼자 참는 것이 좋습니다.", "그만두는 것이 좋습니다.", "선배에게 물어보는 것이 좋습니다."], answer: 3,
        sourceUrl: "teacher.html", sourceTitle: "Teacher" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n일한 대가로 정기적으로 받는 돈입니다.",
        options: ["선물", "세금", "벌금", "월급"], answer: 3,
        sourceUrl: "economy.html", sourceTitle: "Economy" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n새로운 직장에 들어가면 처음에는 낯설고 어렵게 느껴질 수 있습니다. 하지만 선배들에게 물어보고 규칙을 잘 익히면 점점 익숙해집니다. 동료들과 좋은 관계를 유지하는 것도 중요합니다.",
        options: ["월급 계산 방법", "휴가 신청 절차", "제품 포장 방법", "새 직장 적응 방법"], answer: 3,
        sourceUrl: "vocabulary.html", sourceTitle: "Vocabulary" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"연차 사용 안내: 연차는 입사 1년 후부터 사용할 수 있습니다. 사용하지 않은 연차는 수당으로 지급됩니다.\"",
        options: ["연차는 입사 1년 후부터 사용할 수 있습니다.", "사용하지 않은 연차는 사라집니다.", "연차는 입사 즉시 사용할 수 있습니다.", "연차는 수당으로 바꿀 수 없습니다."], answer: 0,
        sourceUrl: "tomorrow.html", sourceTitle: "Tomorrow" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"교대 근무 안내: 주간조와 야간조가 일주일마다 교대합니다. 교대 전날에는 미리 인수인계를 해야 합니다.\"",
        options: ["주간조와 야간조가 일주일마다 교대합니다.", "교대는 한 달에 한 번입니다.", "야간조는 없습니다.", "인수인계는 필요 없습니다."], answer: 0,
        sourceUrl: "word.html", sourceTitle: "Word" }
    ]
  },
  {
    id: "set_08",
    title: "EPS-TOPIK Mock Test #8",
    free: true,
    listening: [
      { id: "L01", audioText: "비빔밥 좋아해요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 좋아해요.", "아니요, 멀어요.", "아니요, 늦었어요.", "네, 비싸요."], answer: 0,
        sourceUrl: "bibimbap.html", sourceTitle: "Bibimbap" },
      { id: "L02", audioText: "김치 매워요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 매워요.", "아니요, 배고파요.", "아니요, 늦었어요.", "네, 비싸요."], answer: 0,
        sourceUrl: "kimchi1.html", sourceTitle: "Kimchi" },
      { id: "L03", audioText: "오늘 점심 뭐 먹었어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["친구를 만났어요.", "서울에 갔어요.", "일곱 시예요.", "삼겹살을 먹었어요."], answer: 3,
        sourceUrl: "samgyeopsal.html", sourceTitle: "Samgyeopsal" },
      { id: "L04", audioText: "라면 끓일 줄 알아요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 늦었어요.", "아니요, 멀어요.", "네, 끓일 줄 알아요.", "네, 비싸요."], answer: 2,
        sourceUrl: "ramen.html", sourceTitle: "Ramen" },
      { id: "L05", audioText: "불고기 만들 수 있어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 늦었어요.", "네, 비싸요.", "네, 만들 수 있어요.", "아니요, 배고파요."], answer: 2,
        sourceUrl: "bulgogi.html", sourceTitle: "Bulgogi" },
      { id: "L06", audioText: "남자: 오늘 날씨 어때요? 여자: 비가 많이 와요.", question: "오늘 날씨는 어떻습니까?",
        options: ["비가 많이 온다", "바람이 분다", "맑다", "눈이 온다"], answer: 0,
        sourceUrl: "rain.html", sourceTitle: "Rain" },
      { id: "L07", audioText: "여름에는 날씨가 덥고 습합니다.", question: "여름 날씨는 어떻습니까?",
        options: ["눈이 온다", "시원하다", "덥고 습하다", "춥고 건조하다"], answer: 2,
        sourceUrl: "summer.html", sourceTitle: "Summer" },
      { id: "L08", audioText: "겨울에는 눈이 많이 옵니다.", question: "겨울에는 무엇이 많이 옵니까?",
        options: ["바람", "안개", "비", "눈"], answer: 3,
        sourceUrl: "snow.html", sourceTitle: "Snow" },
      { id: "L09", audioText: "남자: 오늘 기분이 안 좋아 보여요. 여자: 네, 조금 슬퍼요.", question: "여자는 오늘 기분이 어떻습니까?",
        options: ["슬프다", "무섭다", "기쁘다", "화난다"], answer: 0,
        sourceUrl: "seulpeo1.html", sourceTitle: "Im Sad" },
      { id: "L10", audioText: "왜 화가 났어요?", question: "무엇을 묻고 있습니까?",
        options: ["슬픈 이유", "화난 이유", "무서운 이유", "기쁜 이유"], answer: 1,
        sourceUrl: "hwana1.html", sourceTitle: "Im Angry" },
      { id: "L11", audioText: "고향 가족이 많이 보고 싶어요.", question: "무엇을 말하고 있습니까?",
        options: ["가족이 화났다", "가족이 무섭다", "가족이 그립다", "가족이 밉다"], answer: 2,
        sourceUrl: "bogosipeo1.html", sourceTitle: "I Miss You" },
      { id: "L12", audioText: "새로운 일을 시작할 때 긴장돼요.", question: "새로운 일을 시작할 때 기분이 어떻습니까?",
        options: ["편안하다", "지루하다", "긴장된다", "즐겁다"], answer: 2,
        sourceUrl: "ginjang1.html", sourceTitle: "Im Nervous" },
      { id: "L13", audioText: "너무 걱정하지 마세요.", question: "무엇을 하지 말라고 했습니까?",
        options: ["쉬기", "걱정하기", "먹기", "웃기"], answer: 1,
        sourceUrl: "geokjeong1.html", sourceTitle: "Don't Worry" },
      { id: "L14", audioText: "남자: 이 음식 좋아해요? 여자: 네, 정말 좋아해요.", question: "여자는 이 음식을 어떻게 생각합니까?",
        options: ["좋아한다", "싫어한다", "무섭다", "모른다"], answer: 0,
        sourceUrl: "joayo1.html", sourceTitle: "I Like It" },
      { id: "L15", audioText: "저는 매운 음식을 싫어해요.", question: "무엇을 싫어합니까?",
        options: ["신 음식", "매운 음식", "단 음식", "짠 음식"], answer: 1,
        sourceUrl: "anjoa1.html", sourceTitle: "I Don't Like It" },
      { id: "L16", audioText: "이 노래 정말 좋아요.", question: "무엇에 대해 말하고 있습니까?",
        options: ["노래가 좋다", "노래를 모른다", "노래가 어렵다", "노래가 싫다"], answer: 0,
        sourceUrl: "jeongmal1.html", sourceTitle: "I Love It" },
      { id: "L17", audioText: "저는 벌레를 정말 싫어해요.", question: "무엇을 싫어합니까?",
        options: ["벌레", "음식", "꽃", "동물"], answer: 0,
        sourceUrl: "sireo1.html", sourceTitle: "I Hate It" },
      { id: "L18", audioText: "남자: 준비 다 됐어요? 여자: 네, 준비 됐어요.", question: "여자는 무엇을 했습니까?",
        options: ["잊어버렸다", "아직 못 했다", "준비를 마쳤다", "포기했다"], answer: 2,
        sourceUrl: "junbi1.html", sourceTitle: "Im Ready" },
      { id: "L19", audioText: "아직 다 안 끝났어요.", question: "무엇에 대해 말하고 있습니까?",
        options: ["일을 안 했다", "일이 아직 안 끝났다", "일을 취소했다", "일이 다 끝났다"], answer: 1,
        sourceUrl: "ajig1.html", sourceTitle: "Not Yet" },
      { id: "L20", audioText: "잠깐만 기다려 주세요.", question: "무엇을 부탁했습니까?",
        options: ["전화하기", "기다리기", "빨리 오기", "떠나기"], answer: 1,
        sourceUrl: "gidaryeo1.html", sourceTitle: "Please Wait" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n둥글고 빨간색이나 초록색을 띠는 새콤달콤한 과일입니다.",
        options: ["포도", "수박", "사과", "바나나"], answer: 2,
        sourceUrl: "apple.html", sourceTitle: "Apple" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n물에서 헤엄치며 사는 동물로, 요리해서 먹기도 합니다.",
        options: ["돼지", "닭", "생선", "소"], answer: 2,
        sourceUrl: "fish.html", sourceTitle: "Fish" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 꽃밭에서 꽃 사진을 찍고 있습니다.",
        options: ["운전을 하고 있습니다.", "잠을 자고 있습니다.", "요리를 하고 있습니다.", "사진을 찍고 있습니다."], answer: 3,
        sourceUrl: "flower.html", sourceTitle: "Flower" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n초록 바탕에 나무 모양이 그려진 표지판입니다.",
        options: ["은행이 있습니다.", "공원이 있습니다.", "학교가 있습니다.", "병원이 있습니다."], answer: 1,
        sourceUrl: "nature.html", sourceTitle: "Nature" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n이 옷___ 세탁소에 맡겼어요.",
        options: ["옷에서 세탁소에 맡겼어요.", "옷이 세탁소에 맡겼어요.", "옷을 세탁소에 맡겼어요.", "옷도 세탁소에 맡겼어요."], answer: 2,
        sourceUrl: "clothes.html", sourceTitle: "Clothes" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n주말에 친구를 자주 ______.",
        options: ["만났요.", "만나요.", "만나여요.", "만나아요."], answer: 1,
        sourceUrl: "sentencefriend1.html", sourceTitle: "Friend sentence" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"동물원 관람 안내: 오전 9시 ~ 오후 5시 운영합니다. 매주 월요일은 휴관입니다.\"\n\n동물원은 언제 쉽니까?",
        options: ["매주 월요일", "매주 화요일", "매주 토요일", "매일"], answer: 0,
        sourceUrl: "animals.html", sourceTitle: "Animals" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n가구",
        options: ["침대, 책상, 의자 등을 말합니다.", "음식을 말합니다.", "동물을 말합니다.", "옷을 말합니다."], answer: 0,
        sourceUrl: "furniture.html", sourceTitle: "Furniture" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n거실",
        options: ["잠을 자는 공간입니다.", "음식을 만드는 공간입니다.", "가족이 함께 모여 쉬는 공간입니다.", "씻는 공간입니다."], answer: 2,
        sourceUrl: "livingRoom.html", sourceTitle: "LivingRoom" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"놀이공원 이용 안내: 자유이용권은 입장 시 구매할 수 있습니다. 어린이는 할인됩니다.\"\n\n자유이용권은 언제 구매할 수 있습니까?",
        options: ["퇴장 시", "전화로만", "예약 후 일주일 뒤", "입장 시"], answer: 3,
        sourceUrl: "purchase.html", sourceTitle: "Purchase" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n좋아하는 계절: _____________",
        options: ["생일 선물", "가을", "출근 시간", "가족 모임"], answer: 1,
        sourceUrl: "mountain.html", sourceTitle: "Mountain" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n바다에 가면 ______ 수영을 합니다.",
        options: ["보통도", "보통", "보통은", "보통이"], answer: 1,
        sourceUrl: "sea.html", sourceTitle: "Sea" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n생일에는 ______ 케이크를 먹습니다.",
        options: ["보통가", "보통를", "보통는", "보통"], answer: 3,
        sourceUrl: "gift.html", sourceTitle: "Gift" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n저녁에는 ______ 가족과 함께 식사합니다.",
        options: ["주로가", "주로", "주로도", "주로는"], answer: 1,
        sourceUrl: "evening.html", sourceTitle: "Evening" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n고향이 그리우면 가족에게 ______",
        options: ["전화하지 않는 것이 좋습니다.", "전화하는 것이 좋습니다.", "전화해야 안 됩니다.", "전화할 수 없습니다."], answer: 1,
        sourceUrl: "mother.html", sourceTitle: "Mother" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n낯선 곳에서 길을 잃으면 ______ 이렇게 하면 안전하게 도움을 받을 수 있습니다.",
        options: ["혼자 계속 걷는 것이 좋습니다.", "아무 곳에나 들어가는 것이 좋습니다.", "그냥 앉아 있는 것이 좋습니다.", "지나가는 사람에게 물어보는 것이 좋습니다."], answer: 3,
        sourceUrl: "taxi.html", sourceTitle: "Taxi" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n산이나 들처럼 자연이 만든 아름다운 경치입니다.",
        options: ["도로", "풍경", "다리", "건물"], answer: 1,
        sourceUrl: "landscapes.html", sourceTitle: "Landscapes" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n한국 음식은 다양합니다. 비빔밥, 불고기, 김치찌개 등이 유명합니다. 매운 음식도 많고, 채소를 많이 사용합니다.",
        options: ["한국의 날씨", "한국 교통수단", "한국 직장 문화", "한국 음식 문화"], answer: 3,
        sourceUrl: "gimbap.html", sourceTitle: "Gimbap" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"공원 이용 안내: 공원은 오전 6시부터 오후 10시까지 개방합니다. 반려동물은 목줄을 하고 입장해야 합니다.\"",
        options: ["반려동물은 입장할 수 없습니다.", "반려동물은 목줄을 하고 입장해야 합니다.", "공원은 24시간 개방합니다.", "목줄은 필요 없습니다."], answer: 1,
        sourceUrl: "dog.html", sourceTitle: "Dog" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"애완동물 카페 이용 안내: 카페에 입장하려면 손을 소독해야 합니다. 동물에게 간식을 주는 것은 금지되어 있습니다.\"",
        options: ["손을 소독해야 입장할 수 있습니다.", "손 소독은 필요 없습니다.", "동물에게 간식을 줘도 됩니다.", "아무나 자유롭게 만질 수 있습니다."], answer: 0,
        sourceUrl: "cat.html", sourceTitle: "Cat" }
    ]
  },
  {
    id: "set_09",
    title: "EPS-TOPIK Mock Test #9",
    free: true,
    listening: [
      { id: "L01", audioText: "정말 고마워요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["천만에요.", "늦었어요.", "가까워요.", "비싸요."], answer: 0,
        sourceUrl: "cheonman1.html", sourceTitle: "You're Welcome" },
      { id: "L02", audioText: "실례합니다, 말씀 좀 여쭤봐도 될까요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 비싸요.", "아니요, 멀어요.", "아니요, 늦었어요.", "네, 말씀하세요."], answer: 3,
        sourceUrl: "sillye1.html", sourceTitle: "Excuse Me" },
      { id: "L03", audioText: "이 단어 무슨 뜻이에요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["비싸요.", "가까워요.", "월요일이에요.", "'사랑'이라는 뜻이에요."], answer: 3,
        sourceUrl: "ige1.html", sourceTitle: "What Does This Mean?" },
      { id: "L04", audioText: "이거 너무 비싸요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 배고파요.", "네, 맛있어요.", "네, 좀 비싸요.", "아니요, 늦었어요."], answer: 2,
        sourceUrl: "bissayo1.html", sourceTitle: "It's Too Expensive" },
      { id: "L05", audioText: "이건 정말 싸네요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 정말 싸요.", "네, 맛있어요.", "아니요, 늦었어요.", "아니요, 비싸요."], answer: 0,
        sourceUrl: "ssayo1.html", sourceTitle: "It's Cheap" },
      { id: "L06", audioText: "남자: 이 길이 어느 쪽이에요? 여자: 저쪽이에요.", question: "여자는 어느 쪽을 가리켰습니까?",
        options: ["이쪽", "앞쪽", "뒤쪽", "저쪽"], answer: 3,
        sourceUrl: "eoneujjokieyo1.html", sourceTitle: "Which Way?" },
      { id: "L07", audioText: "남자: 여기서 역까지 멀어요? 여자: 아니요, 가까워요.", question: "역까지 거리는 어떻습니까?",
        options: ["걸어갈 수 없다", "멀다", "알 수 없다", "가깝다"], answer: 3,
        sourceUrl: "meoreoyo1.html", sourceTitle: "Is It Far?" },
      { id: "L08", audioText: "이 길로 쭉 직진하세요.", question: "어떻게 가야 합니까?",
        options: ["좌회전한다", "우회전한다", "돌아간다", "직진한다"], answer: 3,
        sourceUrl: "jikjinhaseyo1.html", sourceTitle: "Go Straight" },
      { id: "L09", audioText: "남자: 오늘 왜 늦었어요? 여자: 죄송해요, 차가 막혔어요.", question: "여자는 왜 늦었습니까?",
        options: ["차가 막혀서", "늦잠을 자서", "버스를 놓쳐서", "길을 잃어서"], answer: 0,
        sourceUrl: "neujeosseoyo1.html", sourceTitle: "I'm Late" },
      { id: "L10", audioText: "이분이 제 가족이에요.", question: "무엇을 소개하고 있습니까?",
        options: ["친구", "동료", "선생님", "가족"], answer: 3,
        sourceUrl: "jegajogieyo1.html", sourceTitle: "This Is My Family" },
      { id: "L11", audioText: "이 사람이 제 친구예요.", question: "무엇을 소개하고 있습니까?",
        options: ["선생님", "가족", "친구", "이웃"], answer: 2,
        sourceUrl: "jechinguyeoyo1.html", sourceTitle: "This Is My Friend" },
      { id: "L12", audioText: "이제 준비가 완벽해요.", question: "무엇에 대해 말하고 있습니까?",
        options: ["준비를 잊었다", "준비를 안 했다", "준비가 부족하다", "준비가 완벽하다"], answer: 3,
        sourceUrl: "wanbyeokhaeyo1.html", sourceTitle: "That's Perfect" },
      { id: "L13", audioText: "이 정도면 충분해요.", question: "무엇에 대해 말하고 있습니까?",
        options: ["너무 많다", "충분하다", "모자라다", "부족하다"], answer: 1,
        sourceUrl: "chungbunhaeyo1.html", sourceTitle: "That's Enough" },
      { id: "L14", audioText: "남자: 이거 같이 할까요? 여자: 네, 저도 동의해요.", question: "여자는 어떤 의견입니까?",
        options: ["반대한다", "싫어한다", "모르겠다", "동의한다"], answer: 3,
        sourceUrl: "donguihaeyo1.html", sourceTitle: "I Agree" },
      { id: "L15", audioText: "그건 틀렸어요.", question: "무엇에 대해 말하고 있습니까?",
        options: ["맞다", "틀렸다", "모르겠다", "비슷하다"], answer: 1,
        sourceUrl: "teullyeosseoyo1.html", sourceTitle: "That's Wrong" },
      { id: "L16", audioText: "맞아요, 그게 정답이에요.", question: "무엇에 대해 말하고 있습니까?",
        options: ["모르겠다", "비슷하다", "정답이다", "틀렸다"], answer: 2,
        sourceUrl: "majayo1.html", sourceTitle: "That's Right" },
      { id: "L17", audioText: "잘 모르겠어요.", question: "무엇에 대해 말하고 있습니까?",
        options: ["모른다", "확실하다", "기억한다", "안다"], answer: 0,
        sourceUrl: "moreugesseoyo1.html", sourceTitle: "I Don't Know" },
      { id: "L18", audioText: "들어오세요.", question: "무엇을 말했습니까?",
        options: ["들어오라고 했다", "기다리라고 했다", "나가라고 했다", "앉으라고 했다"], answer: 0,
        sourceUrl: "deureooseyo1.html", sourceTitle: "Come In" },
      { id: "L19", audioText: "잠시만 기다려 주시겠어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 비싸요.", "네, 맛있어요.", "네, 기다릴게요.", "아니요, 늦었어요."], answer: 2,
        sourceUrl: "gidaryeojuseyo1.html", sourceTitle: "Please Wait" },
      { id: "L20", audioText: "좋은 하루 보내세요.", question: "무엇을 말했습니까?",
        options: ["질문했다", "불평했다", "좋은 하루를 기원했다", "화를 냈다"], answer: 2,
        sourceUrl: "joeunharubonaeseyo1.html", sourceTitle: "Have a Nice Day" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n앉을 때 사용하는 다리가 네 개 달린 가구입니다.",
        options: ["소파", "책상", "침대", "의자"], answer: 3,
        sourceUrl: "chair.html", sourceTitle: "Chair" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n글씨를 쓸 때 사용하는 얇고 긴 필기도구입니다.",
        options: ["연필", "자", "가위", "지우개"], answer: 0,
        sourceUrl: "pencil.html", sourceTitle: "Pencil" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 아기가 엄마 품에서 울고 있습니다.",
        options: ["아기가 웃고 있습니다.", "아기가 자고 있습니다.", "아기가 걷고 있습니다.", "아기가 울고 있습니다."], answer: 3,
        sourceUrl: "baby.html", sourceTitle: "Baby" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n초록 바탕에 화장실 모양이 그려진 표지판입니다.",
        options: ["사무실 위치입니다.", "화장실 위치입니다.", "출입구 위치입니다.", "식당 위치입니다."], answer: 1,
        sourceUrl: "restroom.html", sourceTitle: "Restroom" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n제 동생___ 학교에 다녀요.",
        options: ["동생에서 학교에 다녀요.", "동생이 학교에 다녀요.", "동생을 학교에 다녀요.", "동생께 학교에 다녀요."], answer: 1,
        sourceUrl: "brother.html", sourceTitle: "Brother" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n언니는 매일 화장을 ______.",
        options: ["하아요.", "해요.", "했요.", "하여요."], answer: 1,
        sourceUrl: "sister.html", sourceTitle: "Sister" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"도서관 이용 안내: 평일 오전 9시 ~ 오후 8시, 주말 오전 9시 ~ 오후 5시 운영합니다.\"\n\n주말에는 몇 시까지 운영합니까?",
        options: ["오후 9시", "오후 5시", "오전 9시", "오후 8시"], answer: 1,
        sourceUrl: "academy.html", sourceTitle: "Academy" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n하늘",
        options: ["산 위에 있는 곳입니다.", "바다 속에 있는 곳입니다.", "땅 밑에 있는 곳입니다.", "맑거나 흐릴 수 있고, 별과 구름이 있는 곳입니다."], answer: 3,
        sourceUrl: "sky.html", sourceTitle: "Sky" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n색깔",
        options: ["맛을 말합니다.", "크기를 말합니다.", "빨강, 파랑, 노랑 등을 말합니다.", "무게를 말합니다."], answer: 2,
        sourceUrl: "colors.html", sourceTitle: "Colors" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"체육관 이용 안내: 운동복과 실내화를 착용해야 입장할 수 있습니다.\"\n\n체육관에 입장하려면 무엇을 착용해야 합니까?",
        options: ["작업복", "정장", "교복", "운동복과 실내화"], answer: 3,
        sourceUrl: "sports.html", sourceTitle: "Sports" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n좋아하는 동물: _____________",
        options: ["사자", "가족 모임", "생일 선물", "출근 시간"], answer: 0,
        sourceUrl: "lion.html", sourceTitle: "Lion" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n점심시간에는 ______ 동료들과 식사합니다.",
        options: ["보통이", "보통", "보통은", "보통도"], answer: 1,
        sourceUrl: "lunch.html", sourceTitle: "Lunch" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n고기를 구울 때는 ______ 뒤집어야 합니다.",
        options: ["자주를", "자주", "자주가", "자주는"], answer: 1,
        sourceUrl: "meat.html", sourceTitle: "Meat" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n새벽에는 ______ 조용합니다.",
        options: ["대체로가", "대체로는", "대체로도", "대체로"], answer: 3,
        sourceUrl: "dawn.html", sourceTitle: "Dawn" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n기분이 안 좋으면 좋아하는 음악을 ______",
        options: ["듣는 것이 좋습니다.", "들어야 안 됩니다.", "들을 수 없습니다.", "듣지 않는 것이 좋습니다."], answer: 0,
        sourceUrl: "mood.html", sourceTitle: "Mood" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n새로운 사람을 만나면 ______ 이렇게 하면 좋은 첫인상을 줄 수 있습니다.",
        options: ["밝게 인사하는 것이 좋습니다.", "도망가는 것이 좋습니다.", "화를 내는 것이 좋습니다.", "무시하는 것이 좋습니다."], answer: 0,
        sourceUrl: "feelings.html", sourceTitle: "Feelings" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n창문을 통해 들어오는 빛이나 바깥 풍경을 볼 수 있게 해주는 건축 요소입니다.",
        options: ["지붕", "창문", "벽", "문"], answer: 1,
        sourceUrl: "window.html", sourceTitle: "Window" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n서울에는 높은 건물이 많습니다. 최근에는 새로운 건물이 계속 지어지고 있으며, 도시 풍경이 빠르게 변화하고 있습니다.",
        options: ["한국의 교통수단", "서울의 건물과 풍경", "한국의 직장 문화", "한국의 음식 문화"], answer: 1,
        sourceUrl: "buildings.html", sourceTitle: "Buildings" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"관광 안내소 이용 안내: 무료로 지도와 관광 정보를 제공합니다. 외국어 통역 서비스도 이용할 수 있습니다.\"",
        options: ["지도는 유료로 판매합니다.", "무료로 지도와 관광 정보를 제공합니다.", "통역 서비스는 없습니다.", "외국인은 이용할 수 없습니다."], answer: 1,
        sourceUrl: "tourism.html", sourceTitle: "Tourism" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"교과서 대여 안내: 학기 초에 교과서를 대여할 수 있으며, 학기 말에 반납해야 합니다.\"",
        options: ["교과서는 구매만 가능합니다.", "교과서는 대여할 수 없습니다.", "반납할 필요가 없습니다.", "학기 초에 교과서를 대여할 수 있습니다."], answer: 3,
        sourceUrl: "textbook.html", sourceTitle: "Textbook" }
    ]
  },
  {
    id: "set_10",
    title: "EPS-TOPIK Mock Test #10",
    free: true,
    listening: [
      { id: "L01", audioText: "사랑해요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["늦었어요.", "비싸요.", "저도 사랑해요.", "가까워요."], answer: 2,
        sourceUrl: "saranghaeyo1.html", sourceTitle: "I Love You" },
      { id: "L02", audioText: "이해가 안 돼요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["다시 설명해 드릴게요.", "가까워요.", "맛있어요.", "비싸요."], answer: 0,
        sourceUrl: "ihaemot1.html", sourceTitle: "I Don't Understand" },
      { id: "L03", audioText: "같이 밥 먹을까요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 비싸요.", "아니요, 늦었어요.", "아니요, 멀어요.", "네, 같이 먹어요."], answer: 3,
        sourceUrl: "meogeo1.html", sourceTitle: "Let's Eat" },
      { id: "L04", audioText: "같이 커피 마실까요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 같이 마셔요.", "아니요, 배고파요.", "아니요, 늦었어요.", "네, 맛있어요."], answer: 0,
        sourceUrl: "masyeo1.html", sourceTitle: "Let's Drink" },
      { id: "L05", audioText: "좋은 아침이에요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 좋은 아침이에요.", "늦었어요.", "가까워요.", "비싸요."], answer: 0,
        sourceUrl: "joheun1.html", sourceTitle: "Good Morning" },
      { id: "L06", audioText: "남자: 저는 이만 가볼게요. 여자: 네, 나중에 봐요.", question: "여자는 남자에게 무엇을 말했습니까?",
        options: ["전화하라고 했다", "같이 가자고 했다", "나중에 보자고 했다", "기다리라고 했다"], answer: 2,
        sourceUrl: "najunge1.html", sourceTitle: "See You Later" },
      { id: "L07", audioText: "내일 봐요.", question: "무엇을 말했습니까?",
        options: ["오늘 만나자고 했다", "안 만난다고 했다", "내일 만나자고 했다", "다음 주에 만나자고 했다"], answer: 2,
        sourceUrl: "naeil1.html", sourceTitle: "See You Tomorrow" },
      { id: "L08", audioText: "괜찮아요, 문제없어요.", question: "무엇에 대해 말하고 있습니까?",
        options: ["문제가 생겼다", "문제가 크다", "문제가 없다", "문제를 모른다"], answer: 2,
        sourceUrl: "munje1.html", sourceTitle: "No Problem" },
      { id: "L09", audioText: "물 한 잔 주세요.", question: "무엇을 부탁했습니까?",
        options: ["주스", "커피", "물", "차"], answer: 2,
        sourceUrl: "muljuseyo1.html", sourceTitle: "Water Please" },
      { id: "L10", audioText: "밖이 너무 추워요.", question: "밖의 날씨는 어떻습니까?",
        options: ["춥다", "따뜻하다", "덥다", "시원하다"], answer: 0,
        sourceUrl: "chagawo1.html", sourceTitle: "It's Cold" },
      { id: "L11", audioText: "국물이 정말 뜨거워요.", question: "국물은 어떻습니까?",
        options: ["뜨겁다", "시원하다", "차갑다", "미지근하다"], answer: 0,
        sourceUrl: "tteugeo1.html", sourceTitle: "It's Hot" },
      { id: "L12", audioText: "이 음식은 너무 짜요.", question: "이 음식의 맛은 어떻습니까?",
        options: ["짜다", "달다", "시다", "맵다"], answer: 0,
        sourceUrl: "jjayo1.html", sourceTitle: "It's Salty" },
      { id: "L13", audioText: "이 과일은 정말 달아요.", question: "이 과일의 맛은 어떻습니까?",
        options: ["달다", "시다", "맵다", "짜다"], answer: 0,
        sourceUrl: "dalayo1.html", sourceTitle: "It's Sweet" },
      { id: "L14", audioText: "이 음식은 너무 매워요.", question: "이 음식의 맛은 어떻습니까?",
        options: ["짜다", "맵다", "싱겁다", "달다"], answer: 1,
        sourceUrl: "maewoyo1.html", sourceTitle: "It's Spicy" },
      { id: "L15", audioText: "이제 가요.", question: "무엇을 말했습니까?",
        options: ["가자고 했다", "먹자고 했다", "쉬자고 했다", "기다리자고 했다"], answer: 0,
        sourceUrl: "gayo1.html", sourceTitle: "Let's Go" },
      { id: "L16", audioText: "잠시만요.", question: "무엇을 말했습니까?",
        options: ["떠나라고 했다", "잠깐 기다려 달라고 했다", "가라고 했다", "빨리 오라고 했다"], answer: 1,
        sourceUrl: "jamsiman1.html", sourceTitle: "Wait a Moment" },
      { id: "L17", audioText: "왜 그랬어요?", question: "무엇을 묻고 있습니까?",
        options: ["시간", "이유", "방법", "장소"], answer: 1,
        sourceUrl: "waeyo1.html", sourceTitle: "Why?" },
      { id: "L18", audioText: "정말요? 몰랐어요.", question: "무엇에 대해 말하고 있습니까?",
        options: ["이미 알고 있었다", "화가 났다", "몰랐던 사실에 놀랐다", "관심이 없다"], answer: 2,
        sourceUrl: "jeongmalyo1.html", sourceTitle: "Really?" },
      { id: "L19", audioText: "행운을 빌어요.", question: "무엇을 말했습니까?",
        options: ["슬프다고 했다", "걱정된다고 했다", "행운을 빈다고 했다", "축하한다고 했다"], answer: 2,
        sourceUrl: "haenguneulbireoyo1.html", sourceTitle: "Good Luck" },
      { id: "L20", audioText: "정말 잘했어요.", question: "무엇을 말했습니까?",
        options: ["칭찬했다", "걱정했다", "혼냈다", "슬퍼했다"], answer: 0,
        sourceUrl: "jalhaesseoyo1.html", sourceTitle: "Good Job" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n건물이나 방에 드나들 때 여닫는 것입니다.",
        options: ["문", "벽", "창문", "지붕"], answer: 0,
        sourceUrl: "door.html", sourceTitle: "Door" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n나를 낳아 주고 길러 주신 남자 부모님입니다.",
        options: ["아버지", "누나", "형", "어머니"], answer: 0,
        sourceUrl: "dad.html", sourceTitle: "Dad" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 다친 다리를 붙잡고 아파하고 있습니다.",
        options: ["손을 다쳤습니다.", "머리를 다쳤습니다.", "다리를 다쳤습니다.", "팔을 다쳤습니다."], answer: 2,
        sourceUrl: "body.html", sourceTitle: "Body" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n노란 바탕에 느낌표가 그려진 표지판입니다.",
        options: ["출입 금지입니다.", "흡연 구역입니다.", "조심하세요.", "비상구입니다."], answer: 2,
        sourceUrl: "josimhaseyo1.html", sourceTitle: "Be Careful" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n저는 부모님___ 정말 사랑해요.",
        options: ["부모님이 정말 사랑해요.", "부모님에서 정말 사랑해요.", "부모님도를 정말 사랑해요.", "부모님을 정말 사랑해요."], answer: 3,
        sourceUrl: "love.html", sourceTitle: "Love" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n감정을 솔직하게 ______.",
        options: ["표현해요.", "표현하요.", "표현해서요.", "표현했요."], answer: 0,
        sourceUrl: "emotions.html", sourceTitle: "Emotions" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"경찰서 위치 안내: 사고나 위급 상황 시 112로 신고하거나 가까운 경찰서를 방문하세요.\"\n\n위급 상황 시 몇 번으로 신고합니까?",
        options: ["119", "112", "110", "114"], answer: 1,
        sourceUrl: "gyeongchalbulleojuseyo1.html", sourceTitle: "Call the Police" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n일어나다",
        options: ["앉거나 누운 상태에서 서는 것입니다.", "걷는 것입니다.", "앉는 것입니다.", "눕는 것입니다."], answer: 0,
        sourceUrl: "ireonaseyo1.html", sourceTitle: "Stand Up" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n앉다",
        options: ["걷는 것입니다.", "서 있다가 의자나 바닥에 앉는 것입니다.", "서는 것입니다.", "뛰는 것입니다."], answer: 1,
        sourceUrl: "aneuseyo1.html", sourceTitle: "Sit Down" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"식당 이용 안내: 식사 후 배가 부르시면 남은 음식은 포장해 드립니다.\"\n\n배가 부르면 남은 음식을 어떻게 할 수 있습니까?",
        options: ["포장해 준다", "환불받는다", "다 먹어야 한다", "버려야 한다"], answer: 0,
        sourceUrl: "baebulleoyo1.html", sourceTitle: "I'm Full" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n헤어질 때 인사말: _____________",
        options: ["가족 모임", "출근 시간", "생일 선물", "또 봐요"], answer: 3,
        sourceUrl: "ttaobwayo1.html", sourceTitle: "See You Soon" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n이 가방 디자인이 ______ 예쁘네요.",
        options: ["정말도", "정말이", "정말은", "정말"], answer: 3,
        sourceUrl: "meotjyeoyo1.html", sourceTitle: "That's Cool" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n이 강아지는 ______ 귀엽습니다.",
        options: ["너무가", "너무", "너무는", "너무를"], answer: 1,
        sourceUrl: "gwiyeowoyo1.html", sourceTitle: "That's Cute" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n이 경치가 ______ 아름답습니다.",
        options: ["정말은", "정말를", "정말가", "정말"], answer: 3,
        sourceUrl: "areumdawoyo1.html", sourceTitle: "That's Beautiful" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n이 소식을 들으면 사람들이 ______",
        options: ["놀랄 수 없습니다.", "놀라지 않을 것입니다.", "놀랄 것입니다.", "놀라야 안 됩니다."], answer: 2,
        sourceUrl: "nollawoyo1.html", sourceTitle: "That's Amazing" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n한국 문화에 관심이 있으면 ______ 이렇게 하면 더 깊이 이해할 수 있습니다.",
        options: ["책이나 영상을 찾아보는 것이 좋습니다.", "아무것도 안 하는 것이 좋습니다.", "무시하는 것이 좋습니다.", "피하는 것이 좋습니다."], answer: 0,
        sourceUrl: "heungmirowoyo1.html", sourceTitle: "That's Interesting" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n기대 이상으로 훌륭하거나 멋질 때 쓰는 감탄 표현입니다.",
        options: ["평범하다", "지루하다", "대단하다", "이상하다"], answer: 2,
        sourceUrl: "jeongmalmeotjyeoyo1.html", sourceTitle: "That's Awesome" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n헤어질 때는 여러 가지 인사말을 씁니다. '안녕히 가세요', '또 봐요', '잘 가요' 등이 있으며, 상황에 따라 다르게 사용합니다.",
        options: ["헤어질 때의 인사말", "사과할 때의 표현", "만날 때의 인사말", "감사할 때의 표현"], answer: 0,
        sourceUrl: "bye2.html", sourceTitle: "Good Bye" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"칭찬 문화 안내: 한국에서는 상대방을 칭찬할 때 '정말 좋아요', '최고예요' 같은 표현을 자주 사용합니다.\"",
        options: ["칭찬 표현은 한 가지뿐입니다.", "칭찬은 예의에 어긋납니다.", "한국에서는 칭찬을 하지 않습니다.", "한국에서는 칭찬 표현을 자주 사용합니다."], answer: 3,
        sourceUrl: "jeongmaljoayo1.html", sourceTitle: "That's Great" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"고향에 대한 그리움 안내: 타지에서 일하다 보면 고향과 가족이 그리울 수 있습니다. 이럴 때는 가족과 자주 연락하는 것이 도움이 됩니다.\"",
        options: ["고향을 잊어야 합니다.", "가족과 자주 연락하는 것이 도움이 됩니다.", "가족과 연락하지 않는 것이 좋습니다.", "그리움은 느낄 필요가 없습니다."], answer: 1,
        sourceUrl: "sentencelover1.html", sourceTitle: "lover sentence" }
    ]
  }
];
