/* =========================================================
   EPS-TOPIK 정식 모의고사 데이터
   -----------------------------------------------------------
   실제 EPS-TOPIK 형식 기준(2026년):
   - 총 40문항, 50분, 쉬는 시간 없음
   - 듣기 20문항(25분) + 읽기 20문항(25분)
   - 전부 4지선다, 각 2.5점 (합계 100점)
   - 합격선은 업종마다 다름 (제조업 60점 / 그 외 45점 / 어업 특례 30점)
     → 이 앱은 참고용 연습이며, 실제 시험 채점 기준은 HRD Korea 공식 안내를 따라야 함

   세트 추가 방법: 아래 mockExamSets 배열에 같은 형식으로 객체를 추가하면 됨.
   free: true 인 세트만 무료로 열림. 나머지는 유료(paid) 플랜만 접근 가능.

   ✅ sourceUrl/sourceTitle:
   각 문항이 quizDB(script.js) 600개 레슨 페이지 중 어떤 페이지와 "주제"로 연결되는지
   나타내는 필드. 문제 문장과 레슨 페이지 문장이 토씨 하나까지 일치할 필요는 없음 —
   같은 주제를 더 공부하고 싶을 때 찾아갈 곳을 안내하는 용도. 시험 응시 중에는
   화면에 노출되지 않고, 결과 화면(정답/오답 40문항 리뷰)에서만
   "📚 Study [제목] →" 버튼을 만드는 데 쓰인다.
   나중에 quizDB에 새 페이지가 추가되면, 그 페이지를 주제로 새 문항/새 세트를
   똑같은 방식으로 계속 만들어나갈 수 있음.

   ✅ 2회차 수정 사항 (1회차 대비):
   - R05: 오답 중 하나("버스를 내려요")가 사실 자연스러운 표현이라
     복수 정답처럼 읽히던 문제 → 명확하게 하나만 맞는 조사 문제로 교체
   - sourceUrl 중복 제거: jakeop.html(R02/R09), geunmuji.html(R05/R19),
     apayo1.html(L08/R07)이 겹쳐 쓰이던 것을 40문항 전부 서로 다른 페이지로 재매핑
   ========================================================= */

window.mockExamSets = window.mockExamSets || [
  {
    id: "set_01",
    title: "EPS-TOPIK Mock Test #1",
    free: true,
    listening: [
      { id: "L01", audioText: "안녕하세요. 처음 뵙겠습니다.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 늦었어요.", "네, 비싸요.", "네, 반갑습니다.", "네, 맛있어요."], answer: 2,
        sourceUrl: "annyeonghaseyo1.html", sourceTitle: "Hello" },
      { id: "L02", audioText: "지금 몇 시예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["회사예요.", "3만원이에요.", "월요일이에요.", "9시예요."], answer: 3,
        sourceUrl: "jigeummyeotsiyeyo1.html", sourceTitle: "What Time Is It?" },
      { id: "L03", audioText: "오늘 날씨가 어때요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["친구예요.", "먹어요.", "추워요.", "일요일이에요."], answer: 2,
        sourceUrl: "weather.html", sourceTitle: "Weather" },
      { id: "L04", audioText: "이거 얼마예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["5천원이에요.", "5개예요.", "5층이에요.", "5시예요."], answer: 0,
        sourceUrl: "eolmayeyo1.html", sourceTitle: "How Much Is It" },
      { id: "L05", audioText: "화장실이 어디에 있어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["많이 있어요.", "저기 있어요.", "내일 있어요.", "친구가 있어요."], answer: 1,
        sourceUrl: "hwajangsil1.html", sourceTitle: "Where Is the Restroom?" },
      { id: "L06", audioText: "남자: 오늘 회사에 몇 시까지 가요? 여자: 8시까지 가요.", question: "여자는 몇 시까지 회사에 갑니까?",
        options: ["9시", "6시", "8시", "7시"], answer: 2,
        sourceUrl: "chulgeun.html", sourceTitle: "Go to Work" },
      { id: "L07", audioText: "남자: 안전모를 써 주세요. 여자: 네, 알겠습니다.", question: "남자가 여자에게 부탁한 것은 무엇입니까?",
        options: ["안전모 착용", "마스크 착용", "장갑 착용", "안전화 착용"], answer: 0,
        sourceUrl: "anjeonmo.html", sourceTitle: "Safety Helmet" },
      { id: "L08", audioText: "여자: 오늘 몸이 아파서 병원에 가야 해요. 남자: 그럼 오늘 회사를 쉬세요.", question: "여자는 오늘 무엇을 합니까?",
        options: ["여행을 간다", "병원에 간다", "학교에 간다", "회사에 간다"], answer: 1,
        sourceUrl: "apayo1.html", sourceTitle: "Im Sick" },
      { id: "L09", audioText: "남자: 이 서류에 사인해 주세요. 여자: 네, 여기 사인할게요.", question: "여자가 하는 행동은 무엇입니까?",
        options: ["서류를 읽는다", "서류를 복사한다", "서류에 사인한다", "서류를 버린다"], answer: 2,
        sourceUrl: "seomyeong.html", sourceTitle: "Signature" },
      { id: "L10", audioText: "남자: 다음 주에 휴가를 가고 싶어요. 여자: 언제부터 언제까지예요?", question: "여자가 남자에게 물어본 것은 무엇입니까?",
        options: ["휴가 장소", "휴가 기간", "휴가 비용", "휴가 이유"], answer: 1,
        sourceUrl: "hyuga.html", sourceTitle: "Vacation" },
      { id: "L11", audioText: "공장 안에서는 뛰지 마세요. 위험합니다.", question: "이 방송의 목적은 무엇입니까?",
        options: ["퇴근을 알린다", "안전 주의를 준다", "휴식을 알린다", "식사를 안내한다"], answer: 1,
        sourceUrl: "wiheom.html", sourceTitle: "Danger" },
      { id: "L12", audioText: "오늘 야근이 있습니다. 저녁 8시까지 근무합니다.", question: "오늘 근무는 몇 시까지입니까?",
        options: ["낮 12시", "밤 10시", "저녁 6시", "저녁 8시"], answer: 3,
        sourceUrl: "yageun.html", sourceTitle: "Night Overtime" },
      { id: "L13", audioText: "이번 달 월급은 25일에 나옵니다.", question: "월급은 언제 나옵니까?",
        options: ["25일", "30일", "15일", "1일"], answer: 0,
        sourceUrl: "wolgeup.html", sourceTitle: "Monthly Salary" },
      { id: "L14", audioText: "남자: 이 기계가 고장 났어요. 여자: 반장님께 말씀드릴게요.", question: "여자는 무엇을 할 것입니까?",
        options: ["기계를 버린다", "반장에게 알린다", "기계를 고친다", "집에 간다"], answer: 1,
        sourceUrl: "banjang.html", sourceTitle: "Foreman" },
      { id: "L15", audioText: "다음 버스는 10분 후에 도착합니다.", question: "버스는 언제 도착합니까?",
        options: ["지금", "10시간 후", "내일", "10분 후"], answer: 3,
        sourceUrl: "bus.html", sourceTitle: "Bus" },
      { id: "L16", audioText: "남자: 실례합니다. 은행이 어디예요? 여자: 이 길로 쭉 가세요. 왼쪽에 있어요.", question: "은행은 어느 쪽에 있습니까?",
        options: ["오른쪽", "위쪽", "왼쪽", "뒤쪽"], answer: 2,
        sourceUrl: "oenjjogeurodoseyo1.html", sourceTitle: "Turn Left" },
      { id: "L17", audioText: "물건을 받으면 바로 검사해 주세요.", question: "물건을 받은 후에 해야 할 일은 무엇입니까?",
        options: ["포장한다", "버린다", "검사한다", "판매한다"], answer: 2,
        sourceUrl: "geomsa.html", sourceTitle: "Inspection" },
      { id: "L18", audioText: "남자: 오늘 왜 늦었어요? 여자: 죄송합니다. 버스를 놓쳤어요.", question: "여자가 늦은 이유는 무엇입니까?",
        options: ["버스를 놓쳤다", "잠을 잤다", "길을 잃었다", "몸이 아팠다"], answer: 0,
        sourceUrl: "jigak.html", sourceTitle: "Lateness" },
      { id: "L19", audioText: "이 작업은 장갑을 끼고 하세요.", question: "이 작업을 할 때 착용해야 하는 것은 무엇입니까?",
        options: ["안경", "신발", "장갑", "모자"], answer: 2,
        sourceUrl: "anjeonjanggap.html", sourceTitle: "Safety Gloves" },
      { id: "L20", audioText: "남자: 내일부터 3일 동안 휴가입니다. 여자: 네, 잘 다녀오세요.", question: "남자는 며칠 동안 휴가입니까?",
        options: ["1일", "일주일", "5일", "3일"], answer: 3,
        sourceUrl: "yeonchahyuga.html", sourceTitle: "Annual Leave" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n손으로 종이나 천을 자를 때 쓰는 도구입니다.",
        options: ["볼펜", "가위", "안경", "가방"], answer: 1,
        sourceUrl: "gawi.html", sourceTitle: "Scissors" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n공사장에서 땅을 파는 데 쓰는 큰 기계입니다.",
        options: ["지게차", "굴착기", "트랙터", "자전거"], answer: 1,
        sourceUrl: "jakeop.html", sourceTitle: "Work" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 의자에 앉아서 종이책을 펴고 들여다보고 있습니다.",
        options: ["책을 읽고 있습니다.", "친구를 만나고 있습니다.", "밥을 먹고 있습니다.", "피아노를 치고 있습니다."], answer: 0,
        sourceUrl: "book.html", sourceTitle: "Book" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n노란 바탕에 번개 모양이 그려진 경고 표지판입니다.",
        options: ["떨어질 수 있으니까 조심하세요.", "바닥이 미끄러우니까 조심하세요.", "불이 붙을 수 있으니까 조심하세요.", "전기가 흐르니까 조심하세요."], answer: 3,
        sourceUrl: "gyeonggo.html", sourceTitle: "Warning" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n저는 매일 아침 8시에 ___에서 일해요.",
        options: ["공장을 일해요.", "공장에게 일해요.", "공장이 일해요.", "공장에서 일해요."], answer: 3,
        sourceUrl: "geunroja.html", sourceTitle: "Worker" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.",
        options: ["오늘 시내에서 많이 걸었어요.", "친구한테서 선물을 받었어요.", "퇴근할 때 문을 닫라요.", "심심하면 한국 노래를 듣어요."], answer: 0,
        sourceUrl: "city.html", sourceTitle: "City" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"튼튼치과 진료 시간: 오전 9시 ~ 오후 6시 (일요일 휴무)\"\n\n이 병원이 문을 여는 시간은 언제입니까?",
        options: ["오전 9시", "휴무일 없음", "오후 9시", "오전 6시"], answer: 0,
        sourceUrl: "byeongga.html", sourceTitle: "Sick Leave" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n복장",
        options: ["비빔밥", "작업복", "기차표", "컴퓨터"], answer: 1,
        sourceUrl: "bohogu.html", sourceTitle: "Protective Gear" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n작업장",
        options: ["근로자가 상담하는 곳입니다.", "근로자가 거주하는 곳입니다.", "근로자가 운동하는 곳입니다.", "근로자가 일하는 곳입니다."], answer: 3,
        sourceUrl: "geunmuji.html", sourceTitle: "Workplace" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"이번 주 급여는 통장으로 입금됩니다. 급여 명세서는 이메일로 발송됩니다.\"\n\n급여 명세서는 어떻게 받습니까?",
        options: ["이메일로 받습니다.", "문자로 받습니다.", "직접 받으러 갑니다.", "우편으로 받습니다."], answer: 0,
        sourceUrl: "geupyeo-myeongseoseo.html", sourceTitle: "Payslip" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n지급 방법: _____________",
        options: ["가족 모임", "출근 시간", "통장 입금", "생일 선물"], answer: 2,
        sourceUrl: "tongjang.html", sourceTitle: "Bank Account" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n한국어를 배우고 싶지만 학원에 갈 시간이 없습니다. 그래서 퇴근 후에 인터넷 강의를 ______ 한국어를 공부하고 있습니다.",
        options: ["듣자마자", "듣느라고", "들으려고", "들으면서"], answer: 3,
        sourceUrl: "gongbu1.html", sourceTitle: "Let's Study" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n오늘은 다른 날보다 길이 많이 막힙니다. ______ 가지 않으면 회사에 늦을 것 같습니다.",
        options: ["조심해서", "서둘러서", "서두르게", "조심하게"], answer: 1,
        sourceUrl: "ppalli1.html", sourceTitle: "Hurry Up" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n오늘은 날씨가 너무 덥습니다. 집에 오자마자 선풍기를 ______ 시원한 물을 마셨습니다.",
        options: ["틀려고", "틀면", "틀려면", "틀고"], answer: 3,
        sourceUrl: "water.html", sourceTitle: "Water" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n작업 중 손을 다쳤을 때는 상처가 가벼워도 바로 소독을 해야 합니다. 그리고 병원에 가서 진료를 받고 필요하면 주사를 ______",
        options: ["놓지 않도록 합니다.", "맞는 것이 좋습니다.", "맞지 않도록 합니다.", "놓는 것이 좋습니다."], answer: 1,
        sourceUrl: "eunggeupcheochi.html", sourceTitle: "First Aid" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n어두운 곳에서 작업할 때는 가시성이 높은 ______ 이것을 입으면 멀리서도 잘 보여서 사고를 막을 수 있습니다.",
        options: ["환기 장치를 작동해야 합니다.", "보호 장갑을 구매해야 합니다.", "비상 계단을 이용해야 합니다.", "반사 조끼를 착용해야 합니다."], answer: 3,
        sourceUrl: "anjeon_suchik.html", sourceTitle: "Safety Rules" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n손에 쥐고 철사를 끊거나 구부릴 때 쓰는 도구입니다. 전선이나 작은 부품을 잡을 때도 사용합니다.",
        options: ["쇠톱", "망치", "펜치", "토치"], answer: 2,
        sourceUrl: "penchi.html", sourceTitle: "Pliers" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n한국 사람들은 계절마다 즐겨 먹는 음식이 있습니다. 여름에는 차갑고 시원한 냉면, 콩국수, 팥빙수 등을 많이 먹습니다. 겨울에는 뜨거운 국이나 따뜻한 팥죽, 군고구마, 호떡 등을 자주 먹습니다.",
        options: ["조리 시기", "조리 방법", "음식 재료", "계절 음식"], answer: 3,
        sourceUrl: "food.html", sourceTitle: "Food" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"사내 휴게실 이용 안내: 출입문 비밀번호는 게시판에서 확인하세요. 회사 직원이면 누구나 이용할 수 있습니다. 이용 후에는 문을 꼭 닫고 나가야 합니다.\"",
        options: ["회사 직원은 누구나 휴게실을 이용할 수 있습니다.", "이용 후에는 문을 열어 두고 나가야 합니다.", "휴게실 출입문에는 비밀번호가 없습니다.", "다른 회사 직원도 이용할 수 있습니다."], answer: 0,
        sourceUrl: "chwieopgyuchik.html", sourceTitle: "Employment Rules" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"한국에서 일하는 외국인 근로자는 4대 사회보험 혜택을 받습니다. 이 중 산재보험은 사업주만 가입하면 되지만, 국민연금·건강보험·고용보험은 사업주와 근로자 모두 반드시 가입해야 합니다.\"",
        options: ["산재보험은 근로자와 사업주가 모두 가입해야 합니다.", "국민연금은 사업주만 가입하면 됩니다.", "근로자는 원하는 보험만 선택해서 가입할 수 있습니다.", "산재보험은 사업주만 가입하면 됩니다."], answer: 3,
        sourceUrl: "sanjaeboheom.html", sourceTitle: "Industrial Accident Insurance" }
    ]
  },
  {
    id: "set_02",
    title: "EPS-TOPIK Mock Test #2",
    free: true,
    listening: [
      { id: "L01", audioText: "이 음식 맛이 어때요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["커요.", "맛있어요.", "조용해요.", "빨라요."], answer: 1,
        sourceUrl: "masisseo1.html", sourceTitle: "It's Delicious" },
      { id: "L02", audioText: "생일이 언제예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["형이에요.", "만원이에요.", "회사예요.", "다음 달이에요."], answer: 3,
        sourceUrl: "saengilchukha1.html", sourceTitle: "Happy Birthday" },
      { id: "L03", audioText: "이름이 뭐예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["일곱 살이에요.", "한국이에요.", "교실이에요.", "김민수예요."], answer: 3,
        sourceUrl: "irum1.html", sourceTitle: "What's Your Name" },
      { id: "L04", audioText: "커피 드시겠어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 주세요.", "아니요, 가까워요.", "네, 비싸요.", "아니요, 늦었어요."], answer: 0,
        sourceUrl: "keopijuseyo1.html", sourceTitle: "Coffee Please" },
      { id: "L05", audioText: "여기서 멀어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 맛있어요.", "네, 커요.", "아니요, 늦었어요.", "아니요, 가까워요."], answer: 3,
        sourceUrl: "gakkawoyo1.html", sourceTitle: "Is It Close?" },
      { id: "L06", audioText: "남자: 이번 달 수당이 얼마예요? 여자: 20만원 정도예요.", question: "여자의 이번 달 수당은 얼마입니까?",
        options: ["20만원", "10만원", "5만원", "30만원"], answer: 0,
        sourceUrl: "sudang.html", sourceTitle: "Allowance" },
      { id: "L07", audioText: "남자: 기숙사에서 지내요? 여자: 네, 회사 기숙사에서 지내요.", question: "여자는 어디에서 지냅니까?",
        options: ["고향집", "호텔", "친구 집", "회사 기숙사"], answer: 3,
        sourceUrl: "gisuksa.html", sourceTitle: "Dormitory" },
      { id: "L08", audioText: "남자: 계약 기간이 언제까지예요? 여자: 내년 12월까지예요.", question: "여자의 계약 기간은 언제까지입니까?",
        options: ["다음 주까지", "내년 12월까지", "이번 달까지", "올해 6월까지"], answer: 1,
        sourceUrl: "gyeyak-gigan.html", sourceTitle: "Contract Period" },
      { id: "L09", audioText: "남자: 오늘 제품 몇 개 만들었어요? 여자: 오백 개 만들었어요.", question: "여자는 오늘 제품을 몇 개 만들었습니까?",
        options: ["오천 개", "오십 개", "오 개", "오백 개"], answer: 3,
        sourceUrl: "jepum.html", sourceTitle: "Product" },
      { id: "L10", audioText: "남자: 이 부품을 어디에 두면 돼요? 여자: 창고에 두세요.", question: "부품을 어디에 둬야 합니까?",
        options: ["기숙사", "사무실", "식당", "창고"], answer: 3,
        sourceUrl: "changgo.html", sourceTitle: "Warehouse" },
      { id: "L11", audioText: "이 기계는 고장 났으니 사용하지 마세요.", question: "이 방송의 목적은 무엇입니까?",
        options: ["점심시간 안내", "기계 사용 금지 안내", "퇴근 시간 안내", "회식 안내"], answer: 1,
        sourceUrl: "gojang.html", sourceTitle: "Breakdown" },
      { id: "L12", audioText: "오늘부터 새 사원증을 지급합니다.", question: "오늘부터 무엇을 지급합니까?",
        options: ["사원증", "식권", "교통비", "안전화"], answer: 0,
        sourceUrl: "sinbunjeung.html", sourceTitle: "ID Card" },
      { id: "L13", audioText: "남자: 다음 주에 회사를 그만둬요. 여자: 왜 그만두세요?", question: "남자는 다음 주에 무엇을 합니까?",
        options: ["이직 준비를 한다", "휴가를 간다", "출장을 간다", "회사를 그만둔다"], answer: 3,
        sourceUrl: "sajik.html", sourceTitle: "Resignation" },
      { id: "L14", audioText: "남자: 이번 달 세금이 얼마 나왔어요? 여자: 몇만 원 나왔어요.", question: "무엇에 대해 이야기하고 있습니까?",
        options: ["수당", "세금", "상여금", "월급"], answer: 1,
        sourceUrl: "segeum.html", sourceTitle: "Tax" },
      { id: "L15", audioText: "여권을 꼭 가지고 다니세요.", question: "무엇을 가지고 다니라고 했습니까?",
        options: ["여권", "우산", "지갑", "휴대폰"], answer: 0,
        sourceUrl: "yeogwon.html", sourceTitle: "Passport" },
      { id: "L16", audioText: "남자: 비자 연장 신청했어요? 여자: 네, 지난주에 했어요.", question: "여자는 언제 비자 연장을 신청했습니까?",
        options: ["오늘", "다음 달", "내일", "지난주"], answer: 3,
        sourceUrl: "cheryuyeonjang.html", sourceTitle: "Extension of Stay" },
      { id: "L17", audioText: "포장한 제품은 창고로 옮겨 주세요.", question: "포장한 제품은 어디로 옮겨야 합니까?",
        options: ["식당", "사무실", "창고", "주차장"], answer: 2,
        sourceUrl: "pojang.html", sourceTitle: "Packaging" },
      { id: "L18", audioText: "남자: 오늘 검사에서 불량품이 나왔어요. 여자: 몇 개나 나왔어요?", question: "무엇에 대해 이야기하고 있습니까?",
        options: ["견본품", "불량품", "원자재", "완성품"], answer: 1,
        sourceUrl: "bulryangpum.html", sourceTitle: "Defective Product" },
      { id: "L19", audioText: "이 자재는 조심히 다뤄 주세요. 깨지기 쉽습니다.", question: "이 자재를 어떻게 다뤄야 합니까?",
        options: ["빨리 옮겨야 한다", "밖에 둬야 한다", "버려야 한다", "조심히 다뤄야 한다"], answer: 3,
        sourceUrl: "wonjajae.html", sourceTitle: "Raw Materials" },
      { id: "L20", audioText: "남자: 다음 달에 최저임금이 오른대요. 여자: 그래요? 잘됐네요.", question: "다음 달에 무엇이 오릅니까?",
        options: ["집세", "물가", "기름값", "최저임금"], answer: 3,
        sourceUrl: "choejeoimgeum.html", sourceTitle: "Minimum Wage" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n물건을 나르거나 옮길 때 타는 큰 차입니다.",
        options: ["자전거", "비행기", "트럭", "배"], answer: 2,
        sourceUrl: "unban.html", sourceTitle: "Transport" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n음식을 넣어서 차갑게 보관하는 가전제품입니다.",
        options: ["냉장고", "세탁기", "전자레인지", "청소기"], answer: 0,
        sourceUrl: "electronics.html", sourceTitle: "Electronics" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 침대에 누워서 눈을 감고 자고 있습니다.",
        options: ["요리하고 있습니다.", "자고 있습니다.", "일하고 있습니다.", "운전하고 있습니다."], answer: 1,
        sourceUrl: "bed.html", sourceTitle: "Bed" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n빨간 바탕에 불꽃 모양이 그려진 표지판입니다.",
        options: ["미끄러우니 조심하세요.", "불이 날 수 있으니 조심하세요.", "전기가 흐르니 조심하세요.", "무거우니 조심하세요."], answer: 1,
        sourceUrl: "hwajae.html", sourceTitle: "Fire" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n저는 아침 8시에 회사___ 도착해요.",
        options: ["회사를 도착해요.", "회사에서 도착해요.", "회사가 도착해요.", "회사에 도착해요."], answer: 3,
        sourceUrl: "company.html", sourceTitle: "Company" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n출근하기 전에 얼굴을 ______.",
        options: ["씻으요.", "씻아요.", "씻어요.", "씻었요."], answer: 2,
        sourceUrl: "morning.html", sourceTitle: "Morning" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"기차 운행 시간: 오전 6시 ~ 오후 11시 (배차 간격 15분)\"\n\n기차는 몇 분마다 옵니까?",
        options: ["6분마다", "15분마다", "11분마다", "30분마다"], answer: 1,
        sourceUrl: "train.html", sourceTitle: "Train" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n주방",
        options: ["운동", "쇼핑", "요리", "잠"], answer: 2,
        sourceUrl: "kitchen.html", sourceTitle: "Kitchen" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n부품",
        options: ["회사 대표를 말합니다.", "기계나 제품을 만드는 데 쓰이는 작은 조각입니다.", "월급을 받는 날입니다.", "근로자가 쉬는 곳입니다."], answer: 1,
        sourceUrl: "bupum.html", sourceTitle: "Parts" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"이번 달 상여금은 급여와 함께 지급됩니다. 지급일은 25일입니다.\"\n\n상여금은 언제 지급됩니까?",
        options: ["1일", "25일", "15일", "30일"], answer: 1,
        sourceUrl: "sangyeogeum.html", sourceTitle: "Bonus" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n지급 방법: _____________",
        options: ["가족 모임", "생일 선물", "계좌 이체", "출근 시간"], answer: 2,
        sourceUrl: "gyejwabeonho.html", sourceTitle: "Account Number" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n기계 소리가 이상하면 ______ 반장님께 알려야 합니다.",
        options: ["즉시히", "즉시", "즉시하게", "즉시로"], answer: 1,
        sourceUrl: "ojakdong.html", sourceTitle: "Malfunction" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n물건이 도착하면 ______ 수량을 확인해야 합니다.",
        options: ["먼저가", "먼저", "먼저를", "먼저는"], answer: 1,
        sourceUrl: "suryang.html", sourceTitle: "Quantity" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n오늘은 잔업이 있어서 ______ 집에 갈 수 없습니다.",
        options: ["일찍", "일찍이는", "일찍게", "일찍히"], answer: 0,
        sourceUrl: "janeop.html", sourceTitle: "Remaining Work" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n몸이 안 좋으면 무리하지 말고 팀장님께 ______",
        options: ["말씀드리는 것이 좋습니다.", "말씀드리지 않는 것이 좋습니다.", "말씀드릴 수 없습니다.", "말씀드려야 안 됩니다."], answer: 0,
        sourceUrl: "timjang.html", sourceTitle: "Team Leader" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n밤에 어두운 길을 걸을 때는 ______ 이것을 착용하면 차량 운전자가 멀리서도 알아볼 수 있습니다.",
        options: ["마스크를 착용해야 합니다.", "야광 조끼를 착용해야 합니다.", "장화를 신어야 합니다.", "보호 장갑을 구매해야 합니다."], answer: 1,
        sourceUrl: "anjeon_gyoyuk.html", sourceTitle: "Safety Training" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n선을 정확하게 재거나 물건의 길이를 측정할 때 쓰는 도구입니다.",
        options: ["망치", "줄자", "가위", "드라이버"], answer: 1,
        sourceUrl: "julja.html", sourceTitle: "Tape Measure" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n한국의 대중교통은 버스, 지하철, 택시가 있습니다. 출퇴근 시간에는 사람이 많아서 복잡합니다. 교통카드를 사용하면 편리하게 이용할 수 있습니다.",
        options: ["대중교통 이용", "음식 문화", "계절별 옷차림", "한국의 명절"], answer: 0,
        sourceUrl: "transport.html", sourceTitle: "Transport" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"기숙사 이용 안내: 기숙사는 회사 근로자만 이용할 수 있습니다. 외부인 출입은 금지되어 있으며, 밤 12시 이후에는 조용히 해 주시기 바랍니다.\"",
        options: ["외부인도 자유롭게 출입할 수 있습니다.", "밤 12시 이후에는 시끄러워도 됩니다.", "기숙사는 회사 근로자만 이용할 수 있습니다.", "기숙사는 아무나 이용할 수 있습니다."], answer: 2,
        sourceUrl: "chulipgeumji.html", sourceTitle: "No Entry" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"근로계약서에는 근무 시간, 급여, 휴일 등이 명시되어 있습니다. 근로자와 사업주는 각각 한 부씩 보관해야 합니다.\"",
        options: ["근로계약서에는 급여만 적혀 있습니다.", "근로자와 사업주가 각각 한 부씩 보관해야 합니다.", "근로자는 보관할 필요가 없습니다.", "사업주만 보관하면 됩니다."], answer: 1,
        sourceUrl: "geunro-gyeyakseo.html", sourceTitle: "Labor Contract" }
    ]
  },
  {
    id: "set_03",
    title: "EPS-TOPIK Mock Test #3",
    free: true,
    listening: [
      { id: "L01", audioText: "미안해요, 늦었어요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["괜찮아요.", "가까워요.", "비싸요.", "맛있어요."], answer: 0,
        sourceUrl: "gwaenchanayo1.html", sourceTitle: "It's Okay" },
      { id: "L02", audioText: "많이 피곤해 보여요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 좀 피곤해요.", "네, 배고파요.", "아니요, 추워요.", "아니요, 늦었어요."], answer: 0,
        sourceUrl: "pigon1.html", sourceTitle: "Im Tired" },
      { id: "L03", audioText: "천천히 말해 주세요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 천천히 말할게요.", "네, 빨리 갈게요.", "아니요, 비싸요.", "아니요, 늦었어요."], answer: 0,
        sourceUrl: "cheoncheonhi1.html", sourceTitle: "Please Speak Slowly" },
      { id: "L04", audioText: "이해했어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 늦었어요.", "네, 이해했어요.", "네, 비싸요.", "아니요, 배고파요."], answer: 1,
        sourceUrl: "ihae1.html", sourceTitle: "I Understand" },
      { id: "L05", audioText: "도와주세요.", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 비싸요.", "아니요, 맛있어요.", "아니요, 가까워요.", "네, 도와드릴게요."], answer: 3,
        sourceUrl: "dowajuseyo1.html", sourceTitle: "Help Me" },
      { id: "L06", audioText: "남자: 다친 곳이 어디예요? 여자: 손가락을 다쳤어요.", question: "여자는 어디를 다쳤습니까?",
        options: ["다리", "손가락", "허리", "머리"], answer: 1,
        sourceUrl: "busang.html", sourceTitle: "Injury" },
      { id: "L07", audioText: "남자: 상처에 뭐 발랐어요? 여자: 연고를 발랐어요.", question: "여자는 상처에 무엇을 발랐습니까?",
        options: ["기름", "연고", "소금", "물"], answer: 1,
        sourceUrl: "yeongo.html", sourceTitle: "Ointment" },
      { id: "L08", audioText: "남자: 이 도구 이름이 뭐예요? 여자: 스패너예요.", question: "이 도구의 이름은 무엇입니까?",
        options: ["가위", "망치", "스패너", "드라이버"], answer: 2,
        sourceUrl: "seupaeneo_renchi.html", sourceTitle: "Spanner / Wrench" },
      { id: "L09", audioText: "안전 고글을 꼭 착용하세요.", question: "무엇을 착용해야 합니까?",
        options: ["장갑", "안전 고글", "마스크", "모자"], answer: 1,
        sourceUrl: "boangyeong.html", sourceTitle: "Safety Goggles" },
      { id: "L10", audioText: "귀마개는 소음이 심한 곳에서 착용하세요.", question: "귀마개는 언제 착용해야 합니까?",
        options: ["비가 올 때", "더울 때", "추울 때", "소음이 심할 때"], answer: 3,
        sourceUrl: "gwimagae.html", sourceTitle: "Earplug" },
      { id: "L11", audioText: "화재가 발생하면 즉시 비상구로 대피하세요.", question: "화재 발생 시 어떻게 해야 합니까?",
        options: ["엘리베이터를 탄다", "비상구로 대피한다", "창문을 연다", "계속 일한다"], answer: 1,
        sourceUrl: "bisanggu.html", sourceTitle: "Emergency Exit" },
      { id: "L12", audioText: "남자: 소화기는 어디에 있어요? 여자: 저기 벽에 걸려 있어요.", question: "소화기는 어디에 있습니까?",
        options: ["벽에 걸려 있다", "바닥에 있다", "창고에 있다", "사무실에 있다"], answer: 0,
        sourceUrl: "sohwagi.html", sourceTitle: "Fire Extinguisher" },
      { id: "L13", audioText: "이 구역은 흡연 구역입니다.", question: "이 구역은 무엇을 하는 곳입니까?",
        options: ["흡연", "회의", "휴식", "식사"], answer: 0,
        sourceUrl: "heupyeonguyeok.html", sourceTitle: "Smoking Area" },
      { id: "L14", audioText: "남자: 다음 정류장에서 내려 주세요. 여자: 네, 알겠습니다.", question: "남자는 여자에게 무엇을 부탁했습니까?",
        options: ["창문을 열기", "문을 닫기", "빨리 가기", "다음 정류장에서 내리기"], answer: 3,
        sourceUrl: "yeogiseosewojuseyo1.html", sourceTitle: "Stop Here" },
      { id: "L15", audioText: "이 길로 쭉 가다가 오른쪽으로 도세요.", question: "어느 방향으로 가야 합니까?",
        options: ["아래쪽", "오른쪽", "위쪽", "왼쪽"], answer: 1,
        sourceUrl: "oreunjjogeurodoseyo1.html", sourceTitle: "Turn Right" },
      { id: "L16", audioText: "남자: 길을 잃었어요. 여기가 어디예요? 여자: 여기는 시청 앞이에요.", question: "남자는 지금 어떤 상황입니까?",
        options: ["길을 잃었다", "배가 고프다", "돈이 없다", "시간이 없다"], answer: 0,
        sourceUrl: "gireulireosseoyo1.html", sourceTitle: "I'm Lost" },
      { id: "L17", audioText: "남자: 오늘 왜 일찍 왔어요? 여자: 차가 안 막혀서 일찍 왔어요.", question: "여자는 왜 일찍 왔습니까?",
        options: ["차가 안 막혀서", "늦잠을 자서", "버스를 놓쳐서", "길을 잃어서"], answer: 0,
        sourceUrl: "iljjikwasseoyo1.html", sourceTitle: "I'm Early" },
      { id: "L18", audioText: "질문 있으면 손을 들어 주세요.", question: "질문이 있으면 어떻게 해야 합니까?",
        options: ["문을 두드린다", "손을 든다", "크게 말한다", "자리에서 일어난다"], answer: 1,
        sourceUrl: "jilmunisseoyo1.html", sourceTitle: "I Have a Question" },
      { id: "L19", audioText: "남자: 이 서류 다 작성했어요? 여자: 네, 다 작성했어요.", question: "여자는 서류를 어떻게 했습니까?",
        options: ["아직 안 했다", "잃어버렸다", "버렸다", "다 작성했다"], answer: 3,
        sourceUrl: "sincheongseo.html", sourceTitle: "Application Form" },
      { id: "L20", audioText: "이 제품에는 시리얼 번호가 붙어 있습니다.", question: "이 제품에 무엇이 붙어 있습니까?",
        options: ["사용설명서", "보증서", "시리얼 번호", "가격표"], answer: 2,
        sourceUrl: "ilryeonbeonho.html", sourceTitle: "Serial Number" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n못을 박거나 물건을 두드릴 때 쓰는 도구입니다.",
        options: ["망치", "펜치", "드라이버", "가위"], answer: 0,
        sourceUrl: "mangchi.html", sourceTitle: "Hammer" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n나사를 돌려서 조이거나 풀 때 쓰는 도구입니다.",
        options: ["망치", "줄자", "가위", "드라이버"], answer: 3,
        sourceUrl: "deuraibeo.html", sourceTitle: "Screwdriver" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 서서 큰 소리로 전화 통화를 하고 있습니다.",
        options: ["운전을 하고 있습니다.", "요리를 하고 있습니다.", "잠을 자고 있습니다.", "전화를 하고 있습니다."], answer: 3,
        sourceUrl: "friend.html", sourceTitle: "Friend" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n초록 바탕에 걷는 사람 모양이 그려진 표지판입니다.",
        options: ["이 길은 위험합니다.", "이 길은 공사 중입니다.", "이 길은 출입 금지입니다.", "이 길로 대피하세요."], answer: 3,
        sourceUrl: "pinangu.html", sourceTitle: "Escape Exit" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n다친 손가락___ 붕대를 감았어요.",
        options: ["손가락을 붕대를 감았어요.", "손가락이 붕대를 감았어요.", "손가락에 붕대를 감았어요.", "손가락에서 붕대를 감았어요."], answer: 2,
        sourceUrl: "bungdae.html", sourceTitle: "Bandage" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n작업 전에 안전화를 ______.",
        options: ["신아요.", "신어요.", "신었요.", "신으요."], answer: 1,
        sourceUrl: "anjeonhwa.html", sourceTitle: "Safety Shoes" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"소방 훈련 안내: 이번 주 금요일 오후 2시에 실시합니다. 전 직원 참여 필수입니다.\"\n\n소방 훈련은 언제 실시합니까?",
        options: ["다음 주 월요일", "이번 주 금요일 오후 2시", "이번 달 말", "오늘 오전"], answer: 1,
        sourceUrl: "anjeon_jeomgeom.html", sourceTitle: "Safety Inspection" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n구급함",
        options: ["음식을 보관하는 상자입니다.", "월급을 계산하는 상자입니다.", "다쳤을 때 필요한 약과 도구가 들어 있는 상자입니다.", "서류를 보관하는 상자입니다."], answer: 2,
        sourceUrl: "gugeupham.html", sourceTitle: "First Aid Kit" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n소독약",
        options: ["상처를 깨끗하게 소독할 때 사용합니다.", "옷을 세탁할 때 사용합니다.", "바닥을 청소할 때 사용합니다.", "기계를 수리할 때 사용합니다."], answer: 0,
        sourceUrl: "sodongyak.html", sourceTitle: "Antiseptic" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"산업재해 신고 안내: 사고가 발생하면 즉시 반장님이나 관리자에게 알리세요.\"\n\n사고가 발생하면 누구에게 알려야 합니까?",
        options: ["반장님이나 관리자", "가족", "친구", "경찰"], answer: 0,
        sourceUrl: "singo.html", sourceTitle: "Report / Notification" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n비상 연락처: _____________",
        options: ["생일 날짜", "좋아하는 음식", "취미", "소방서 전화번호"], answer: 3,
        sourceUrl: "bisang_yeollakcheo.html", sourceTitle: "Emergency Contact" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n작업 중 어지러우면 ______ 쉬어야 합니다.",
        options: ["즉시히", "즉시", "즉시로", "즉시하게"], answer: 1,
        sourceUrl: "eojireumjeung.html", sourceTitle: "Dizziness" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n쓰러진 사람을 발견하면 ______ 심폐소생술을 실시해야 합니다.",
        options: ["바로는", "바로", "바로가", "바로를"], answer: 1,
        sourceUrl: "simpyesosaengsul.html", sourceTitle: "CPR" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n화재가 나면 엘리베이터를 타지 말고 ______ 대피해야 합니다.",
        options: ["계단도", "계단으로", "계단이", "계단을"], answer: 1,
        sourceUrl: "daepi.html", sourceTitle: "Evacuation" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n가스 냄새가 나면 창문을 열고 ______",
        options: ["환기시키지 않는 것이 좋습니다.", "환기해야 안 됩니다.", "환기시키는 것이 좋습니다.", "환기할 수 없습니다."], answer: 2,
        sourceUrl: "gaseunuchul.html", sourceTitle: "Gas Leak" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n전선이 벗겨진 곳은 만지지 말고 ______ 이것을 지키면 감전 사고를 막을 수 있습니다.",
        options: ["절연 장갑을 착용해야 합니다.", "바로 잡아당겨야 합니다.", "맨손으로 만져야 합니다.", "물을 뿌려야 합니다."], answer: 0,
        sourceUrl: "gamjeon.html", sourceTitle: "Electric Shock" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n전기가 통하지 않도록 막아 주는 것으로, 감전 사고를 예방하는 데 씁니다.",
        options: ["소화기", "절연체", "줄자", "펜치"], answer: 1,
        sourceUrl: "jeoryeon.html", sourceTitle: "Insulation" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n작업장에서는 항상 안전 수칙을 지켜야 합니다. 보호 장비를 착용하고, 위험한 구역에는 함부로 들어가지 않아야 합니다. 사고가 발생하면 즉시 신고해야 합니다.",
        options: ["작업장 안전 수칙", "월급 계산 방법", "휴가 신청 방법", "제품 포장 방법"], answer: 0,
        sourceUrl: "anjeon_pyojipan.html", sourceTitle: "Safety Sign" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"비상벨 사용 안내: 위급한 상황이 발생하면 비상벨을 누르세요. 비상벨을 누르면 관리자에게 즉시 연락이 갑니다.\"",
        options: ["비상벨을 누르면 관리자에게 연락이 갑니다.", "비상벨을 누르면 아무 일도 일어나지 않습니다.", "비상벨은 사용할 수 없습니다.", "비상벨은 평소에도 눌러도 됩니다."], answer: 0,
        sourceUrl: "bisangbel.html", sourceTitle: "Emergency Bell" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"위험물 취급 안내: 위험물은 지정된 장소에만 보관해야 합니다. 화기 근처에는 절대 두면 안 됩니다.\"",
        options: ["위험물은 아무 곳에나 보관해도 됩니다.", "위험물 취급에는 규정이 없습니다.", "위험물은 지정된 장소에만 보관해야 합니다.", "위험물은 화기 근처에 둬도 됩니다."], answer: 2,
        sourceUrl: "yuhaemuljil.html", sourceTitle: "Hazardous Material" }
    ]
  },
  {
    id: "set_04",
    title: "EPS-TOPIK Mock Test #4",
    free: true,
    listening: [
      { id: "L01", audioText: "오늘 기분이 어때요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["좋아요.", "멀어요.", "비싸요.", "늦었어요."], answer: 0,
        sourceUrl: "gibun1.html", sourceTitle: "I Feel Good" },
      { id: "L02", audioText: "지금 바빠요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 늦었어요.", "네, 맛있어요.", "네, 좀 바빠요.", "아니요, 커요."], answer: 2,
        sourceUrl: "bappa1.html", sourceTitle: "Im Busy" },
      { id: "L03", audioText: "오늘 시간 있어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 비싸요.", "네, 멀어요.", "아니요, 추워요.", "네, 시간 있어요."], answer: 3,
        sourceUrl: "sigan1.html", sourceTitle: "Im Free" },
      { id: "L04", audioText: "배 안 고파요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 비싸요.", "아니요, 늦었어요.", "네, 배고파요.", "아니요, 멀어요."], answer: 2,
        sourceUrl: "baegopa1.html", sourceTitle: "I'm Hungry" },
      { id: "L05", audioText: "졸려요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 비싸요.", "아니요, 가까워요.", "아니요, 커요.", "네, 졸려요."], answer: 3,
        sourceUrl: "jollyeo1.html", sourceTitle: "Im Sleepy" },
      { id: "L06", audioText: "남자: 오늘 공정이 몇 개 남았어요? 여자: 세 개 남았어요.", question: "공정이 몇 개 남았습니까?",
        options: ["한 개", "세 개", "두 개", "다섯 개"], answer: 1,
        sourceUrl: "gongjeong.html", sourceTitle: "Process" },
      { id: "L07", audioText: "남자: 조립은 다 끝났어요? 여자: 네, 방금 끝났어요.", question: "여자는 무엇을 끝냈습니까?",
        options: ["조립", "배송", "검사", "포장"], answer: 0,
        sourceUrl: "jorip.html", sourceTitle: "Assembly" },
      { id: "L08", audioText: "이 제품은 용접이 필요합니다.", question: "이 제품에 무엇이 필요합니까?",
        options: ["포장", "도색", "세척", "용접"], answer: 3,
        sourceUrl: "yongjeop.html", sourceTitle: "Welding" },
      { id: "L09", audioText: "남자: 완성품은 어디에 쌓아 두면 돼요? 여자: 저쪽 팔레트 위에 쌓아 주세요.", question: "완성품을 어디에 쌓아야 합니까?",
        options: ["출입구", "팔레트 위", "바닥", "창문 옆"], answer: 1,
        sourceUrl: "wanseongpum.html", sourceTitle: "Finished Product" },
      { id: "L10", audioText: "오늘 납기일은 내일까지입니다.", question: "납기일은 언제까지입니까?",
        options: ["이번 달 말까지", "오늘까지", "다음 주까지", "내일까지"], answer: 3,
        sourceUrl: "napgi.html", sourceTitle: "Delivery" },
      { id: "L11", audioText: "남자: 불량품은 따로 분류해 주세요. 여자: 네, 알겠습니다.", question: "불량품은 어떻게 해야 합니까?",
        options: ["버린다", "따로 분류한다", "재사용한다", "그냥 포장한다"], answer: 1,
        sourceUrl: "bunryu.html", sourceTitle: "Sorting / Classification" },
      { id: "L12", audioText: "이 부품은 정확한 치수로 측정해야 합니다.", question: "이 부품에 대해 무엇을 해야 합니까?",
        options: ["빠른 포장", "색깔 확인", "정확한 치수 측정", "무게 확인"], answer: 2,
        sourceUrl: "cheukjeong.html", sourceTitle: "Measurement" },
      { id: "L13", audioText: "남자: 기계 설정을 바꿨어요? 여자: 네, 방금 바꿨어요.", question: "여자는 무엇을 했습니까?",
        options: ["기계를 껐다", "기계 설정을 바꿨다", "기계를 청소했다", "기계를 옮겼다"], answer: 1,
        sourceUrl: "seoljeong.html", sourceTitle: "Setting / Configuration" },
      { id: "L14", audioText: "이 기계는 시운전 중입니다.", question: "이 기계는 지금 어떤 상태입니까?",
        options: ["시운전 중이다", "고장났다", "꺼져 있다", "수리 중이다"], answer: 0,
        sourceUrl: "siunjeon.html", sourceTitle: "Test Run" },
      { id: "L15", audioText: "폐기물은 정해진 곳에 버려 주세요.", question: "폐기물을 어디에 버려야 합니까?",
        options: ["창고", "아무 곳", "사무실", "정해진 곳"], answer: 3,
        sourceUrl: "pyegimul.html", sourceTitle: "Waste Material" },
      { id: "L16", audioText: "남자: 재고가 얼마나 남았어요? 여자: 백 개 정도 남았어요.", question: "재고가 얼마나 남았습니까?",
        options: ["백 개 정도", "십 개 정도", "오십 개 정도", "천 개 정도"], answer: 0,
        sourceUrl: "jaego.html", sourceTitle: "Inventory / Stock" },
      { id: "L17", audioText: "남자: 생산량이 목표에 도달했어요? 여자: 아직 못 했어요.", question: "생산량은 목표에 도달했습니까?",
        options: ["이미 도달했다", "초과했다", "아직 못 했다", "알 수 없다"], answer: 2,
        sourceUrl: "saengsallyang.html", sourceTitle: "Production Volume" },
      { id: "L18", audioText: "이 기계는 과부하로 자동 정지되었습니다.", question: "이 기계는 왜 정지되었습니까?",
        options: ["전기가 없어서", "사람이 꺼서", "고장이 나서", "과부하 때문에"], answer: 3,
        sourceUrl: "gwabuhwa.html", sourceTitle: "Overload" },
      { id: "L19", audioText: "남자: 품질 검사는 언제 해요? 여자: 생산 끝난 후에 바로 해요.", question: "품질 검사는 언제 합니까?",
        options: ["퇴근 후에", "점심시간에", "생산 끝난 후 바로", "생산 시작 전"], answer: 2,
        sourceUrl: "pumjilgwanri.html", sourceTitle: "Quality Control" },
      { id: "L20", audioText: "이 상자에는 바코드를 붙여 주세요.", question: "이 상자에 무엇을 붙여야 합니까?",
        options: ["경고문", "바코드", "가격표", "이름표"], answer: 1,
        sourceUrl: "bakodeu.html", sourceTitle: "Barcode" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n물건의 무게를 재는 도구입니다.",
        options: ["시계", "줄자", "온도계", "저울"], answer: 3,
        sourceUrl: "muge.html", sourceTitle: "Weight" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n물건을 눌러서 압축할 때 쓰는 기계입니다.",
        options: ["프레스기", "가위", "망치", "드라이버"], answer: 0,
        sourceUrl: "peureseu.html", sourceTitle: "Pressing" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 기계 앞에 서서 부품을 가공하고 있습니다.",
        options: ["전화를 하고 있습니다.", "밥을 먹고 있습니다.", "부품을 가공하고 있습니다.", "잠을 자고 있습니다."], answer: 2,
        sourceUrl: "gagong.html", sourceTitle: "Processing / Machining" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n노란 바탕에 상자가 떨어지는 그림이 그려진 표지판입니다.",
        options: ["낙하물을 조심하세요.", "미끄러우니 조심하세요.", "전기가 흐르니 조심하세요.", "불이 날 수 있으니 조심하세요."], answer: 0,
        sourceUrl: "pason.html", sourceTitle: "Damage / Breakage" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n완성된 상자___ 창고로 옮겼어요.",
        options: ["상자도 창고로 옮겼어요.", "상자에서 창고로 옮겼어요.", "상자가 창고로 옮겼어요.", "상자를 창고로 옮겼어요."], answer: 3,
        sourceUrl: "mukkeum.html", sourceTitle: "Bundle" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n기계를 사용하기 전에 설명서를 ______.",
        options: ["읽으요.", "읽아요.", "읽었요.", "읽어요."], answer: 3,
        sourceUrl: "gwalli.html", sourceTitle: "Management / Care" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"생산 목표 안내: 이번 주 목표 수량은 5,000개입니다. 매일 진행 상황을 게시판에 기록해 주세요.\"\n\n이번 주 목표 수량은 몇 개입니까?",
        options: ["5개", "500개", "5,000개", "50,000개"], answer: 2,
        sourceUrl: "mokpyoryang.html", sourceTitle: "Target Quantity" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n효율",
        options: ["휴가를 가는 것입니다.", "적은 시간과 힘으로 많은 일을 하는 것입니다.", "월급을 받는 것입니다.", "물건을 포장하는 것입니다."], answer: 1,
        sourceUrl: "neungnyul.html", sourceTitle: "Efficiency" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n표본",
        options: ["완성된 모든 제품입니다.", "품질을 확인하기 위해 미리 만든 제품입니다.", "포장 재료를 말합니다.", "불량품을 말합니다."], answer: 1,
        sourceUrl: "sample_sijepum.html", sourceTitle: "Sample / Prototype" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"품질 개선 회의 안내: 매주 월요일 오전 10시에 실시합니다. 관련 부서는 모두 참석해 주세요.\"\n\n품질 개선 회의는 언제 합니까?",
        options: ["매일 오후", "금요일마다", "매주 월요일 오전 10시", "매달 첫째 주"], answer: 2,
        sourceUrl: "gongjeonggaeseon.html", sourceTitle: "Improvement" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n규격 확인 방법: _____________",
        options: ["가족 모임", "생일 선물", "출근 시간", "줄자로 측정"], answer: 3,
        sourceUrl: "gyugyeok.html", sourceTitle: "Standard / Specification" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n부품이 부족하면 ______ 담당자에게 알려야 합니다.",
        options: ["즉시하게", "즉시히", "즉시", "즉시로"], answer: 2,
        sourceUrl: "suryangbujok.html", sourceTitle: "Shortage of Quantity" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n기계를 점검할 때는 ______ 전원을 꺼야 합니다.",
        options: ["먼저", "먼저는", "먼저가", "먼저를"], answer: 0,
        sourceUrl: "jeomgeom.html", sourceTitle: "Checking / Inspection" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n포장이 끝나면 ______ 배송 준비를 합니다.",
        options: ["바로가", "바로를", "바로는", "바로"], answer: 3,
        sourceUrl: "chulha.html", sourceTitle: "Shipping Out" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n불량품을 발견하면 반장님께 ______",
        options: ["보고해야 안 됩니다.", "보고하지 않는 것이 좋습니다.", "보고할 수 없습니다.", "보고하는 것이 좋습니다."], answer: 3,
        sourceUrl: "gyoche.html", sourceTitle: "Replacement" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n무거운 자재를 옮길 때는 ______ 이렇게 하면 허리 부상을 막을 수 있습니다.",
        options: ["한 손으로 빨리 들어야 합니다.", "허리를 펴고 다리 힘으로 들어야 합니다.", "숨을 참고 들어야 합니다.", "허리를 굽히고 팔 힘으로 들어야 합니다."], answer: 1,
        sourceUrl: "bunhae.html", sourceTitle: "Disassembly" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n물건에 붙여서 제품 정보를 표시하는 종이나 스티커입니다.",
        options: ["줄자", "가위", "망치", "라벨"], answer: 3,
        sourceUrl: "rabelling.html", sourceTitle: "Labeling" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n공장에서는 매일 생산량을 기록하고 목표와 비교합니다. 목표에 미달하면 원인을 분석하고 개선 방법을 찾습니다. 이러한 과정을 통해 효율을 높일 수 있습니다.",
        options: ["휴가 신청 절차", "생산 관리와 개선", "직원 채용 방법", "급여 계산 방법"], answer: 1,
        sourceUrl: "jakdong.html", sourceTitle: "Operation" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"재고 관리 안내: 매주 금요일 재고를 확인하고 기록합니다. 부족한 자재는 다음 주 월요일까지 주문해야 합니다.\"",
        options: ["부족한 자재는 주문할 필요가 없습니다.", "재고는 확인하지 않습니다.", "재고 관리는 한 달에 한 번 합니다.", "매주 금요일 재고를 확인합니다."], answer: 3,
        sourceUrl: "gadong.html", sourceTitle: "Operation / Running" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"폐기물 처리 안내: 재활용 가능한 폐기물은 따로 분리해서 배출합니다. 일반 폐기물과 섞지 않도록 주의해 주세요.\"",
        options: ["재활용 가능한 폐기물은 따로 분리해서 배출합니다.", "모든 폐기물은 같이 버려도 됩니다.", "폐기물은 아무 데나 버려도 됩니다.", "재활용은 하지 않아도 됩니다."], answer: 0,
        sourceUrl: "jaehwalyong.html", sourceTitle: "Recycling" }
    ]
  },
  {
    id: "set_05",
    title: "EPS-TOPIK Mock Test #5",
    free: true,
    listening: [
      { id: "L01", audioText: "이거 뭐예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["빵이에요.", "일요일이에요.", "회사예요.", "친구예요."], answer: 0,
        sourceUrl: "bread.html", sourceTitle: "Bread" },
      { id: "L02", audioText: "무슨 계절을 좋아해요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["우산을 좋아해요.", "봄을 좋아해요.", "연필을 좋아해요.", "책상을 좋아해요."], answer: 1,
        sourceUrl: "spring.html", sourceTitle: "Spring" },
      { id: "L03", audioText: "가족이 몇 명이에요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네 명이에요.", "월요일이에요.", "가방이에요.", "교실이에요."], answer: 0,
        sourceUrl: "family.html", sourceTitle: "Family" },
      { id: "L04", audioText: "오늘 뭐 먹었어요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["서울에 갔어요.", "친구를 만났어요.", "일곱 시예요.", "김치찌개를 먹었어요."], answer: 3,
        sourceUrl: "soup.html", sourceTitle: "Soup" },
      { id: "L05", audioText: "취미가 뭐예요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["가까워요.", "운동이에요.", "월요일이에요.", "비싸요."], answer: 1,
        sourceUrl: "hobbies.html", sourceTitle: "Hobbies" },
      { id: "L06", audioText: "남자: 외국인등록증 가지고 왔어요? 여자: 네, 여기 있어요.", question: "여자는 무엇을 가지고 왔습니까?",
        options: ["통장", "여권", "비자", "외국인등록증"], answer: 3,
        sourceUrl: "oegugindeungrokjeung.html", sourceTitle: "Alien Registration Card" },
      { id: "L07", audioText: "남자: 비자는 언제까지예요? 여자: 내년 3월까지예요.", question: "여자의 비자는 언제까지입니까?",
        options: ["올해 12월까지", "내년 3월까지", "이번 달까지", "다음 주까지"], answer: 1,
        sourceUrl: "bija.html", sourceTitle: "Visa" },
      { id: "L08", audioText: "남자: 체류 기간이 얼마나 남았어요? 여자: 두 달 남았어요.", question: "여자의 체류 기간은 얼마나 남았습니까?",
        options: ["일주일", "일 년", "한 달", "두 달"], answer: 3,
        sourceUrl: "cheryugigan.html", sourceTitle: "Period of Stay" },
      { id: "L09", audioText: "재입국 허가를 미리 신청해야 합니다.", question: "무엇을 미리 신청해야 합니까?",
        options: ["비자 연장", "건강보험", "외국인등록증", "재입국 허가"], answer: 3,
        sourceUrl: "jaeipguk.html", sourceTitle: "Re-entry" },
      { id: "L10", audioText: "고용센터에서 취업 상담을 받을 수 있습니다.", question: "고용센터에서 무엇을 받을 수 있습니까?",
        options: ["취업 상담", "비자 발급", "여권 발급", "건강 검진"], answer: 0,
        sourceUrl: "goyongcenter.html", sourceTitle: "Employment Center" },
      { id: "L11", audioText: "남자: 건강보험료가 얼마예요? 여자: 매달 오만원 정도예요.", question: "건강보험료는 얼마입니까?",
        options: ["매달 오천원", "매달 이십만원", "매달 오만원 정도", "매달 십만원"], answer: 2,
        sourceUrl: "gukmingeongangboheom.html", sourceTitle: "National Health Insurance" },
      { id: "L12", audioText: "이 도장을 서류에 찍어 주세요.", question: "서류에 무엇을 찍어야 합니까?",
        options: ["날짜", "이름", "사진", "도장"], answer: 3,
        sourceUrl: "dojang.html", sourceTitle: "Stamp / Seal" },
      { id: "L13", audioText: "남자: 오늘 환율이 얼마예요? 여자: 천이백 원 정도예요.", question: "오늘 환율은 얼마입니까?",
        options: ["오백 원", "천 원", "이천 원", "천이백 원 정도"], answer: 3,
        sourceUrl: "hwanyul.html", sourceTitle: "Exchange Rate" },
      { id: "L14", audioText: "남자: 고향에 돈을 보냈어요? 여자: 네, 어제 송금했어요.", question: "여자는 언제 송금했습니까?",
        options: ["내일", "오늘", "어제", "지난달"], answer: 2,
        sourceUrl: "songgeum.html", sourceTitle: "Money Transfer" },
      { id: "L15", audioText: "송금 수수료를 확인해 주세요.", question: "무엇을 확인해야 합니까?",
        options: ["주소", "송금 수수료", "전화번호", "생년월일"], answer: 1,
        sourceUrl: "susuryo.html", sourceTitle: "Fee" },
      { id: "L16", audioText: "남자: 재직증명서 발급받았어요? 여자: 네, 오늘 받았어요.", question: "여자는 무엇을 발급받았습니까?",
        options: ["비자", "건강진단서", "재직증명서", "졸업증명서"], answer: 2,
        sourceUrl: "jeungmyeongseo.html", sourceTitle: "Certificate" },
      { id: "L17", audioText: "서류 접수는 오전에만 가능합니다.", question: "서류 접수는 언제 가능합니까?",
        options: ["종일", "오후에만", "저녁에만", "오전에만"], answer: 3,
        sourceUrl: "jeopsu.html", sourceTitle: "Reception / Filing" },
      { id: "L18", audioText: "남자: 신청이 승인됐어요? 여자: 네, 어제 승인됐어요.", question: "신청은 언제 승인됐습니까?",
        options: ["다음 주", "어제", "오늘", "내일"], answer: 1,
        sourceUrl: "seungin.html", sourceTitle: "Approval" },
      { id: "L19", audioText: "남자: 서류에 동의 서명을 했어요? 여자: 네, 다 했어요.", question: "여자는 무엇을 했습니까?",
        options: ["서류 제출", "비용 납부", "사진 촬영", "동의 서명"], answer: 3,
        sourceUrl: "dongui.html", sourceTitle: "Consent / Agreement" },
      { id: "L20", audioText: "신분 확인을 위해 신분증을 보여 주세요.", question: "무엇을 보여 줘야 합니까?",
        options: ["통장", "여권 사진", "신분증", "계약서"], answer: 2,
        sourceUrl: "sinwon_hwagin.html", sourceTitle: "Identity Verification" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n하늘을 날아서 먼 나라로 이동할 때 타는 것입니다.",
        options: ["비행기", "기차", "배", "버스"], answer: 0,
        sourceUrl: "airplane.html", sourceTitle: "Airplane" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n비행기를 타고 내리는 곳입니다.",
        options: ["기차역", "항구", "버스터미널", "공항"], answer: 3,
        sourceUrl: "airport.html", sourceTitle: "Airport" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 부엌에서 채소를 썰고 있습니다.",
        options: ["잠을 자고 있습니다.", "요리를 하고 있습니다.", "운동을 하고 있습니다.", "청소를 하고 있습니다."], answer: 1,
        sourceUrl: "cooking.html", sourceTitle: "Cooking" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n파란 바탕에 흰색 화살표가 아래를 가리키는 표지판입니다.",
        options: ["여기서 기다리세요.", "이쪽으로 내려가세요.", "여기서 멈추세요.", "이쪽으로 올라가세요."], answer: 1,
        sourceUrl: "places.html", sourceTitle: "Places" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n이 서류___ 고용센터에 제출하세요.",
        options: ["서류를 고용센터에 제출하세요.", "서류도 고용센터에 제출하세요.", "서류가 고용센터에 제출하세요.", "서류에서 고용센터에 제출하세요."], answer: 0,
        sourceUrl: "goyongnodongbu.html", sourceTitle: "Ministry of Employment and Labor" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n서류를 제출하기 전에 내용을 ______.",
        options: ["확인하요.", "확인해서요.", "확인했요.", "확인해요."], answer: 3,
        sourceUrl: "eoryu.html", sourceTitle: "Documents" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"고용센터 운영 시간: 평일 오전 9시 ~ 오후 6시 (주말 휴무)\"\n\n고용센터는 언제까지 운영합니까?",
        options: ["오전 9시", "오후 6시", "오후 9시", "오전 6시"], answer: 1,
        sourceUrl: "goyongboheom.html", sourceTitle: "Employment Insurance" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n국민연금",
        options: ["나이가 들면 받는 연금 제도입니다.", "회사에서 주는 보너스입니다.", "병원비 지원 제도입니다.", "매달 내는 세금입니다."], answer: 0,
        sourceUrl: "gukminyeongeum.html", sourceTitle: "National Pension" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n산업재해",
        options: ["월급이 늦게 나오는 것입니다.", "휴가를 못 가는 것입니다.", "일을 하다가 다치거나 병에 걸리는 것입니다.", "계약이 끝나는 것입니다."], answer: 2,
        sourceUrl: "saneupjaehae.html", sourceTitle: "Industrial Accident" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"서류 접수 안내: 신청서는 이메일 또는 방문으로 접수할 수 있습니다. 접수 마감일은 이번 달 30일입니다.\"\n\n접수 마감일은 언제입니까?",
        options: ["이번 달 30일", "다음 달 30일", "이번 달 1일", "다음 달 1일"], answer: 0,
        sourceUrl: "geojeol.html", sourceTitle: "Rejection" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n지급 방법: _____________",
        options: ["출근 시간", "가족 모임", "현금 지급", "생일 선물"], answer: 2,
        sourceUrl: "money.html", sourceTitle: "Money" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n공항에 도착하면 ______ 짐을 찾아야 합니다.",
        options: ["먼저", "먼저는", "먼저가", "먼저를"], answer: 0,
        sourceUrl: "travel.html", sourceTitle: "Travel" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n장을 볼 때는 ______ 영수증을 받아야 합니다.",
        options: ["꼭이", "꼭도", "꼭은", "꼭"], answer: 3,
        sourceUrl: "market.html", sourceTitle: "Market" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n이사할 집을 구할 때는 ______ 여러 곳을 비교해 봐야 합니다.",
        options: ["미리는", "미리도", "미리가", "미리"], answer: 3,
        sourceUrl: "house.html", sourceTitle: "House" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n몸이 아프면 참지 말고 병원에 ______",
        options: ["갈 수 없습니다.", "가는 것이 좋습니다.", "가지 않는 것이 좋습니다.", "가야 안 됩니다."], answer: 1,
        sourceUrl: "health.html", sourceTitle: "Health" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n고향 가족에게 안부를 전할 때는 ______ 이렇게 하면 마음이 편안해집니다.",
        options: ["연락을 끊는 것이 좋습니다.", "전화를 자주 하는 것이 좋습니다.", "걱정하지 않아도 됩니다.", "답장을 안 해도 됩니다."], answer: 1,
        sourceUrl: "parents.html", sourceTitle: "Parents" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n여러 가지 채소와 고기를 넣고 매운 양념으로 볶은 한국 음식입니다.",
        options: ["김밥", "불고기", "비빔밥", "떡볶이"], answer: 3,
        sourceUrl: "tteokbokki.html", sourceTitle: "Tteokbokki" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n한국은 봄, 여름, 가을, 겨울 네 계절이 뚜렷합니다. 봄에는 꽃이 피고, 여름에는 덥고 습합니다. 가을에는 단풍이 들고, 겨울에는 눈이 옵니다.",
        options: ["한국의 음식 문화", "한국의 직장 문화", "한국의 사계절", "한국의 교통수단"], answer: 2,
        sourceUrl: "autumn.html", sourceTitle: "Autumn" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"편의점 이용 안내: 24시간 운영하며, 간단한 식사와 생필품을 구매할 수 있습니다. 교통카드 충전도 가능합니다.\"",
        options: ["교통카드 충전은 불가능합니다.", "편의점은 오전에만 운영합니다.", "편의점에서는 식사를 살 수 없습니다.", "편의점은 24시간 운영합니다."], answer: 3,
        sourceUrl: "store.html", sourceTitle: "Store" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"대중교통 이용 안내: 교통카드를 사용하면 버스와 지하철을 환승할 때 할인을 받을 수 있습니다. 현금 결제 시에는 환승 할인이 적용되지 않습니다.\"",
        options: ["현금으로 내도 환승 할인을 받습니다.", "교통카드를 사용하면 환승 할인을 받을 수 있습니다.", "환승 할인은 항상 적용됩니다.", "교통카드는 지하철에서만 사용할 수 있습니다."], answer: 1,
        sourceUrl: "commute.html", sourceTitle: "Commute" }
    ]
  },
  {
    id: "set_06",
    title: "EPS-TOPIK Mock Test #6",
    free: true,
    listening: [
      { id: "L01", audioText: "몸이 어디가 아파요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["머리가 아파요.", "회사예요.", "비싸요.", "늦었어요."], answer: 0,
        sourceUrl: "meorigaapayo1.html", sourceTitle: "My Head Hurts" },
      { id: "L02", audioText: "열이 나요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["아니요, 늦었어요.", "아니요, 배고파요.", "네, 열이 나요.", "네, 비싸요."], answer: 2,
        sourceUrl: "yeorinayo1.html", sourceTitle: "I Have a Fever" },
      { id: "L03", audioText: "무슨 일이에요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["늦었어요.", "비싸요.", "사고가 났어요.", "가까워요."], answer: 2,
        sourceUrl: "museunirieyo1.html", sourceTitle: "What Happened?" },
      { id: "L04", audioText: "도움이 필요해요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 비싸요.", "네, 도움이 필요해요.", "아니요, 맛있어요.", "아니요, 가까워요."], answer: 1,
        sourceUrl: "doumipilyohaeyo1.html", sourceTitle: "I Need Help" },
      { id: "L05", audioText: "이쪽으로 가면 돼요?", question: "다음을 듣고 알맞은 대답을 고르세요.",
        options: ["네, 이쪽으로 가세요.", "아니요, 비싸요.", "아니요, 늦었어요.", "네, 맛있어요."], answer: 0,
        sourceUrl: "ttaraoseyo1.html", sourceTitle: "Follow Me" },
      { id: "L06", audioText: "남자: 작업 중 손을 베였어요. 여자: 빨리 응급실로 가세요.", question: "남자에게 무슨 일이 있었습니까?",
        options: ["감전됐다", "넘어졌다", "손을 다쳤다", "화상을 입었다"], answer: 2,
        sourceUrl: "yeolsang.html", sourceTitle: "Laceration / Cut" },
      { id: "L07", audioText: "남자: 뜨거운 물에 손을 데었어요. 여자: 찬물로 식히세요.", question: "여자는 남자에게 무엇을 하라고 했습니까?",
        options: ["찬물로 식히기", "붕대를 감기", "약을 바르기", "병원에 가기"], answer: 0,
        sourceUrl: "hwasang.html", sourceTitle: "Burn" },
      { id: "L08", audioText: "높은 곳에서 작업할 때는 안전벨트를 착용하세요.", question: "높은 곳에서 작업할 때 무엇을 착용해야 합니까?",
        options: ["모자", "안전벨트", "마스크", "장갑"], answer: 1,
        sourceUrl: "anjeondae.html", sourceTitle: "Safety Harness" },
      { id: "L09", audioText: "남자: 바닥이 미끄러워요. 조심하세요. 여자: 네, 알겠습니다.", question: "남자는 여자에게 무엇을 조심하라고 했습니까?",
        options: ["뜨거운 물건", "날카로운 도구", "미끄러운 바닥", "무거운 짐"], answer: 2,
        sourceUrl: "jeondo.html", sourceTitle: "Slip / Trip" },
      { id: "L10", audioText: "이 기계에 손이 끼이지 않도록 조심하세요.", question: "무엇을 조심해야 합니까?",
        options: ["기계가 뜨거운 것", "손이 기계에 끼이는 것", "기계 소리가 큰 것", "기계가 넘어지는 것"], answer: 1,
        sourceUrl: "hyeopchak.html", sourceTitle: "Jamming / Pinched" },
      { id: "L11", audioText: "가스 누출 경보음이 울리면 즉시 대피하세요.", question: "경보음이 울리면 어떻게 해야 합니까?",
        options: ["계속 일한다", "즉시 대피한다", "기계를 켠다", "창문을 닫는다"], answer: 1,
        sourceUrl: "gyeongbogi.html", sourceTitle: "Alarm" },
      { id: "L12", audioText: "이 마스크는 먼지가 많은 곳에서 착용하세요.", question: "이 마스크는 언제 착용해야 합니까?",
        options: ["더울 때", "비가 올 때", "추울 때", "먼지가 많을 때"], answer: 3,
        sourceUrl: "bangjinmaseukeu.html", sourceTitle: "Dust Mask" },
      { id: "L13", audioText: "남자: 여기 차단기가 내려갔어요. 여자: 제가 올릴게요.", question: "여자는 무엇을 하려고 합니까?",
        options: ["전등을 켜기", "기계를 끄기", "차단기를 올리기", "문을 열기"], answer: 2,
        sourceUrl: "chadangi.html", sourceTitle: "Circuit Breaker" },
      { id: "L14", audioText: "전선을 만지기 전에 접지 상태를 확인하세요.", question: "전선을 만지기 전에 무엇을 확인해야 합니까?",
        options: ["전선 길이", "전선 색깔", "전선 무게", "접지 상태"], answer: 3,
        sourceUrl: "jeopji.html", sourceTitle: "Grounding / Earthing" },
      { id: "L15", audioText: "이 구역은 물기가 있으니 사용하지 마세요.", question: "이 구역에서 무엇을 하지 말아야 합니까?",
        options: ["이동", "대화", "전기 기구 사용", "휴식"], answer: 2,
        sourceUrl: "mulgi_eomgeum.html", sourceTitle: "Keep Away from Water" },
      { id: "L16", audioText: "화재 시 소화전 위치를 미리 확인해 두세요.", question: "화재 시 무엇을 미리 확인해야 합니까?",
        options: ["비상구 색깔", "경보음 크기", "소화전 위치", "소화기 무게"], answer: 2,
        sourceUrl: "sohwajeon.html", sourceTitle: "Fire Hydrant" },
      { id: "L17", audioText: "이 구역은 차량 출입을 금지합니다.", question: "이 구역에서 금지하는 것은 무엇입니까?",
        options: ["휴식", "보행", "차량 출입", "대화"], answer: 2,
        sourceUrl: "tapseunggeumji.html", sourceTitle: "No Riding" },
      { id: "L18", audioText: "인화물질 근처에서는 불을 사용하지 마세요.", question: "인화물질 근처에서 하지 말아야 할 것은 무엇입니까?",
        options: ["불 사용", "휴식", "대화", "이동"], answer: 0,
        sourceUrl: "hwagi_eomgeum.html", sourceTitle: "No Flammable Materials" },
      { id: "L19", audioText: "작업장은 항상 깨끗하게 정리 정돈하세요.", question: "작업장을 어떻게 유지해야 합니까?",
        options: ["최대한 어둡게", "좁게", "물건을 쌓아 두게", "깨끗하게 정리 정돈"], answer: 3,
        sourceUrl: "jeongrijeongdon.html", sourceTitle: "Tidying Up" },
      { id: "L20", audioText: "환기가 잘 안 되는 곳에서는 마스크를 착용하세요.", question: "환기가 잘 안 되는 곳에서 무엇을 착용해야 합니까?",
        options: ["장갑", "모자", "안전화", "마스크"], answer: 3,
        sourceUrl: "hwangi.html", sourceTitle: "Ventilation" }
    ],
    reading: [
      { id: "R01", question: "다음 설명에 알맞은 단어를 고르세요.\n\n작은 철사나 전선을 자를 때 쓰는 도구입니다.",
        options: ["망치", "니퍼", "펜치", "가위"], answer: 1,
        sourceUrl: "nipeo.html", sourceTitle: "Nippers" },
      { id: "R02", question: "다음 설명에 알맞은 단어를 고르세요.\n\n바닥이나 벽이 수평인지 확인할 때 쓰는 도구입니다.",
        options: ["저울", "온도계", "수평계", "줄자"], answer: 2,
        sourceUrl: "supyeongdae.html", sourceTitle: "Spirit Level" },
      { id: "R03", question: "다음 상황 설명에 알맞은 문장을 고르세요.\n\n한 사람이 바닥에 쓰러져서 움직이지 않습니다.",
        options: ["운동을 하고 있습니다.", "의식을 잃었습니다.", "잠을 자고 있습니다.", "일을 하고 있습니다."], answer: 1,
        sourceUrl: "honsu_gijeol.html", sourceTitle: "Fainting / Unconsciousness" },
      { id: "R04", question: "다음 표지판 설명에 어울리는 문장을 고르세요.\n\n빨간 바탕에 금지 표시가 그려진 표지판입니다.",
        options: ["이곳은 식사하는 곳입니다.", "이곳은 쉬는 곳입니다.", "이곳은 출입을 금지합니다.", "이곳은 자유롭게 다닐 수 있습니다."], answer: 2,
        sourceUrl: "geumji.html", sourceTitle: "Prohibition" },
      { id: "R05", question: "다음 중 밑줄 친 조사가 맞는 것을 고르세요.\n\n다친 사람___ 병원에 데려갔어요.",
        options: ["다친 사람에서 병원에 데려갔어요.", "다친 사람도 병원에 데려갔어요.", "다친 사람이 병원에 데려갔어요.", "다친 사람을 병원에 데려갔어요."], answer: 3,
        sourceUrl: "sangcheo.html", sourceTitle: "Wound" },
      { id: "R06", question: "다음 중 밑줄 친 부분이 맞는 것을 고르세요.\n\n다치면 바로 병원에 ______.",
        options: ["가아요.", "가여요.", "가요.", "갔요."], answer: 2,
        sourceUrl: "goljeol.html", sourceTitle: "Fracture" },
      { id: "R07", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"소화기 점검 안내: 매달 첫째 주 월요일에 점검합니다. 이상이 있으면 관리자에게 알려 주세요.\"\n\n소화기는 언제 점검합니까?",
        options: ["매주 금요일", "매달 첫째 주 월요일", "분기별 1회", "매일 아침"], answer: 1,
        sourceUrl: "jeongbi.html", sourceTitle: "Maintenance" },
      { id: "R08", question: "다음 단어와 관계있는 것을 고르세요.\n\n소독",
        options: ["물건을 포장하는 것입니다.", "상처나 물건을 깨끗하게 하는 것입니다.", "휴가를 신청하는 것입니다.", "월급을 계산하는 것입니다."], answer: 1,
        sourceUrl: "sodok.html", sourceTitle: "Disinfection" },
      { id: "R09", question: "다음 단어와 관계있는 것을 고르세요.\n\n누전",
        options: ["가스가 새는 것입니다.", "전기가 새어 나오는 것입니다.", "물이 새는 것입니다.", "소리가 새는 것입니다."], answer: 1,
        sourceUrl: "nujeon.html", sourceTitle: "Electricity Leakage" },
      { id: "R10", question: "다음 안내문을 읽고 물음에 답하세요.\n\n\"대피소 이용 안내: 비상시 3층 대피소로 이동하세요. 엘리베이터는 사용하지 마세요.\"\n\n비상시 어디로 이동해야 합니까?",
        options: ["1층 로비", "지하 주차장", "옥상", "3층 대피소"], answer: 3,
        sourceUrl: "daepiso.html", sourceTitle: "Shelter" },
      { id: "R11", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n사고 원인: _____________",
        options: ["생일 선물", "합선", "가족 모임", "출근 시간"], answer: 1,
        sourceUrl: "hapseon.html", sourceTitle: "Short Circuit" },
      { id: "R12", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n화학물질을 다룰 때는 ______ 환기를 시켜야 합니다.",
        options: ["반드시", "반드시는", "반드시도", "반드시가"], answer: 0,
        sourceUrl: "inhwasung.html", sourceTitle: "Flammability" },
      { id: "R13", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n부식성 물질은 ______ 다뤄야 합니다.",
        options: ["조심스러움", "조심스러운", "조심스럽게", "조심"], answer: 2,
        sourceUrl: "busiksung.html", sourceTitle: "Corrosiveness" },
      { id: "R14", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n작업장에서는 ______ 정리 정돈을 해야 합니다.",
        options: ["항상은", "항상이", "항상", "항상도"], answer: 2,
        sourceUrl: "cheongso.html", sourceTitle: "Cleaning" },
      { id: "R15", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n독성 물질을 마셨을 때는 즉시 ______",
        options: ["집에서 쉬어야 합니다.", "물을 안 마셔야 합니다.", "그냥 두어야 합니다.", "병원에 가야 합니다."], answer: 3,
        sourceUrl: "jungdok.html", sourceTitle: "Poisoning / Intoxication" },
      { id: "R16", question: "빈칸에 들어갈 가장 알맞은 것을 고르세요.\n\n폭발 위험이 있는 구역에서는 ______ 이렇게 하면 큰 사고를 막을 수 있습니다.",
        options: ["라이터를 사용해도 됩니다.", "화기를 사용하면 안 됩니다.", "불을 켜도 됩니다.", "담배를 피워도 됩니다."], answer: 1,
        sourceUrl: "pokbal.html", sourceTitle: "Explosion" },
      { id: "R17", question: "다음 설명에 알맞은 어휘를 고르세요.\n\n숨을 쉬기 어려운 상태로, 산소가 부족할 때 나타납니다.",
        options: ["어지러움", "구토", "기절", "질식"], answer: 3,
        sourceUrl: "jilsik.html", sourceTitle: "Suffocation" },
      { id: "R18", question: "다음 글을 읽고 무엇에 대한 글인지 고르세요.\n\n작업 중 사고가 발생하면 당황하지 말고 먼저 안전한 곳으로 이동해야 합니다. 그 다음 관리자에게 알리고, 필요하면 119에 신고해야 합니다.",
        options: ["월급 계산 방법", "제품 포장 방법", "휴가 신청 절차", "사고 발생 시 대처 방법"], answer: 3,
        sourceUrl: "chungdol.html", sourceTitle: "Collision" },
      { id: "R19", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"화상 응급처치 안내: 화상을 입으면 먼저 찬물로 식히고, 물집을 터뜨리지 마세요. 심하면 병원에 가야 합니다.\"",
        options: ["화상을 입으면 찬물로 식혀야 합니다.", "화상을 입으면 뜨거운 물로 식혀야 합니다.", "화상은 병원에 갈 필요가 없습니다.", "물집은 바로 터뜨려야 합니다."], answer: 0,
        sourceUrl: "banchanggo.html", sourceTitle: "Adhesive Plaster" },
      { id: "R20", question: "다음을 읽고 내용과 같은 것을 고르세요.\n\n\"어지러움 증상 대처 안내: 어지러우면 즉시 앉거나 누워서 쉬어야 합니다. 증상이 계속되면 관리자에게 알려야 합니다.\"",
        options: ["어지러우면 뛰어야 합니다.", "어지러워도 계속 일해야 합니다.", "어지러우면 즉시 앉거나 누워서 쉬어야 합니다.", "어지러움은 신경 쓰지 않아도 됩니다."], answer: 2,
        sourceUrl: "guto.html", sourceTitle: "Vomiting" }
    ]
  }
];
