const quizDB = [
            { title: "Academy", url: "academy.html", keywords: "academy school study education" },
            { title: "Airplane", url: "airplane.html", keywords: "airplane flight travel sky" },
            { title: "Airport", url: "airport.html", keywords: "airport travel flight airplane" },
            { title: "Animals", url: "animals.html", keywords: "animals pet nature zoo" },
            { title: "Apartment", url: "apartment.html", keywords: "apartment house living room" },
            { title: "Apple", url: "apple.html", keywords: "apple fruit food red" },
            { title: "Autumn", url: "autumn.html", keywords: "autumn fall season weather" },
            { title: "Baby", url: "baby.html", keywords: "baby child kid family" },
            { title: "Bed", url: "bed.html", keywords: "bed furniture sleep" },
            { title: "Bibimbap", url: "bibimbap.html", keywords: "bibimbap food korean rice" },
            { title: "Bird", url: "bird.html", keywords: "bird animal sky fly" },
            { title: "Body", url: "body.html", keywords: "body human health" },
            { title: "Book", url: "book.html", keywords: "book reading library study" },
            { title: "Bread", url: "bread.html", keywords: "bread food bakery" },
            { title: "Brother", url: "brother.html", keywords: "brother family sibling" },
            { title: "Buildings", url: "buildings.html", keywords: "buildings house city" },
            { title: "Bulgogi", url: "bulgogi.html", keywords: "bulgogi food korean meat" },
            { title: "Bus", url: "bus.html", keywords: "bus transport commute" },
            { title: "Cash", url: "cash.html", keywords: "cash money currency" },
            { title: "Cat", url: "cat.html", keywords: "cat animal pet" },
            { title: "Chair", url: "chair.html", keywords: "chair furniture seat" },
            { title: "City", url: "city.html", keywords: "city buildings urban" },
            { title: "Class", url: "class.html", keywords: "class school study student" },
            { title: "Clothes", url: "clothes.html", keywords: "clothes fashion wear" },
            { title: "Colors", url: "colors.html", keywords: "colors red blue green" },
            { title: "Commute", url: "commute.html", keywords: "commute work transport travel" },
            { title: "Company", url: "company.html", keywords: "company work job business" },
            { title: "Cooking", url: "cooking.html", keywords: "cooking food kitchen" },
            { title: "Dad", url: "dad.html", keywords: "dad father family parent" },
            { title: "Dawn", url: "dawn.html", keywords: "dawn morning time" },
            { title: "Desk", url: "desk.html", keywords: "desk furniture study school" },
            { title: "Dog", url: "dog.html", keywords: "dog animal pet puppy" },
            { title: "Door", url: "door.html", keywords: "door house entrance" },
            { title: "Economy", url: "economy.html", keywords: "economy money finance" },
            { title: "Electronics", url: "electronics.html", keywords: "electronics tech device" },
            { title: "Emotions", url: "emotions.html", keywords: "emotions feelings mood" },
            { title: "Evening", url: "evening.html", keywords: "evening night time" },
            { title: "Exam", url: "exam.html", keywords: "exam test study school" },
            { title: "Family", url: "family.html", keywords: "family parents child sibling" },
            { title: "Feelings", url: "feelings.html", keywords: "feelings mood emotion" },
            { title: "Fish", url: "fish.html", keywords: "fish animal sea ocean" },
            { title: "Flower", url: "flower.html", keywords: "flower nature plant" },
            { title: "Food", url: "food.html", keywords: "food eat meal" },
            { title: "Friend", url: "friend.html", keywords: "friend person relationship" },
            { title: "Fruit", url: "fruit.html", keywords: "fruit food healthy" },
            { title: "Furniture", url: "furniture.html", keywords: "furniture house bed chair" },
            { title: "Gift", url: "gift.html", keywords: "gift present surprise" },
            { title: "Gimbap", url: "gimbap.html", keywords: "gimbap food korean" },
            { title: "Happiness", url: "happiness.html", keywords: "happiness joy emotion" },
            { title: "Health", url: "health.html", keywords: "health body exercise" },
            { title: "Hobbies", url: "hobbies.html", keywords: "hobbies activity free time" },
            { title: "Homework", url: "homework.html", keywords: "homework study school" },
            { title: "House", url: "house.html", keywords: "house home living" },
            { title: "Jobs", url: "jobs.html", keywords: "jobs work profession" },
            { title: "Joy", url: "joy.html", keywords: "joy happiness emotion" },
            { title: "Kimchi", url: "kimchi1.html", keywords: "kimchi food korean spicy" },
            { title: "Kitchen", url: "kitchen.html", keywords: "kitchen cooking house" },
            { title: "Landscapes", url: "landscapes.html", keywords: "landscapes nature scenery" },
            { title: "Lion", url: "lion.html", keywords: "lion animal nature" },
            { title: "LivingRoom", url: "livingRoom.html", keywords: "livingRoom house home" },
            { title: "Love", url: "love.html", keywords: "love emotion feelings" },
            { title: "Lunch", url: "lunch.html", keywords: "lunch food meal time" },
            { title: "Market", url: "market.html", keywords: "market shopping store" },
            { title: "Meat", url: "meat.html", keywords: "meat food protein" },
            { title: "Money", url: "money.html", keywords: "money cash finance" },
            { title: "Mood", url: "mood.html", keywords: "mood emotion feelings" },
            { title: "Morning", url: "morning.html", keywords: "morning dawn time" },
            { title: "Mother", url: "mother.html", keywords: "mother mom family parent" },
            { title: "Mountain", url: "mountain.html", keywords: "mountain nature hiking" },
            { title: "Nature", url: "nature.html", keywords: "nature plant scenery" },
            { title: "Parents", url: "parents.html", keywords: "parents family mom dad" },
            { title: "Pencil", url: "pencil.html", keywords: "pencil school writing" },
            { title: "Places", url: "places.html", keywords: "places location travel" },
            { title: "Purchase", url: "purchase.html", keywords: "purchase shopping buy" },
            { title: "Rain", url: "rain.html", keywords: "rain weather nature" },
            { title: "Ramen", url: "ramen.html", keywords: "ramen food noodle" },
            { title: "Restroom", url: "restroom.html", keywords: "restroom bathroom toilet" },
            { title: "Sadness", url: "sadness.html", keywords: "sadness emotion feelings" },
            { title: "Samgyeopsal", url: "samgyeopsal.html", keywords: "samgyeopsal food korean meat" },
            { title: "School", url: "school.html", keywords: "school study education" },
            { title: "Sea", url: "sea.html", keywords: "sea ocean water nature" },
            { title: "Sister", url: "sister.html", keywords: "sister family sibling" },
            { title: "Sky", url: "sky.html", keywords: "sky nature weather" },
            { title: "Snow", url: "snow.html", keywords: "snow winter weather" },
            { title: "Soup", url: "soup.html", keywords: "soup food meal" },
            { title: "Sports", url: "sports.html", keywords: "sports exercise activity" },
            { title: "Spring", url: "spring.html", keywords: "spring season weather" },
            { title: "Store", url: "store.html", keywords: "store market shopping" },
            { title: "Student", url: "student.html", keywords: "student school study" },
            { title: "Study", url: "study.html", keywords: "study learn school" },
            { title: "Summer", url: "summer.html", keywords: "summer season weather" },
            { title: "Taxi", url: "taxi.html", keywords: "taxi transport car" },
            { title: "Teacher", url: "teacher.html", keywords: "teacher school education" },
            { title: "Textbook", url: "textbook.html", keywords: "textbook study school" },
            { title: "Time", url: "time.html", keywords: "time clock schedule" },
            { title: "Today", url: "today.html", keywords: "today time" },
            { title: "Tomorrow", url: "tomorrow.html", keywords: "tomorrow time" },
            { title: "Tourism", url: "tourism.html", keywords: "tourism travel trip" },
            { title: "Train", url: "train.html", keywords: "train transport travel" },
            { title: "Transport", url: "transport.html", keywords: "transport commute car bus" },
            { title: "Travel", url: "travel.html", keywords: "travel trip tourism" },
            { title: "Tteokbokki", url: "tteokbokki.html", keywords: "tteokbokki food korean spicy" },
            { title: "Vocabulary", url: "vocabulary.html", keywords: "vocabulary words study" },
            { title: "Water", url: "water.html", keywords: "water drink nature" },
            { title: "Weather", url: "weather.html", keywords: "weather sky rain snow" },
            { title: "Window", url: "window.html", keywords: "window house glass" },
            { title: "Word", url: "word.html", keywords: "word vocabulary language" },
            { title: "lover sentence", url: "sentencelover1.html", keywords: "sentence lover study korean phrase" },
            { title: "Hello", url: "annyeonghaseyo1.html", keywords: "hello hi greeting korean greeting" },
            { title: "Thank You", url: "gamsahamnida1.html", keywords: "thank you thanks gratitude appreciation" },
            { title: "It's Fun", url: "jaemiisseoyo1.html", keywords: "it's fun fun interesting enjoyable" },
            { title: "Good Night", url: "jaljayo1.html", keywords: "good night sleep bedtime" },
            { title: "What's Your Name", url: "irum1.html", keywords: "what's your name name introduction" },
            { title: "Nice to Meet You", url: "bangawoyo1.html", keywords: "nice to meet you introduction greeting" },
            { title: "How Have You Been", url: "jaljinaesseoyo1.html", keywords: "how have you been greeting conversation" },
            { title: "It's Okay", url: "gwaenchanayo1.html", keywords: "it's okay okay no problem fine" },
            { title: "Im Sorry", url: "mianhaeyo1.html", keywords: "i'm sorry sorry apology excuse me" },
            { title: "I Love You", url: "saranghaeyo1.html", keywords: "i love you love romance affection" },
            { title: "Please Speak Slowly", url: "cheoncheonhi1.html", keywords: "please speak slowly slow speaking conversation" },
            { title: "I'm Learning Korean", url: "hangukeo1.html", keywords: "i'm learning korean study korean language" },
            { title: "Help Me", url: "dowajuseyo1.html", keywords: "help me help emergency assistance" },
            { title: "Where Is the Restroom?", url: "hwajangsil1.html", keywords: "where is the restroom restroom bathroom toilet" },
            { title: "How Much Is It", url: "eolmayeyo1.html", keywords: "how much is it price cost shopping" },
            { title: "Where Is It", url: "eodi1.html", keywords: "where is it where location directions" },
            { title: "Im Happy", url: "haengbok1.html", keywords: "i'm happy happy feeling emotion" },
            { title: "Im Sleepy", url: "jollyeo1.html", keywords: "i'm sleepy sleepy tired bedtime" },
            { title: "Im Tired", url: "pigon1.html", keywords: "i'm tired tired exhausted fatigue" },
            { title: "Im Thirsty", url: "mongmalla1.html", keywords: "i'm thirsty thirsty drink water" },
            { title: "I'm Hungry", url: "baegopa1.html", keywords: "i'm hungry hungry food meal" },
            { title: "I Don't Understand", url: "ihaemot1.html", keywords: "i don't understand understand confusion learning" },
            { title: "I Understand", url: "ihae1.html", keywords: "i understand understand got it learning" },
            { title: "Please Speak Slowly", url: "cheoncheonhi1.html", keywords: "please speak slowly slow speaking conversation" },
            { title: "Im Sad", url: "seulpeo1.html", keywords: "i'm sad sad emotion feeling" },
            { title: "Im Angry", url: "hwana1.html", keywords: "i'm angry angry mad emotion" },
            { title: "Im Scared", url: "museowo1.html", keywords: "i'm scared scared afraid fear" },
            { title: "I Miss You", url: "bogosipeo1.html", keywords: "i miss you miss longing affection" },
            { title: "Im Sick", url: "apayo1.html", keywords: "i'm sick sick ill health" },
            { title: "Im Nervous", url: "ginjang1.html", keywords: "i'm nervous nervous anxious feeling" },
            { title: "I Feel Good", url: "gibun1.html", keywords: "i feel good good feeling mood" },
            { title: "Im Busy", url: "bappa1.html", keywords: "i'm busy busy work schedule" },
            { title: "Im Free", url: "sigan1.html", keywords: "i'm free available free time schedule" },
            { title: "Don't Worry", url: "geokjeong1.html", keywords: "don't worry worry relax comfort" },
            { title: "I Like It", url: "joayo1.html", keywords: "i like it like favorite preference" },
            { title: "I Don't Like It", url: "anjoa1.html", keywords: "i don't like it dislike don't like preference" },
            { title: "I Love It", url: "jeongmal1.html", keywords: "i love it love favorite really like" },
            { title: "I Hate It", url: "sireo1.html", keywords: "i hate it hate dislike emotion" },
            { title: "Im Ready", url: "junbi1.html", keywords: "i'm ready ready prepared let's go" },
            { title: "Not Yet", url: "ajig1.html", keywords: "not yet wait later unfinished" },
            { title: "Please Wait", url: "gidaryeo1.html", keywords: "please wait wait hold on moment" },
            { title: "Hurry Up", url: "ppalli1.html", keywords: "hurry up quick faster rush" },
            { title: "Let's Eat", url: "meogeo1.html", keywords: "let's eat eat meal food" },
            { title: "Let's Drink", url: "masyeo1.html", keywords: "let's drink drink beverage together" },
            { title: "Let's Study", url: "gongbu1.html", keywords: "let's study study learn korean" },
            { title: "Good Morning", url: "joheun1.html", keywords: "good morning morning greeting" },
            { title: "See You Later", url: "najunge1.html", keywords: "see you later goodbye farewell" },
            { title: "See You Tomorrow", url: "naeil1.html", keywords: "see you tomorrow tomorrow goodbye farewell" },
            { title: "You're Welcome", url: "cheonman1.html", keywords: "you're welcome welcome no problem thanks" },
            { title: "Excuse Me", url: "sillye1.html", keywords: "excuse me pardon attention polite" },
            { title: "No Problem", url: "munje1.html", keywords: "no problem okay it's fine don't worry" },
            { title: "What Does This Mean?", url: "ige1.html", keywords: "what does this mean meaning translation korean" },
            { title: "It's Too Expensive", url: "bissayo1.html", keywords: "it's too expensive expensive price shopping" },
            { title: "It's Cheap", url: "ssayo1.html", keywords: "it's cheap cheap affordable price shopping" },
            { title: "Water Please", url: "muljuseyo1.html", keywords: "water please water drink beverage" },
            { title: "It's Cold", url: "chagawo1.html", keywords: "it's cold cold weather temperature" },
            { title: "It's Hot", url: "tteugeo1.html", keywords: "it's hot hot weather temperature" },
            { title: "It's Salty", url: "jjayo1.html", keywords: "it's salty salty taste food" },
            { title: "It's Sweet", url: "dalayo1.html", keywords: "it's sweet sweet taste dessert" },
            { title: "It's Spicy", url: "maewoyo1.html", keywords: "it's spicy spicy hot food" },
            { title: "It's Delicious", url: "masisseo1.html", keywords: "it's delicious delicious tasty food" },
            { title: "Let's Go", url: "gayo1.html", keywords: "let's go go together invitation" },
            { title: "Wait a Moment", url: "jamsiman1.html", keywords: "wait a moment wait hold on please" },
            { title: "Coffee Please", url: "keopijuseyo1.html", keywords: "coffee please coffee drink beverage" },
            { title: "What Happened?", url: "museunirieyo1.html", keywords: "what happened happened problem situation" },
            { title: "Why?", url: "waeyo1.html", keywords: "why question reason" },
            { title: "Really?", url: "jeongmalyo1.html", keywords: "really surprise question" },
            { title: "I Miss You", url: "bogosipeoyo1.html", keywords: "i miss you miss longing affection" },
            { title: "Happy Birthday", url: "saengilchukha1.html", keywords: "happy birthday birthday celebration greeting" },
            { title: "Good Luck", url: "haenguneulbireoyo1.html", keywords: "good luck luck encouragement wish" },
            { title: "Good Job", url: "jalhaesseoyo1.html", keywords: "good job well done praise encouragement" },
            { title: "Be Careful", url: "josimhaseyo1.html", keywords: "be careful careful safety warning" },
            { title: "Stand Up", url: "ireonaseyo1.html", keywords: "stand up get up classroom instruction" },
            { title: "Sit Down", url: "aneuseyo1.html", keywords: "sit down take a seat classroom instruction" },
            { title: "Are You Okay?", url: "gwaenchanayo1.html", keywords: "are you okay okay concern health" },
            { title: "I'm Full", url: "baebulleoyo1.html", keywords: "i'm full full food meal" },
            { title: "See You Soon", url: "ttaobwayo1.html", keywords: "see you soon goodbye farewell" },
            { title: "Have a Nice Day", url: "joeunharubonaeseyo1.html", keywords: "have a nice day greeting farewell" },
            { title: "Come In", url: "deureooseyo1.html", keywords: "come in enter welcome invitation" },
            { title: "Please Wait", url: "gidaryeojuseyo1.html", keywords: "please wait wait hold on moment" },
            { title: "I Don't Know", url: "moreugesseoyo1.html", keywords: "i don't know don't know answer" },
            { title: "That's Right", url: "majayo1.html", keywords: "that's right correct yes agree" },
            { title: "That's Cool", url: "meotjyeoyo1.html", keywords: "that's cool cool awesome compliment" },
            { title: "That's Cute", url: "gwiyeowoyo1.html", keywords: "that's cute cute adorable compliment" },
            { title: "That's Beautiful", url: "areumdawoyo1.html", keywords: "that's beautiful beautiful pretty compliment" },
            { title: "That's Amazing", url: "nollawoyo1.html", keywords: "that's amazing amazing incredible surprise" },
            { title: "That's Interesting", url: "heungmirowoyo1.html", keywords: "that's interesting interesting curious conversation" },
            { title: "That's Awesome", url: "jeongmalmeotjyeoyo1.html", keywords: "that's awesome awesome excellent compliment" },
            { title: "Good Bye", url: "bye2.html", keywords: "good bye goodbye farewell see you" },
            { title: "That's Great", url: "jeongmaljoayo1.html", keywords: "that's great great excellent praise" },
            { title: "I Agree", url: "donguihaeyo1.html", keywords: "i agree agree opinion conversation" },
            { title: "That's Wrong", url: "teullyeosseoyo1.html", keywords: "that's wrong wrong incorrect mistake" },
            { title: "Friend sentence ", url: "sentencefriend1.html", keywords: "sentence friend study korean conversation" }
        ];